# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_openvet.ui'
#
# Created: Sat Mar 29 11:26:29 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.stackedWidget.setStyleSheet("background-color: rgba(188, 255, 231, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Consultation = QtGui.QWidget()
        self.page_Consultation.setObjectName("page_Consultation")
        self.tabWidget_fiches = QtGui.QTabWidget(self.page_Consultation)
        self.tabWidget_fiches.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.tabWidget_fiches.setAutoFillBackground(False)
        self.tabWidget_fiches.setStyleSheet("None")
        self.tabWidget_fiches.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_fiches.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_fiches.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_fiches.setTabsClosable(True)
        self.tabWidget_fiches.setObjectName("tabWidget_fiches")
        self.tab_fiche1 = QtGui.QWidget()
        self.tab_fiche1.setObjectName("tab_fiche1")
        self.frame_client = QtGui.QFrame(self.tab_fiche1)
        self.frame_client.setGeometry(QtCore.QRect(0, 0, 474, 120))
        self.frame_client.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_client.setFrameShape(QtGui.QFrame.Box)
        self.frame_client.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_client.setLineWidth(1)
        self.frame_client.setObjectName("frame_client")
        self.comboBox_client = QtGui.QComboBox(self.frame_client)
        self.comboBox_client.setGeometry(QtCore.QRect(10, 10, 371, 27))
        self.comboBox_client.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_client.setEditable(True)
        self.comboBox_client.setObjectName("comboBox_client")
        self.textBrowser_client = QtGui.QTextBrowser(self.frame_client)
        self.textBrowser_client.setGeometry(QtCore.QRect(10, 50, 451, 61))
        self.textBrowser_client.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_client.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_client.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_client.setLineWidth(1)
        self.textBrowser_client.setMidLineWidth(0)
        self.textBrowser_client.setObjectName("textBrowser_client")
        self.toolButton_ClientInfo = QtGui.QToolButton(self.frame_client)
        self.toolButton_ClientInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClientInfo.setIcon(icon1)
        self.toolButton_ClientInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_ClientInfo.setObjectName("toolButton_ClientInfo")
        self.frame_animal = QtGui.QFrame(self.tab_fiche1)
        self.frame_animal.setGeometry(QtCore.QRect(536, 0, 482, 120))
        self.frame_animal.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_animal.setFrameShape(QtGui.QFrame.Box)
        self.frame_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_animal.setObjectName("frame_animal")
        self.comboBox_Animal = QtGui.QComboBox(self.frame_animal)
        self.comboBox_Animal.setGeometry(QtCore.QRect(10, 10, 261, 27))
        self.comboBox_Animal.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Animal.setEditable(True)
        self.comboBox_Animal.setObjectName("comboBox_Animal")
        self.textBrowser_animal = QtGui.QTextBrowser(self.frame_animal)
        self.textBrowser_animal.setGeometry(QtCore.QRect(10, 50, 454, 61))
        self.textBrowser_animal.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_animal.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_animal.setObjectName("textBrowser_animal")
        self.toolButton_AnimalInfo = QtGui.QToolButton(self.frame_animal)
        self.toolButton_AnimalInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        self.toolButton_AnimalInfo.setIcon(icon1)
        self.toolButton_AnimalInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_AnimalInfo.setObjectName("toolButton_AnimalInfo")
        self.toolButton_addAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addAnimal.setGeometry(QtCore.QRect(510, 0, 26, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addAnimal.setIcon(icon2)
        self.toolButton_addAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addAnimal.setObjectName("toolButton_addAnimal")
        self.toolButton_editAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editAnimal.setGeometry(QtCore.QRect(510, 32, 26, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editAnimal.setIcon(icon3)
        self.toolButton_editAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editAnimal.setObjectName("toolButton_editAnimal")
        self.toolButton_deleteAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteAnimal.setGeometry(QtCore.QRect(510, 64, 26, 26))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/delete2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deleteAnimal.setIcon(icon4)
        self.toolButton_deleteAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteAnimal.setObjectName("toolButton_deleteAnimal")
        self.toolButton_scan = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_scan.setGeometry(QtCore.QRect(493, 95, 26, 26))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/loupe2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scan.setIcon(icon5)
        self.toolButton_scan.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan.setObjectName("toolButton_scan")
        self.toolButton_addClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addClient.setGeometry(QtCore.QRect(474, 0, 26, 26))
        self.toolButton_addClient.setIcon(icon2)
        self.toolButton_addClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addClient.setObjectName("toolButton_addClient")
        self.toolButton_deleteClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteClient.setGeometry(QtCore.QRect(474, 64, 26, 26))
        self.toolButton_deleteClient.setIcon(icon4)
        self.toolButton_deleteClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteClient.setObjectName("toolButton_deleteClient")
        self.toolButton_editClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editClient.setGeometry(QtCore.QRect(474, 32, 26, 26))
        self.toolButton_editClient.setIcon(icon3)
        self.toolButton_editClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editClient.setObjectName("toolButton_editClient")
        self.tabWidget_fiches.addTab(self.tab_fiche1, "")
        self.tab_fiche2 = QtGui.QWidget()
        self.tab_fiche2.setObjectName("tab_fiche2")
        self.tabWidget_fiches.addTab(self.tab_fiche2, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_fiches.addTab(self.tab_7, "")
        self.stackedWidget.addWidget(self.page_Consultation)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menuDossiers_M_dicaux = QtGui.QMenu(self.menubar)
        self.menuDossiers_M_dicaux.setObjectName("menuDossiers_M_dicaux")
        self.menuComptabilit = QtGui.QMenu(self.menubar)
        self.menuComptabilit.setObjectName("menuComptabilit")
        self.menuD_clarations = QtGui.QMenu(self.menuComptabilit)
        self.menuD_clarations.setObjectName("menuD_clarations")
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuBase_de_donn_es = QtGui.QMenu(self.menuConfiguration)
        self.menuBase_de_donn_es.setObjectName("menuBase_de_donn_es")
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName("menuQuitter")
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName("menuStock")
        self.menuStatistiques = QtGui.QMenu(self.menubar)
        self.menuStatistiques.setObjectName("menuStatistiques")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Recettes = QtGui.QAction(MainWindow)
        self.action_Recettes.setObjectName("action_Recettes")
        self.actionD_penses = QtGui.QAction(MainWindow)
        self.actionD_penses.setObjectName("actionD_penses")
        self.action_Banque = QtGui.QAction(MainWindow)
        self.action_Banque.setObjectName("action_Banque")
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindow)
        self.actionRecoupement_bancaire.setObjectName("actionRecoupement_bancaire")
        self.actionTVA = QtGui.QAction(MainWindow)
        self.actionTVA.setObjectName("actionTVA")
        self.action2035 = QtGui.QAction(MainWindow)
        self.action2035.setObjectName("action2035")
        self.actionCommandes = QtGui.QAction(MainWindow)
        self.actionCommandes.setObjectName("actionCommandes")
        self.actionAnalyse = QtGui.QAction(MainWindow)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.action_Facturation = QtGui.QAction(MainWindow)
        self.action_Facturation.setObjectName("action_Facturation")
        self.actionBureau = QtGui.QAction(MainWindow)
        self.actionBureau.setObjectName("actionBureau")
        self.action_M_dicaments = QtGui.QAction(MainWindow)
        self.action_M_dicaments.setObjectName("action_M_dicaments")
        self.action_Pathologies = QtGui.QAction(MainWindow)
        self.action_Pathologies.setObjectName("action_Pathologies")
        self.actionBackup = QtGui.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionR_seau_S_curit = QtGui.QAction(MainWindow)
        self.actionR_seau_S_curit.setObjectName("actionR_seau_S_curit")
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuD_clarations.addAction(self.actionTVA)
        self.menuD_clarations.addAction(self.action2035)
        self.menuComptabilit.addAction(self.action_Recettes)
        self.menuComptabilit.addAction(self.actionD_penses)
        self.menuComptabilit.addAction(self.action_Banque)
        self.menuComptabilit.addAction(self.actionRecoupement_bancaire)
        self.menuComptabilit.addAction(self.menuD_clarations.menuAction())
        self.menuBase_de_donn_es.addAction(self.actionBackup)
        self.menuBase_de_donn_es.addAction(self.actionRestore)
        self.menuBase_de_donn_es.addAction(self.actionImport)
        self.menuConfiguration.addAction(self.actionBureau)
        self.menuConfiguration.addAction(self.action_Facturation)
        self.menuConfiguration.addAction(self.action_M_dicaments)
        self.menuConfiguration.addAction(self.action_Pathologies)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuBase_de_donn_es.menuAction())
        self.menuConfiguration.addAction(self.actionR_seau_S_curit)
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuStock.addAction(self.actionCommandes)
        self.menuStock.addAction(self.actionAnalyse)
        self.menubar.addAction(self.menuDossiers_M_dicaux.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuComptabilit.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuQuitter.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_fiches.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Open Vet", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_client.setToolTip(QtGui.QApplication.translate("MainWindow", "Double click pour sélectionner l\'édition", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_ClientInfo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_animal.setToolTip(QtGui.QApplication.translate("MainWindow", "Double click pour sélectionner l\'édition", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AnimalInfo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Nouvel animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Efface animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan.setToolTip(QtGui.QApplication.translate("MainWindow", "Recherche client / animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Nouveau client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Efface client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche1), QtGui.QApplication.translate("MainWindow", "Client1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche2), QtGui.QApplication.translate("MainWindow", "Client2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDossiers_M_dicaux.setTitle(QtGui.QApplication.translate("MainWindow", "Dossiers Médicaux", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComptabilit.setTitle(QtGui.QApplication.translate("MainWindow", "Comptabilité", None, QtGui.QApplication.UnicodeUTF8))
        self.menuD_clarations.setTitle(QtGui.QApplication.translate("MainWindow", "Déclarations", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase_de_donn_es.setTitle(QtGui.QApplication.translate("MainWindow", "Base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuitter.setTitle(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStock.setTitle(QtGui.QApplication.translate("MainWindow", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStatistiques.setTitle(QtGui.QApplication.translate("MainWindow", "Statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Recettes.setText(QtGui.QApplication.translate("MainWindow", "&Recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_penses.setText(QtGui.QApplication.translate("MainWindow", "&Dépenses", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Banque.setText(QtGui.QApplication.translate("MainWindow", "&Banque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoupement_bancaire.setText(QtGui.QApplication.translate("MainWindow", "Recoupement bancaire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTVA.setText(QtGui.QApplication.translate("MainWindow", "TVA", None, QtGui.QApplication.UnicodeUTF8))
        self.action2035.setText(QtGui.QApplication.translate("MainWindow", "2035", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommandes.setText(QtGui.QApplication.translate("MainWindow", "&Commandes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalyse.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Facturation.setText(QtGui.QApplication.translate("MainWindow", "&Facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setText(QtGui.QApplication.translate("MainWindow", "Bureau", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_M_dicaments.setText(QtGui.QApplication.translate("MainWindow", "&Médicaments", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Pathologies.setText(QtGui.QApplication.translate("MainWindow", "&Pathologies", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionR_seau_S_curit.setText(QtGui.QApplication.translate("MainWindow", "Réseau/Sécurité", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setToolTip(QtGui.QApplication.translate("MainWindow", "Quitter l\'application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
