# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_pathologie.ui'
#
# Created: Mon Mar 17 14:21:39 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogPathologie(object):
    def setupUi(self, DialogPathologie):
        DialogPathologie.setObjectName("DialogPathologie")
        DialogPathologie.resize(786, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPathologie.setWindowIcon(icon)
        self.pushButton_PlanTherapeutique = QtGui.QPushButton(DialogPathologie)
        self.pushButton_PlanTherapeutique.setGeometry(QtCore.QRect(610, 80, 151, 27))
        self.pushButton_PlanTherapeutique.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_PlanTherapeutique.setObjectName("pushButton_PlanTherapeutique")
        self.layoutWidget = QtGui.QWidget(DialogPathologie)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 11, 561, 106))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieDomaine.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieDomaine.setEditable(False)
        self.comboBox_PathologieDomaine.setObjectName("comboBox_PathologieDomaine")
        self.horizontalLayout_5.addWidget(self.comboBox_PathologieDomaine)
        self.toolButton_DomaineSelection = QtGui.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/valid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_DomaineSelection.setIcon(icon1)
        self.toolButton_DomaineSelection.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_DomaineSelection.setObjectName("toolButton_DomaineSelection")
        self.horizontalLayout_5.addWidget(self.toolButton_DomaineSelection)
        self.toolButton_AddSelection_2 = QtGui.QToolButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddSelection_2.setIcon(icon2)
        self.toolButton_AddSelection_2.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddSelection_2.setObjectName("toolButton_AddSelection_2")
        self.horizontalLayout_5.addWidget(self.toolButton_AddSelection_2)
        self.toolButton_DeleteDommaine = QtGui.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/delete2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_DeleteDommaine.setIcon(icon3)
        self.toolButton_DeleteDommaine.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_DeleteDommaine.setObjectName("toolButton_DeleteDommaine")
        self.horizontalLayout_5.addWidget(self.toolButton_DeleteDommaine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_PathologiePathologie = MyComboBox(self.layoutWidget)
        self.comboBox_PathologiePathologie.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologiePathologie.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologiePathologie.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologiePathologie.setEditable(False)
        self.comboBox_PathologiePathologie.setObjectName("comboBox_PathologiePathologie")
        self.horizontalLayout_6.addWidget(self.comboBox_PathologiePathologie)
        self.toolButton_AddPathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_AddPathologie.setIcon(icon2)
        self.toolButton_AddPathologie.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddPathologie.setObjectName("toolButton_AddPathologie")
        self.horizontalLayout_6.addWidget(self.toolButton_AddPathologie)
        self.toolButton_DeletePathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_DeletePathologie.setIcon(icon3)
        self.toolButton_DeletePathologie.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_DeletePathologie.setObjectName("toolButton_DeletePathologie")
        self.horizontalLayout_6.addWidget(self.toolButton_DeletePathologie)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboBox_PathologieSelection = MyComboBox(self.layoutWidget)
        self.comboBox_PathologieSelection.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieSelection.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieSelection.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieSelection.setObjectName("comboBox_PathologieSelection")
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieSelection)
        self.toolButton_AddSelection = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_AddSelection.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_AddSelection.setMaximumSize(QtCore.QSize(27, 27))
        self.toolButton_AddSelection.setIcon(icon2)
        self.toolButton_AddSelection.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddSelection.setObjectName("toolButton_AddSelection")
        self.horizontalLayout_7.addWidget(self.toolButton_AddSelection)
        self.toolButton_deleteSelection = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_deleteSelection.setMaximumSize(QtCore.QSize(27, 27))
        self.toolButton_deleteSelection.setIcon(icon3)
        self.toolButton_deleteSelection.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_deleteSelection.setObjectName("toolButton_deleteSelection")
        self.horizontalLayout_7.addWidget(self.toolButton_deleteSelection)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.pushButton_SavePathologie = QtGui.QPushButton(DialogPathologie)
        self.pushButton_SavePathologie.setGeometry(QtCore.QRect(610, 30, 151, 27))
        self.pushButton_SavePathologie.setObjectName("pushButton_SavePathologie")
        self.line = QtGui.QFrame(DialogPathologie)
        self.line.setGeometry(QtCore.QRect(11, 131, 765, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtGui.QWidget(DialogPathologie)
        self.widget.setGeometry(QtCore.QRect(15, 145, 762, 431))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_NomReference = QtGui.QLineEdit(self.widget)
        self.lineEdit_NomReference.setMinimumSize(QtCore.QSize(350, 30))
        self.lineEdit_NomReference.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lineEdit_NomReference.setFont(font)
        self.lineEdit_NomReference.setObjectName("lineEdit_NomReference")
        self.horizontalLayout.addWidget(self.lineEdit_NomReference)
        self.checkBox_Chronic = QtGui.QCheckBox(self.widget)
        self.checkBox_Chronic.setMinimumSize(QtCore.QSize(150, 27))
        self.checkBox_Chronic.setObjectName("checkBox_Chronic")
        self.horizontalLayout.addWidget(self.checkBox_Chronic)
        self.toolButton_documentPathologie = QtGui.QToolButton(self.widget)
        self.toolButton_documentPathologie.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_documentPathologie.setMaximumSize(QtCore.QSize(30, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_documentPathologie.setIcon(icon4)
        self.toolButton_documentPathologie.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_documentPathologie.setObjectName("toolButton_documentPathologie")
        self.horizontalLayout.addWidget(self.toolButton_documentPathologie)
        self.toolButton_traitements = QtGui.QToolButton(self.widget)
        self.toolButton_traitements.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_traitements.setMaximumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/gelule.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_traitements.setIcon(icon5)
        self.toolButton_traitements.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_traitements.setObjectName("toolButton_traitements")
        self.horizontalLayout.addWidget(self.toolButton_traitements)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.plainTextEdit_Descriptif = QtGui.QPlainTextEdit(self.widget)
        self.plainTextEdit_Descriptif.setMinimumSize(QtCore.QSize(280, 0))
        self.plainTextEdit_Descriptif.setObjectName("plainTextEdit_Descriptif")
        self.verticalLayout.addWidget(self.plainTextEdit_Descriptif)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.listWidget_Domaines = QtGui.QListWidget(self.widget)
        self.listWidget_Domaines.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_Domaines.setMaximumSize(QtCore.QSize(220, 150))
        self.listWidget_Domaines.setObjectName("listWidget_Domaines")
        self.verticalLayout_3.addWidget(self.listWidget_Domaines)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.listWidget_Synonymes = QtGui.QListWidget(self.widget)
        self.listWidget_Synonymes.setMaximumSize(QtCore.QSize(240, 16777215))
        self.listWidget_Synonymes.setObjectName("listWidget_Synonymes")
        self.verticalLayout_4.addWidget(self.listWidget_Synonymes)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_Examen = MyComboBox(self.widget)
        self.comboBox_Examen.setMinimumSize(QtCore.QSize(230, 27))
        self.comboBox_Examen.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Examen.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Examen.setEditable(True)
        self.comboBox_Examen.setObjectName("comboBox_Examen")
        self.horizontalLayout_2.addWidget(self.comboBox_Examen)
        spacerItem = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBox_Critere = MyComboBox(self.widget)
        self.comboBox_Critere.setMinimumSize(QtCore.QSize(320, 27))
        self.comboBox_Critere.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Critere.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Critere.setEditable(True)
        self.comboBox_Critere.setObjectName("comboBox_Critere")
        self.horizontalLayout_2.addWidget(self.comboBox_Critere)
        self.toolButton_AddCritere = QtGui.QToolButton(self.widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddCritere.setIcon(icon6)
        self.toolButton_AddCritere.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddCritere.setObjectName("toolButton_AddCritere")
        self.horizontalLayout_2.addWidget(self.toolButton_AddCritere)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_Criteres = MyTableWidget(self.widget)
        self.tableWidget_Criteres.setRowCount(10)
        self.tableWidget_Criteres.setColumnCount(6)
        self.tableWidget_Criteres.setObjectName("tableWidget_Criteres")
        self.tableWidget_Criteres.setColumnCount(6)
        self.tableWidget_Criteres.setRowCount(10)
        self.tableWidget_Criteres.horizontalHeader().setVisible(True)
        self.tableWidget_Criteres.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.tableWidget_Criteres)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtGui.QSpacerItem(448, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButton_Cancel = QtGui.QPushButton(self.widget)
        self.pushButton_Cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_8.addWidget(self.pushButton_Cancel)
        self.pushButton_Save = QtGui.QPushButton(self.widget)
        self.pushButton_Save.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_8.addWidget(self.pushButton_Save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.label.setBuddy(self.comboBox_PathologieDomaine)
        self.label_2.setBuddy(self.comboBox_PathologiePathologie)
        self.label_3.setBuddy(self.comboBox_PathologieSelection)
        self.label_5.setBuddy(self.plainTextEdit_Descriptif)
        self.label_9.setBuddy(self.listWidget_Synonymes)
        self.label_8.setBuddy(self.listWidget_Synonymes)
        self.label_6.setBuddy(self.comboBox_Examen)
        self.label_7.setBuddy(self.comboBox_Critere)

        self.retranslateUi(DialogPathologie)
        QtCore.QMetaObject.connectSlotsByName(DialogPathologie)

    def retranslateUi(self, DialogPathologie):
        DialogPathologie.setWindowTitle(QtGui.QApplication.translate("DialogPathologie", "Formulaire de Pathologie", None, QtGui.QApplication.UnicodeUTF8))
        DialogPathologie.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Documents relatifs cette pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PlanTherapeutique.setText(QtGui.QApplication.translate("DialogPathologie", "Plan Thérapeutique", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogPathologie", "Domaine :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DomaineSelection.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Ajouter un domaine pour la pathologie en cours", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DomaineSelection.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddSelection_2.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Créer un nouveau domaine", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddSelection_2.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DeleteDommaine.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Supprimer ce domaine", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DeleteDommaine.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogPathologie", "Pathologie :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PathologiePathologie.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Pour ajouter une nouvelle pathologie, tapez sont nom ici.", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddPathologie.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Créer une pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddPathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DeletePathologie.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Supprimer cette pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DeletePathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogPathologie", "Sélection :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddSelection.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Ajouter la pathologie en cours dans la selection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddSelection.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteSelection.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Supprimer cette pathologie de la selection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteSelection.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SavePathologie.setText(QtGui.QApplication.translate("DialogPathologie", "Enregistrer Pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_NomReference.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Modifier le nom de référence ici et Entrée pour valider", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Chronic.setText(QtGui.QApplication.translate("DialogPathologie", "Maladie chronique", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_documentPathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_traitements.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Traitements proposés", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_traitements.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogPathologie", "Descriptif :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DialogPathologie", "Domaines :", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_Domaines.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Double Click oiur supprimer un domaine de la liste", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogPathologie", "Synonymes :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogPathologie", "Examen :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogPathologie", "Critère :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddCritere.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Editer les critères diagnostiques", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddCritere.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Cancel.setText(QtGui.QApplication.translate("DialogPathologie", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Save.setText(QtGui.QApplication.translate("DialogPathologie", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))

from Mywidgets import MyTableWidget, MyComboBox
import resources_rc
