# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_openvet.ui'
#
# Created: Fri Jan 31 17:33:10 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1284, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../images/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidgetClient = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetClient.setGeometry(QtCore.QRect(0, 10, 1291, 751))
        self.tabWidgetClient.setAutoFillBackground(False)
        self.tabWidgetClient.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidgetClient.setTabsClosable(True)
        self.tabWidgetClient.setMovable(True)
        self.tabWidgetClient.setObjectName(_fromUtf8("tabWidgetClient"))
        self.tabWidgetOuvrir = QtGui.QWidget()
        self.tabWidgetOuvrir.setObjectName(_fromUtf8("tabWidgetOuvrir"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/add1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetClient.addTab(self.tabWidgetOuvrir, icon1, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1284, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDossiers_M_dicaux = QtGui.QMenu(self.menubar)
        self.menuDossiers_M_dicaux.setObjectName(_fromUtf8("menuDossiers_M_dicaux"))
        self.menuComptabilit = QtGui.QMenu(self.menubar)
        self.menuComptabilit.setObjectName(_fromUtf8("menuComptabilit"))
        self.menuD_clarations = QtGui.QMenu(self.menuComptabilit)
        self.menuD_clarations.setObjectName(_fromUtf8("menuD_clarations"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuBase_de_donn_es = QtGui.QMenu(self.menuConfiguration)
        self.menuBase_de_donn_es.setObjectName(_fromUtf8("menuBase_de_donn_es"))
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName(_fromUtf8("menuQuitter"))
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName(_fromUtf8("menuStock"))
        self.menuStatistiques = QtGui.QMenu(self.menubar)
        self.menuStatistiques.setObjectName(_fromUtf8("menuStatistiques"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Recettes = QtGui.QAction(MainWindow)
        self.action_Recettes.setObjectName(_fromUtf8("action_Recettes"))
        self.actionD_penses = QtGui.QAction(MainWindow)
        self.actionD_penses.setObjectName(_fromUtf8("actionD_penses"))
        self.action_Banque = QtGui.QAction(MainWindow)
        self.action_Banque.setObjectName(_fromUtf8("action_Banque"))
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindow)
        self.actionRecoupement_bancaire.setObjectName(_fromUtf8("actionRecoupement_bancaire"))
        self.actionTVA = QtGui.QAction(MainWindow)
        self.actionTVA.setObjectName(_fromUtf8("actionTVA"))
        self.action2035 = QtGui.QAction(MainWindow)
        self.action2035.setObjectName(_fromUtf8("action2035"))
        self.actionCommandes = QtGui.QAction(MainWindow)
        self.actionCommandes.setObjectName(_fromUtf8("actionCommandes"))
        self.actionAnalyse = QtGui.QAction(MainWindow)
        self.actionAnalyse.setObjectName(_fromUtf8("actionAnalyse"))
        self.action_Facturation = QtGui.QAction(MainWindow)
        self.action_Facturation.setObjectName(_fromUtf8("action_Facturation"))
        self.actionBureau = QtGui.QAction(MainWindow)
        self.actionBureau.setObjectName(_fromUtf8("actionBureau"))
        self.action_M_dicaments = QtGui.QAction(MainWindow)
        self.action_M_dicaments.setObjectName(_fromUtf8("action_M_dicaments"))
        self.action_Pathologies = QtGui.QAction(MainWindow)
        self.action_Pathologies.setObjectName(_fromUtf8("action_Pathologies"))
        self.actionBackup = QtGui.QAction(MainWindow)
        self.actionBackup.setObjectName(_fromUtf8("actionBackup"))
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName(_fromUtf8("actionRestore"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionR_seau_S_curit = QtGui.QAction(MainWindow)
        self.actionR_seau_S_curit.setObjectName(_fromUtf8("actionR_seau_S_curit"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.menuD_clarations.addAction(self.actionTVA)
        self.menuD_clarations.addAction(self.action2035)
        self.menuComptabilit.addAction(self.action_Recettes)
        self.menuComptabilit.addAction(self.actionD_penses)
        self.menuComptabilit.addAction(self.action_Banque)
        self.menuComptabilit.addAction(self.actionRecoupement_bancaire)
        self.menuComptabilit.addAction(self.menuD_clarations.menuAction())
        self.menuBase_de_donn_es.addAction(self.actionBackup)
        self.menuBase_de_donn_es.addAction(self.actionRestore)
        self.menuBase_de_donn_es.addAction(self.actionImport)
        self.menuConfiguration.addAction(self.actionBureau)
        self.menuConfiguration.addAction(self.action_Facturation)
        self.menuConfiguration.addAction(self.action_M_dicaments)
        self.menuConfiguration.addAction(self.action_Pathologies)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuBase_de_donn_es.menuAction())
        self.menuConfiguration.addAction(self.actionR_seau_S_curit)
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuStock.addAction(self.actionCommandes)
        self.menuStock.addAction(self.actionAnalyse)
        self.menubar.addAction(self.menuDossiers_M_dicaux.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuComptabilit.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuQuitter.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetClient.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Open Vet", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDossiers_M_dicaux.setTitle(QtGui.QApplication.translate("MainWindow", "Dossiers Médicaux", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComptabilit.setTitle(QtGui.QApplication.translate("MainWindow", "Comptabilité", None, QtGui.QApplication.UnicodeUTF8))
        self.menuD_clarations.setTitle(QtGui.QApplication.translate("MainWindow", "Déclarations", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase_de_donn_es.setTitle(QtGui.QApplication.translate("MainWindow", "Base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuitter.setTitle(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStock.setTitle(QtGui.QApplication.translate("MainWindow", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStatistiques.setTitle(QtGui.QApplication.translate("MainWindow", "Statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Recettes.setText(QtGui.QApplication.translate("MainWindow", "&Recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_penses.setText(QtGui.QApplication.translate("MainWindow", "&Dépenses", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Banque.setText(QtGui.QApplication.translate("MainWindow", "&Banque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoupement_bancaire.setText(QtGui.QApplication.translate("MainWindow", "Recoupement bancaire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTVA.setText(QtGui.QApplication.translate("MainWindow", "TVA", None, QtGui.QApplication.UnicodeUTF8))
        self.action2035.setText(QtGui.QApplication.translate("MainWindow", "2035", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommandes.setText(QtGui.QApplication.translate("MainWindow", "&Commandes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalyse.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Facturation.setText(QtGui.QApplication.translate("MainWindow", "&Facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setText(QtGui.QApplication.translate("MainWindow", "Bureau", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_M_dicaments.setText(QtGui.QApplication.translate("MainWindow", "&Médicaments", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Pathologies.setText(QtGui.QApplication.translate("MainWindow", "&Pathologies", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionR_seau_S_curit.setText(QtGui.QApplication.translate("MainWindow", "Réseau/Sécurité", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setToolTip(QtGui.QApplication.translate("MainWindow", "Quitter l\'application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
