# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_animal.ui'
#
# Created: Sun Jan  5 22:16:05 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog_animal(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog_animal")
        Dialog.resize(420, 307)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 371, 227))
        self.widget.setObjectName("widget")
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(141, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit_NomAnimal = QtGui.QLineEdit(self.widget)
        self.lineEdit_NomAnimal.setObjectName("lineEdit_NomAnimal")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_NomAnimal)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(141, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_especes = QtGui.QComboBox(self.widget)
        self.comboBox_especes.setObjectName("comboBox_especes")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_especes)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(141, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox_race = QtGui.QComboBox(self.widget)
        self.comboBox_race.setObjectName("comboBox_race")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_race)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(141, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_male = QtGui.QRadioButton(self.widget)
        self.radioButton_male.setObjectName("radioButton_male")
        self.horizontalLayout.addWidget(self.radioButton_male)
        self.radioButton_femelle = QtGui.QRadioButton(self.widget)
        self.radioButton_femelle.setObjectName("radioButton_femelle")
        self.horizontalLayout.addWidget(self.radioButton_femelle)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(141, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.dateEdit_naissance = QtGui.QDateEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_naissance.sizePolicy().hasHeightForWidth())
        self.dateEdit_naissance.setSizePolicy(sizePolicy)
        self.dateEdit_naissance.setMinimumSize(QtCore.QSize(111, 0))
        self.dateEdit_naissance.setMaximumSize(QtCore.QSize(111, 16777215))
        self.dateEdit_naissance.setCalendarPopup(True)
        self.dateEdit_naissance.setObjectName("dateEdit_naissance")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dateEdit_naissance)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(141, 0))
        self.label_6.setMaximumSize(QtCore.QSize(141, 16777215))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.checkBox_sterilisation = QtGui.QCheckBox(self.widget)
        self.checkBox_sterilisation.setTristate(False)
        self.checkBox_sterilisation.setObjectName("checkBox_sterilisation")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.checkBox_sterilisation)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Nom :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Espece :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Race :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Sexe :", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_male.setText(QtGui.QApplication.translate("Dialog", "Mâle", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_femelle.setText(QtGui.QApplication.translate("Dialog", "Femelle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Date de naissance :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_naissance.setDisplayFormat(QtGui.QApplication.translate("Dialog", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Identification :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sterilisation.setText(QtGui.QApplication.translate("Dialog", "Stérilisation", None, QtGui.QApplication.UnicodeUTF8))

