# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_consultation_old.ui'
#
# Created: Sat Mar 29 11:26:29 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.stackedWidget.setStyleSheet("background-color: rgba(188, 255, 231, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Consultation = QtGui.QWidget()
        self.page_Consultation.setObjectName("page_Consultation")
        self.tabWidget_fiches = QtGui.QTabWidget(self.page_Consultation)
        self.tabWidget_fiches.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.tabWidget_fiches.setAutoFillBackground(False)
        self.tabWidget_fiches.setStyleSheet("None")
        self.tabWidget_fiches.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_fiches.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_fiches.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_fiches.setTabsClosable(True)
        self.tabWidget_fiches.setObjectName("tabWidget_fiches")
        self.tab_fiche1 = QtGui.QWidget()
        self.tab_fiche1.setObjectName("tab_fiche1")
        self.frame_client = QtGui.QFrame(self.tab_fiche1)
        self.frame_client.setGeometry(QtCore.QRect(0, 0, 474, 120))
        self.frame_client.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_client.setFrameShape(QtGui.QFrame.Box)
        self.frame_client.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_client.setLineWidth(1)
        self.frame_client.setObjectName("frame_client")
        self.comboBox_client = QtGui.QComboBox(self.frame_client)
        self.comboBox_client.setGeometry(QtCore.QRect(10, 10, 371, 27))
        self.comboBox_client.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_client.setEditable(True)
        self.comboBox_client.setObjectName("comboBox_client")
        self.textBrowser_client = QtGui.QTextBrowser(self.frame_client)
        self.textBrowser_client.setGeometry(QtCore.QRect(10, 50, 451, 61))
        self.textBrowser_client.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_client.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_client.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_client.setLineWidth(1)
        self.textBrowser_client.setMidLineWidth(0)
        self.textBrowser_client.setObjectName("textBrowser_client")
        self.toolButton_ClientInfo = QtGui.QToolButton(self.frame_client)
        self.toolButton_ClientInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClientInfo.setIcon(icon1)
        self.toolButton_ClientInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_ClientInfo.setObjectName("toolButton_ClientInfo")
        self.frame_animal = QtGui.QFrame(self.tab_fiche1)
        self.frame_animal.setGeometry(QtCore.QRect(536, 0, 482, 120))
        self.frame_animal.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_animal.setFrameShape(QtGui.QFrame.Box)
        self.frame_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_animal.setObjectName("frame_animal")
        self.comboBox_Animal = QtGui.QComboBox(self.frame_animal)
        self.comboBox_Animal.setGeometry(QtCore.QRect(10, 10, 261, 27))
        self.comboBox_Animal.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Animal.setEditable(True)
        self.comboBox_Animal.setObjectName("comboBox_Animal")
        self.textBrowser_animal = QtGui.QTextBrowser(self.frame_animal)
        self.textBrowser_animal.setGeometry(QtCore.QRect(10, 50, 454, 61))
        self.textBrowser_animal.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_animal.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_animal.setObjectName("textBrowser_animal")
        self.toolButton_AnimalInfo = QtGui.QToolButton(self.frame_animal)
        self.toolButton_AnimalInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        self.toolButton_AnimalInfo.setIcon(icon1)
        self.toolButton_AnimalInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_AnimalInfo.setObjectName("toolButton_AnimalInfo")
        self.toolButton_addAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addAnimal.setGeometry(QtCore.QRect(510, 0, 26, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addAnimal.setIcon(icon2)
        self.toolButton_addAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addAnimal.setObjectName("toolButton_addAnimal")
        self.toolButton_editAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editAnimal.setGeometry(QtCore.QRect(510, 32, 26, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editAnimal.setIcon(icon3)
        self.toolButton_editAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editAnimal.setObjectName("toolButton_editAnimal")
        self.toolButton_deleteAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteAnimal.setGeometry(QtCore.QRect(510, 64, 26, 26))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/delete2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deleteAnimal.setIcon(icon4)
        self.toolButton_deleteAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteAnimal.setObjectName("toolButton_deleteAnimal")
        self.toolButton_scan = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_scan.setGeometry(QtCore.QRect(493, 95, 26, 26))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/loupe2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scan.setIcon(icon5)
        self.toolButton_scan.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan.setObjectName("toolButton_scan")
        self.tabWidget_medical = QtGui.QTabWidget(self.tab_fiche1)
        self.tabWidget_medical.setGeometry(QtCore.QRect(0, 120, 1024, 521))
        self.tabWidget_medical.setObjectName("tabWidget_medical")
        self.tab_consulation = QtGui.QWidget()
        self.tab_consulation.setObjectName("tab_consulation")
        self.splitter = QtGui.QSplitter(self.tab_consulation)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1018, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_med_sup = QtGui.QFrame(self.splitter)
        self.frame_med_sup.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_med_sup.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_sup.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_sup.setObjectName("frame_med_sup")
        self.tableWidget_vacciner = QtGui.QTableWidget(self.frame_med_sup)
        self.tableWidget_vacciner.setGeometry(QtCore.QRect(690, 10, 311, 121))
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setObjectName("tableWidget_vacciner")
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.verticalHeader().setVisible(False)
        self.button_vacciner = QtGui.QPushButton(self.frame_med_sup)
        self.button_vacciner.setGeometry(QtCore.QRect(910, 230, 93, 27))
        self.button_vacciner.setObjectName("button_vacciner")
        self.dateEdit_vacciner_start = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_start.setGeometry(QtCore.QRect(750, 140, 101, 27))
        self.dateEdit_vacciner_start.setCalendarPopup(True)
        self.dateEdit_vacciner_start.setObjectName("dateEdit_vacciner_start")
        self.dateEdit_vacciner_end = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_end.setGeometry(QtCore.QRect(900, 180, 101, 27))
        self.dateEdit_vacciner_end.setCalendarPopup(True)
        self.dateEdit_vacciner_end.setObjectName("dateEdit_vacciner_end")
        self.comboBox_vacciner = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_vacciner.setGeometry(QtCore.QRect(900, 140, 101, 27))
        self.comboBox_vacciner.setObjectName("comboBox_vacciner")
        self.comboBox_rappel = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_rappel.setGeometry(QtCore.QRect(750, 180, 141, 27))
        self.comboBox_rappel.setObjectName("comboBox_rappel")
        self.label_2 = QtGui.QLabel(self.frame_med_sup)
        self.label_2.setGeometry(QtCore.QRect(690, 190, 62, 17))
        self.label_2.setObjectName("label_2")
        self.label_vaccinerStart = QtGui.QLabel(self.frame_med_sup)
        self.label_vaccinerStart.setGeometry(QtCore.QRect(690, 150, 31, 17))
        self.label_vaccinerStart.setObjectName("label_vaccinerStart")
        self.textBrowser_consultations = QtGui.QTextBrowser(self.frame_med_sup)
        self.textBrowser_consultations.setGeometry(QtCore.QRect(10, 10, 671, 401))
        self.textBrowser_consultations.setStyleSheet("background-position: right; background-image:  url(:/newPrefix/images/openvet.png);background-repeat: no-repeat; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));")
        self.textBrowser_consultations.setObjectName("textBrowser_consultations")
        self.frame_med_inf = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_med_inf.sizePolicy().hasHeightForWidth())
        self.frame_med_inf.setSizePolicy(sizePolicy)
        self.frame_med_inf.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_med_inf.setStyleSheet("None")
        self.frame_med_inf.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_inf.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_inf.setObjectName("frame_med_inf")
        self.layoutWidget = QtGui.QWidget(self.frame_med_inf)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 985, 246))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(25, 27))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.dateEdit_consult = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_consult.sizePolicy().hasHeightForWidth())
        self.dateEdit_consult.setSizePolicy(sizePolicy)
        self.dateEdit_consult.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_consult.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dateEdit_consult.setCalendarPopup(True)
        self.dateEdit_consult.setObjectName("dateEdit_consult")
        self.horizontalLayout.addWidget(self.dateEdit_consult)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(82, 0))
        self.label.setMaximumSize(QtCore.QSize(82, 27))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_veterinaire = MyComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_veterinaire.sizePolicy().hasHeightForWidth())
        self.comboBox_veterinaire.setSizePolicy(sizePolicy)
        self.comboBox_veterinaire.setMinimumSize(QtCore.QSize(200, 27))
        self.comboBox_veterinaire.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_veterinaire.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_veterinaire.setEditable(True)
        self.comboBox_veterinaire.setFrame(True)
        self.comboBox_veterinaire.setObjectName("comboBox_veterinaire")
        self.horizontalLayout.addWidget(self.comboBox_veterinaire)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(50, 27))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.comboBox_consultType = MyComboBox(self.layoutWidget)
        self.comboBox_consultType.setMinimumSize(QtCore.QSize(160, 27))
        self.comboBox_consultType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_consultType.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_consultType.setObjectName("comboBox_consultType")
        self.horizontalLayout.addWidget(self.comboBox_consultType)
        self.label_Referant = QtGui.QLabel(self.layoutWidget)
        self.label_Referant.setMaximumSize(QtCore.QSize(63, 27))
        self.label_Referant.setObjectName("label_Referant")
        self.horizontalLayout.addWidget(self.label_Referant)
        self.comboBox_Referant = MyComboBox(self.layoutWidget)
        self.comboBox_Referant.setMinimumSize(QtCore.QSize(181, 27))
        self.comboBox_Referant.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Referant.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Referant.setEditable(True)
        self.comboBox_Referant.setObjectName("comboBox_Referant")
        self.horizontalLayout.addWidget(self.comboBox_Referant)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(160, 27))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(200, 27))
        self.comboBox_PathologieDomaine.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieDomaine.setObjectName("comboBox_PathologieDomaine")
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieDomaine)
        self.label_Pathologie = QtGui.QLabel(self.layoutWidget)
        self.label_Pathologie.setMinimumSize(QtCore.QSize(81, 0))
        self.label_Pathologie.setMaximumSize(QtCore.QSize(81, 27))
        self.label_Pathologie.setObjectName("label_Pathologie")
        self.horizontalLayout_7.addWidget(self.label_Pathologie)
        self.comboBox_Pathologie = MyComboBox(self.layoutWidget)
        self.comboBox_Pathologie.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox_Pathologie.setMaximumSize(QtCore.QSize(261, 27))
        self.comboBox_Pathologie.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Pathologie.setEditable(False)
        self.comboBox_Pathologie.setObjectName("comboBox_Pathologie")
        self.horizontalLayout_7.addWidget(self.comboBox_Pathologie)
        self.toolButton_Pathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_Pathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_Pathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/pathologie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Pathologie.setIcon(icon6)
        self.toolButton_Pathologie.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Pathologie.setObjectName("toolButton_Pathologie")
        self.horizontalLayout_7.addWidget(self.toolButton_Pathologie)
        self.toolButton_comment = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_comment.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setMaximumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setIcon(icon1)
        self.toolButton_comment.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_comment.setObjectName("toolButton_comment")
        self.horizontalLayout_7.addWidget(self.toolButton_comment)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.textEdit_consultObs = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultObs.sizePolicy().hasHeightForWidth())
        self.textEdit_consultObs.setSizePolicy(sizePolicy)
        self.textEdit_consultObs.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultObs.setMaximumSize(QtCore.QSize(16777215, 111))
        self.textEdit_consultObs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_consultObs.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_consultObs.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit_consultObs.setObjectName("textEdit_consultObs")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit_consultObs)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.textEdit_consultTrait = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultTrait.sizePolicy().hasHeightForWidth())
        self.textEdit_consultTrait.setSizePolicy(sizePolicy)
        self.textEdit_consultTrait.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultTrait.setMaximumSize(QtCore.QSize(16777215, 51))
        self.textEdit_consultTrait.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_consultTrait.setObjectName("textEdit_consultTrait")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEdit_consultTrait)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_valider = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_valider.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_valider.setObjectName("pushButton_valider")
        self.verticalLayout.addWidget(self.pushButton_valider)
        self.pushButton_Nouveau = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Nouveau.setObjectName("pushButton_Nouveau")
        self.verticalLayout.addWidget(self.pushButton_Nouveau)
        self.pushButton_Hospit = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Hospit.setObjectName("pushButton_Hospit")
        self.verticalLayout.addWidget(self.pushButton_Hospit)
        self.pushButton_Facturation = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Facturation.setObjectName("pushButton_Facturation")
        self.verticalLayout.addWidget(self.pushButton_Facturation)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget_medical.addTab(self.tab_consulation, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_medical.addTab(self.tab, "")
        self.tab_analyses = QtGui.QWidget()
        self.tab_analyses.setObjectName("tab_analyses")
        self.tableWidget_analyses = QtGui.QTableWidget(self.tab_analyses)
        self.tableWidget_analyses.setEnabled(True)
        self.tableWidget_analyses.setGeometry(QtCore.QRect(650, 70, 350, 241))
        self.tableWidget_analyses.setShowGrid(True)
        self.tableWidget_analyses.setRowCount(16)
        self.tableWidget_analyses.setColumnCount(4)
        self.tableWidget_analyses.setObjectName("tableWidget_analyses")
        self.tableWidget_analyses.setColumnCount(4)
        self.tableWidget_analyses.setRowCount(16)
        self.tableWidget_analyses.verticalHeader().setVisible(False)
        self.listWidget_analyse = QtGui.QListWidget(self.tab_analyses)
        self.listWidget_analyse.setGeometry(QtCore.QRect(650, 60, 351, 192))
        self.listWidget_analyse.setObjectName("listWidget_analyse")
        self.lineEdit_titreImage = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_titreImage.setGeometry(QtCore.QRect(650, 340, 311, 27))
        self.lineEdit_titreImage.setObjectName("lineEdit_titreImage")
        self.lineEdit_fichier = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_fichier.setGeometry(QtCore.QRect(650, 390, 311, 27))
        self.lineEdit_fichier.setObjectName("lineEdit_fichier")
        self.toolButton_fichier = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_fichier.setGeometry(QtCore.QRect(970, 390, 26, 25))
        self.toolButton_fichier.setObjectName("toolButton_fichier")
        self.pushButton_addImage = QtGui.QPushButton(self.tab_analyses)
        self.pushButton_addImage.setGeometry(QtCore.QRect(760, 430, 111, 27))
        self.pushButton_addImage.setObjectName("pushButton_addImage")
        self.line = QtGui.QFrame(self.tab_analyses)
        self.line.setGeometry(QtCore.QRect(620, 30, 20, 420))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.tab_analyses)
        self.line_2.setGeometry(QtCore.QRect(270, 30, 20, 420))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtGui.QLabel(self.tab_analyses)
        self.label_5.setGeometry(QtCore.QRect(660, 11, 113, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_typeanalyse = QtGui.QComboBox(self.tab_analyses)
        self.comboBox_typeanalyse.setGeometry(QtCore.QRect(780, 10, 181, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_typeanalyse.sizePolicy().hasHeightForWidth())
        self.comboBox_typeanalyse.setSizePolicy(sizePolicy)
        self.comboBox_typeanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_typeanalyse.setObjectName("comboBox_typeanalyse")
        self.label_3 = QtGui.QLabel(self.tab_analyses)
        self.label_3.setGeometry(QtCore.QRect(50, 12, 171, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.listView = QtGui.QListView(self.tab_analyses)
        self.listView.setGeometry(QtCore.QRect(18, 37, 239, 410))
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.layoutWidget1 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget1.setGeometry(QtCore.QRect(303, 12, 303, 438))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_analyse = QtGui.QDateTimeEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_analyse.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_analyse.setSizePolicy(sizePolicy)
        self.dateTimeEdit_analyse.setMinimumSize(QtCore.QSize(156, 27))
        self.dateTimeEdit_analyse.setCalendarPopup(True)
        self.dateTimeEdit_analyse.setObjectName("dateTimeEdit_analyse")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_analyse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_description = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_description.sizePolicy().hasHeightForWidth())
        self.lineEdit_description.setSizePolicy(sizePolicy)
        self.lineEdit_description.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.verticalLayout_2.addWidget(self.lineEdit_description)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.lineEdit_prelevement = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prelevement.sizePolicy().hasHeightForWidth())
        self.lineEdit_prelevement.setSizePolicy(sizePolicy)
        self.lineEdit_prelevement.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_prelevement.setObjectName("lineEdit_prelevement")
        self.verticalLayout_2.addWidget(self.lineEdit_prelevement)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.textEdit_syntheseanalyse = QtGui.QTextEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_syntheseanalyse.sizePolicy().hasHeightForWidth())
        self.textEdit_syntheseanalyse.setSizePolicy(sizePolicy)
        self.textEdit_syntheseanalyse.setMinimumSize(QtCore.QSize(301, 120))
        self.textEdit_syntheseanalyse.setMaximumSize(QtCore.QSize(16777215, 141))
        self.textEdit_syntheseanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_syntheseanalyse.setAutoFillBackground(False)
        self.textEdit_syntheseanalyse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_syntheseanalyse.setObjectName("textEdit_syntheseanalyse")
        self.verticalLayout_2.addWidget(self.textEdit_syntheseanalyse)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.textEdit_conclusions = QtGui.QTextEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_conclusions.sizePolicy().hasHeightForWidth())
        self.textEdit_conclusions.setSizePolicy(sizePolicy)
        self.textEdit_conclusions.setMinimumSize(QtCore.QSize(301, 0))
        self.textEdit_conclusions.setMaximumSize(QtCore.QSize(16777215, 61))
        self.textEdit_conclusions.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_conclusions.setObjectName("textEdit_conclusions")
        self.verticalLayout_2.addWidget(self.textEdit_conclusions)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_valide = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_valide.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_valide.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_valide.setObjectName("pushButton_valide")
        self.horizontalLayout_6.addWidget(self.pushButton_valide)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.toolButton_AddTypeAnalyse = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_AddTypeAnalyse.setGeometry(QtCore.QRect(970, 10, 26, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddTypeAnalyse.setIcon(icon7)
        self.toolButton_AddTypeAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddTypeAnalyse.setObjectName("toolButton_AddTypeAnalyse")
        self.tabWidget_medical.addTab(self.tab_analyses, "")
        self.tab_ordonnances = QtGui.QWidget()
        self.tab_ordonnances.setObjectName("tab_ordonnances")
        self.textBrowser_medicament = QtGui.QTextBrowser(self.tab_ordonnances)
        self.textBrowser_medicament.setGeometry(QtCore.QRect(540, 220, 451, 231))
        self.textBrowser_medicament.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_medicament.setObjectName("textBrowser_medicament")
        self.label_RCP = QtGui.QLabel(self.tab_ordonnances)
        self.label_RCP.setGeometry(QtCore.QRect(540, 200, 131, 17))
        self.label_RCP.setObjectName("label_RCP")
        self.line_3 = QtGui.QFrame(self.tab_ordonnances)
        self.line_3.setGeometry(QtCore.QRect(515, 20, 20, 501))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.toolButton = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton.setGeometry(QtCore.QRect(960, 190, 26, 25))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon8)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_2.setGeometry(QtCore.QRect(920, 190, 26, 25))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_abst.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon9)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName("toolButton_2")
        self.layoutWidget2 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget2.setGeometry(QtCore.QRect(543, 10, 451, 171))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_medicament = QtGui.QLabel(self.layoutWidget2)
        self.label_medicament.setObjectName("label_medicament")
        self.gridLayout.addWidget(self.label_medicament, 0, 0, 1, 1)
        self.label_molecule = QtGui.QLabel(self.layoutWidget2)
        self.label_molecule.setObjectName("label_molecule")
        self.gridLayout.addWidget(self.label_molecule, 0, 1, 1, 1)
        self.comboBox_medicament = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_medicament.sizePolicy().hasHeightForWidth())
        self.comboBox_medicament.setSizePolicy(sizePolicy)
        self.comboBox_medicament.setObjectName("comboBox_medicament")
        self.gridLayout.addWidget(self.comboBox_medicament, 1, 0, 1, 1)
        self.comboBox_molecule = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_molecule.sizePolicy().hasHeightForWidth())
        self.comboBox_molecule.setSizePolicy(sizePolicy)
        self.comboBox_molecule.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_molecule.setObjectName("comboBox_molecule")
        self.gridLayout.addWidget(self.comboBox_molecule, 1, 1, 1, 1)
        self.label_posomol = QtGui.QLabel(self.layoutWidget2)
        self.label_posomol.setObjectName("label_posomol")
        self.gridLayout.addWidget(self.label_posomol, 2, 0, 1, 1)
        self.label_presentation = QtGui.QLabel(self.layoutWidget2)
        self.label_presentation.setObjectName("label_presentation")
        self.gridLayout.addWidget(self.label_presentation, 2, 1, 1, 1)
        self.lineEdit_posomol = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomol.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomol.setSizePolicy(sizePolicy)
        self.lineEdit_posomol.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomol.setObjectName("lineEdit_posomol")
        self.gridLayout.addWidget(self.lineEdit_posomol, 3, 0, 1, 1)
        self.comboBox_presentation = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_presentation.setObjectName("comboBox_presentation")
        self.gridLayout.addWidget(self.comboBox_presentation, 3, 1, 1, 1)
        self.label_posomed = QtGui.QLabel(self.layoutWidget2)
        self.label_posomed.setObjectName("label_posomed")
        self.gridLayout.addWidget(self.label_posomed, 4, 0, 1, 1)
        self.label_especeCible = QtGui.QLabel(self.layoutWidget2)
        self.label_especeCible.setObjectName("label_especeCible")
        self.gridLayout.addWidget(self.label_especeCible, 4, 1, 1, 1)
        self.lineEdit_posomed = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomed.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomed.setSizePolicy(sizePolicy)
        self.lineEdit_posomed.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomed.setObjectName("lineEdit_posomed")
        self.gridLayout.addWidget(self.lineEdit_posomed, 5, 0, 1, 1)
        self.comboBox_especeCible = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_especeCible.setObjectName("comboBox_especeCible")
        self.gridLayout.addWidget(self.comboBox_especeCible, 5, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget3.setGeometry(QtCore.QRect(540, 490, 451, 29))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_validOrdonnance = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_validOrdonnance.setObjectName("pushButton_validOrdonnance")
        self.horizontalLayout_4.addWidget(self.pushButton_validOrdonnance)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_CalculPoso = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_CalculPoso.setObjectName("pushButton_CalculPoso")
        self.horizontalLayout_4.addWidget(self.pushButton_CalculPoso)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_DMV = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_DMV.setObjectName("pushButton_DMV")
        self.horizontalLayout_4.addWidget(self.pushButton_DMV)
        self.layoutWidget4 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 31, 512, 387))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.dateEdit_ordonance = QtGui.QDateEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ordonance.sizePolicy().hasHeightForWidth())
        self.dateEdit_ordonance.setSizePolicy(sizePolicy)
        self.dateEdit_ordonance.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_ordonance.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_ordonance.setCalendarPopup(True)
        self.dateEdit_ordonance.setObjectName("dateEdit_ordonance")
        self.horizontalLayout_3.addWidget(self.dateEdit_ordonance)
        spacerItem2 = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_11 = QtGui.QLabel(self.layoutWidget4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lineEdit_poids = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_poids.sizePolicy().hasHeightForWidth())
        self.lineEdit_poids.setSizePolicy(sizePolicy)
        self.lineEdit_poids.setMinimumSize(QtCore.QSize(66, 27))
        self.lineEdit_poids.setObjectName("lineEdit_poids")
        self.horizontalLayout_3.addWidget(self.lineEdit_poids)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(496, 391))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.pushButton_OrdonnanceValid = QtGui.QPushButton(self.tab_ordonnances)
        self.pushButton_OrdonnanceValid.setGeometry(QtCore.QRect(200, 430, 93, 27))
        self.pushButton_OrdonnanceValid.setObjectName("pushButton_OrdonnanceValid")
        self.tabWidget_medical.addTab(self.tab_ordonnances, "")
        self.tab_planTherapeutique = QtGui.QWidget()
        self.tab_planTherapeutique.setObjectName("tab_planTherapeutique")
        self.tabWidget_medical.addTab(self.tab_planTherapeutique, "")
        self.tab_documents = QtGui.QWidget()
        self.tab_documents.setObjectName("tab_documents")
        self.listView_doc = QtGui.QListView(self.tab_documents)
        self.listView_doc.setGeometry(QtCore.QRect(20, 90, 241, 341))
        self.listView_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView_doc.setObjectName("listView_doc")
        self.label_doc = QtGui.QLabel(self.tab_documents)
        self.label_doc.setGeometry(QtCore.QRect(10, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_doc.setFont(font)
        self.label_doc.setTextFormat(QtCore.Qt.PlainText)
        self.label_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doc.setObjectName("label_doc")
        self.layoutWidget5 = QtGui.QWidget(self.tab_documents)
        self.layoutWidget5.setGeometry(QtCore.QRect(320, 52, 631, 378))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_docDate = QtGui.QLabel(self.layoutWidget5)
        self.label_docDate.setObjectName("label_docDate")
        self.horizontalLayout_5.addWidget(self.label_docDate)
        self.dateEdit_docDate = QtGui.QDateEdit(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_docDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_docDate.setSizePolicy(sizePolicy)
        self.dateEdit_docDate.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_docDate.setCalendarPopup(True)
        self.dateEdit_docDate.setObjectName("dateEdit_docDate")
        self.horizontalLayout_5.addWidget(self.dateEdit_docDate)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_docFile = QtGui.QLabel(self.layoutWidget5)
        self.label_docFile.setObjectName("label_docFile")
        self.horizontalLayout_5.addWidget(self.label_docFile)
        self.lineEdit_docFile = QtGui.QLineEdit(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_docFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_docFile.setSizePolicy(sizePolicy)
        self.lineEdit_docFile.setMinimumSize(QtCore.QSize(212, 27))
        self.lineEdit_docFile.setObjectName("lineEdit_docFile")
        self.horizontalLayout_5.addWidget(self.lineEdit_docFile)
        self.toolButton_docFile = QtGui.QToolButton(self.layoutWidget5)
        self.toolButton_docFile.setObjectName("toolButton_docFile")
        self.horizontalLayout_5.addWidget(self.toolButton_docFile)
        self.pushButton_docAdd = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_docAdd.setObjectName("pushButton_docAdd")
        self.horizontalLayout_5.addWidget(self.pushButton_docAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.textBrowser_doc = QtGui.QTextBrowser(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_doc.sizePolicy().hasHeightForWidth())
        self.textBrowser_doc.setSizePolicy(sizePolicy)
        self.textBrowser_doc.setMinimumSize(QtCore.QSize(571, 341))
        self.textBrowser_doc.setMaximumSize(QtCore.QSize(16777215, 611))
        self.textBrowser_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_doc.setObjectName("textBrowser_doc")
        self.verticalLayout_3.addWidget(self.textBrowser_doc)
        self.tabWidget_medical.addTab(self.tab_documents, "")
        self.toolButton_addClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addClient.setGeometry(QtCore.QRect(474, 0, 26, 26))
        self.toolButton_addClient.setIcon(icon2)
        self.toolButton_addClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addClient.setObjectName("toolButton_addClient")
        self.toolButton_deleteClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteClient.setGeometry(QtCore.QRect(474, 64, 26, 26))
        self.toolButton_deleteClient.setIcon(icon4)
        self.toolButton_deleteClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteClient.setObjectName("toolButton_deleteClient")
        self.toolButton_editClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editClient.setGeometry(QtCore.QRect(474, 32, 26, 26))
        self.toolButton_editClient.setIcon(icon3)
        self.toolButton_editClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editClient.setObjectName("toolButton_editClient")
        self.tabWidget_fiches.addTab(self.tab_fiche1, "")
        self.tab_fiche2 = QtGui.QWidget()
        self.tab_fiche2.setObjectName("tab_fiche2")
        self.tabWidget_fiches.addTab(self.tab_fiche2, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_fiches.addTab(self.tab_7, "")
        self.stackedWidget.addWidget(self.page_Consultation)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menuDossiers_M_dicaux = QtGui.QMenu(self.menubar)
        self.menuDossiers_M_dicaux.setObjectName("menuDossiers_M_dicaux")
        self.menuComptabilit = QtGui.QMenu(self.menubar)
        self.menuComptabilit.setObjectName("menuComptabilit")
        self.menuD_clarations = QtGui.QMenu(self.menuComptabilit)
        self.menuD_clarations.setObjectName("menuD_clarations")
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuBase_de_donn_es = QtGui.QMenu(self.menuConfiguration)
        self.menuBase_de_donn_es.setObjectName("menuBase_de_donn_es")
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName("menuQuitter")
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName("menuStock")
        self.menuStatistiques = QtGui.QMenu(self.menubar)
        self.menuStatistiques.setObjectName("menuStatistiques")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Recettes = QtGui.QAction(MainWindow)
        self.action_Recettes.setObjectName("action_Recettes")
        self.actionD_penses = QtGui.QAction(MainWindow)
        self.actionD_penses.setObjectName("actionD_penses")
        self.action_Banque = QtGui.QAction(MainWindow)
        self.action_Banque.setObjectName("action_Banque")
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindow)
        self.actionRecoupement_bancaire.setObjectName("actionRecoupement_bancaire")
        self.actionTVA = QtGui.QAction(MainWindow)
        self.actionTVA.setObjectName("actionTVA")
        self.action2035 = QtGui.QAction(MainWindow)
        self.action2035.setObjectName("action2035")
        self.actionCommandes = QtGui.QAction(MainWindow)
        self.actionCommandes.setObjectName("actionCommandes")
        self.actionAnalyse = QtGui.QAction(MainWindow)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.action_Facturation = QtGui.QAction(MainWindow)
        self.action_Facturation.setObjectName("action_Facturation")
        self.actionBureau = QtGui.QAction(MainWindow)
        self.actionBureau.setObjectName("actionBureau")
        self.action_M_dicaments = QtGui.QAction(MainWindow)
        self.action_M_dicaments.setObjectName("action_M_dicaments")
        self.action_Pathologies = QtGui.QAction(MainWindow)
        self.action_Pathologies.setObjectName("action_Pathologies")
        self.actionBackup = QtGui.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionR_seau_S_curit = QtGui.QAction(MainWindow)
        self.actionR_seau_S_curit.setObjectName("actionR_seau_S_curit")
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuD_clarations.addAction(self.actionTVA)
        self.menuD_clarations.addAction(self.action2035)
        self.menuComptabilit.addAction(self.action_Recettes)
        self.menuComptabilit.addAction(self.actionD_penses)
        self.menuComptabilit.addAction(self.action_Banque)
        self.menuComptabilit.addAction(self.actionRecoupement_bancaire)
        self.menuComptabilit.addAction(self.menuD_clarations.menuAction())
        self.menuBase_de_donn_es.addAction(self.actionBackup)
        self.menuBase_de_donn_es.addAction(self.actionRestore)
        self.menuBase_de_donn_es.addAction(self.actionImport)
        self.menuConfiguration.addAction(self.actionBureau)
        self.menuConfiguration.addAction(self.action_Facturation)
        self.menuConfiguration.addAction(self.action_M_dicaments)
        self.menuConfiguration.addAction(self.action_Pathologies)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuBase_de_donn_es.menuAction())
        self.menuConfiguration.addAction(self.actionR_seau_S_curit)
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuStock.addAction(self.actionCommandes)
        self.menuStock.addAction(self.actionAnalyse)
        self.menubar.addAction(self.menuDossiers_M_dicaux.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuComptabilit.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuQuitter.menuAction())
        self.label_2.setBuddy(self.comboBox_rappel)
        self.label_vaccinerStart.setBuddy(self.dateEdit_vacciner_start)
        self.label_13.setBuddy(self.dateEdit_consult)
        self.label.setBuddy(self.comboBox_veterinaire)
        self.label_12.setBuddy(self.comboBox_consultType)
        self.label_Referant.setBuddy(self.comboBox_Referant)
        self.label_3.setBuddy(self.listView)
        self.label_4.setBuddy(self.dateTimeEdit_analyse)
        self.label_6.setBuddy(self.lineEdit_description)
        self.label_7.setBuddy(self.lineEdit_prelevement)
        self.label_8.setBuddy(self.textEdit_syntheseanalyse)
        self.label_9.setBuddy(self.textEdit_conclusions)
        self.label_RCP.setBuddy(self.textBrowser_medicament)
        self.label_medicament.setBuddy(self.comboBox_medicament)
        self.label_molecule.setBuddy(self.comboBox_molecule)
        self.label_posomol.setBuddy(self.lineEdit_posomol)
        self.label_presentation.setBuddy(self.comboBox_presentation)
        self.label_posomed.setBuddy(self.lineEdit_posomed)
        self.label_especeCible.setBuddy(self.comboBox_especeCible)
        self.label_10.setBuddy(self.dateEdit_ordonance)
        self.label_11.setBuddy(self.lineEdit_poids)
        self.label_doc.setBuddy(self.listView_doc)
        self.label_docFile.setBuddy(self.lineEdit_docFile)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_fiches.setCurrentIndex(0)
        self.tabWidget_medical.setCurrentIndex(2)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL("clicked()"), self.dateEdit_vacciner_start.show)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL("clicked()"), self.dateEdit_vacciner_end.show)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL("clicked()"), self.comboBox_vacciner.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Open Vet", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_client.setToolTip(QtGui.QApplication.translate("MainWindow", "Double click pour sélectionner l\'édition", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_ClientInfo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_animal.setToolTip(QtGui.QApplication.translate("MainWindow", "Double click pour sélectionner l\'édition", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AnimalInfo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Nouvel animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Efface animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan.setToolTip(QtGui.QApplication.translate("MainWindow", "Recherche client / animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.button_vacciner.setToolTip(QtGui.QApplication.translate("MainWindow", "Ajouter ce vaccin dans le dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.button_vacciner.setText(QtGui.QApplication.translate("MainWindow", "Vacciner", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_vacciner_start.setToolTip(QtGui.QApplication.translate("MainWindow", "Date de vaccination", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_vacciner_end.setToolTip(QtGui.QApplication.translate("MainWindow", "Date de rappel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_vacciner.setToolTip(QtGui.QApplication.translate("MainWindow", "Vaccin", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rappel.setToolTip(QtGui.QApplication.translate("MainWindow", "Période de rappel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Rappel :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vaccinerStart.setText(QtGui.QApplication.translate("MainWindow", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_med_inf.setToolTip(QtGui.QApplication.translate("MainWindow", "Ajouter un commentaire", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_consult.setToolTip(QtGui.QApplication.translate("MainWindow", "Date de consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_consult.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Vétérinaire :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_veterinaire.setToolTip(QtGui.QApplication.translate("MainWindow", "Vétérinaire consultant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "   Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consultType.setToolTip(QtGui.QApplication.translate("MainWindow", "Choir le type dominant de la consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Referant.setText(QtGui.QApplication.translate("MainWindow", "Référant :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Referant.setToolTip(QtGui.QApplication.translate("MainWindow", "Choisir un vétérinaire référant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Domaine Pathologique :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PathologieDomaine.setToolTip(QtGui.QApplication.translate("MainWindow", "Domaine pathologique dominant de la consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Pathologie.setText(QtGui.QApplication.translate("MainWindow", "Pathologie :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Pathologie.setToolTip(QtGui.QApplication.translate("MainWindow", "Choisir une Pathologie Dominante pour cette Consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Pathologie.setToolTip(QtGui.QApplication.translate("MainWindow", "Accès au formulaire de pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Pathologie.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_comment.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Observations :", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_consultObs.setToolTip(QtGui.QApplication.translate("MainWindow", "Insérer les observations cliniques", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Traitements :", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_consultTrait.setToolTip(QtGui.QApplication.translate("MainWindow", "Inserez les traitements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valider.setToolTip(QtGui.QApplication.translate("MainWindow", "Enregistrer cette consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valider.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Nouveau.setToolTip(QtGui.QApplication.translate("MainWindow", "Nouvelle Consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Nouveau.setText(QtGui.QApplication.translate("MainWindow", "Nouveau", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Hospit.setToolTip(QtGui.QApplication.translate("MainWindow", "Imprimer la fiche d\'hospitalisation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Hospit.setText(QtGui.QApplication.translate("MainWindow", "Hospitalisation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Facturation.setToolTip(QtGui.QApplication.translate("MainWindow", "Basculer en facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Facturation.setText(QtGui.QApplication.translate("MainWindow", "Facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_consulation), QtGui.QApplication.translate("MainWindow", "Consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_fichier.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addImage.setToolTip(QtGui.QApplication.translate("MainWindow", "Ajouter une nouvelle image à l\'examen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addImage.setText(QtGui.QApplication.translate("MainWindow", "Ajouter image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Type d\'analyse :  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Analyses précédentes", None, QtGui.QApplication.UnicodeUTF8))
        self.listView.setStatusTip(QtGui.QApplication.translate("MainWindow", "Double click pour éditer l\'analyse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Date Heure :  ", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit_analyse.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Description de l\'analyse:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Prélèvement :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Observations :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Conclusions :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valide.setToolTip(QtGui.QApplication.translate("MainWindow", "Ajouter l\'analyse au dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valide.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddTypeAnalyse.setToolTip(QtGui.QApplication.translate("MainWindow", "AJouter des types d\'analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddTypeAnalyse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_analyses), QtGui.QApplication.translate("MainWindow", "Analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_RCP.setText(QtGui.QApplication.translate("MainWindow", "Mentions légales :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Texte complet", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Résumé", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_medicament.setText(QtGui.QApplication.translate("MainWindow", "Médicament :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_molecule.setText(QtGui.QApplication.translate("MainWindow", "Molécule :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_posomol.setText(QtGui.QApplication.translate("MainWindow", "Posologie de principe actif :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_presentation.setText(QtGui.QApplication.translate("MainWindow", "Présentation :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_posomed.setText(QtGui.QApplication.translate("MainWindow", "Posologie de médicament :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_especeCible.setText(QtGui.QApplication.translate("MainWindow", "Espèce cible :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_validOrdonnance.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CalculPoso.setText(QtGui.QApplication.translate("MainWindow", "Calculatrice", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DMV.setText(QtGui.QApplication.translate("MainWindow", "Editer DMV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_ordonance.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Poids :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_OrdonnanceValid.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_ordonnances), QtGui.QApplication.translate("MainWindow", "Ordonnances", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_planTherapeutique), QtGui.QApplication.translate("MainWindow", "Plan Thérapeutique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_doc.setText(QtGui.QApplication.translate("MainWindow", "Documents disponibles :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_docDate.setText(QtGui.QApplication.translate("MainWindow", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_docDate.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_docFile.setText(QtGui.QApplication.translate("MainWindow", "Fichier :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_docFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Selectionner un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_docFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_docAdd.setToolTip(QtGui.QApplication.translate("MainWindow", "Ajouter nouveau document au dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_docAdd.setText(QtGui.QApplication.translate("MainWindow", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_documents), QtGui.QApplication.translate("MainWindow", "Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Nouveau client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_addClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Efface client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deleteClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche1), QtGui.QApplication.translate("MainWindow", "Client1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche2), QtGui.QApplication.translate("MainWindow", "Client2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDossiers_M_dicaux.setTitle(QtGui.QApplication.translate("MainWindow", "Dossiers Médicaux", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComptabilit.setTitle(QtGui.QApplication.translate("MainWindow", "Comptabilité", None, QtGui.QApplication.UnicodeUTF8))
        self.menuD_clarations.setTitle(QtGui.QApplication.translate("MainWindow", "Déclarations", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase_de_donn_es.setTitle(QtGui.QApplication.translate("MainWindow", "Base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuitter.setTitle(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStock.setTitle(QtGui.QApplication.translate("MainWindow", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStatistiques.setTitle(QtGui.QApplication.translate("MainWindow", "Statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Recettes.setText(QtGui.QApplication.translate("MainWindow", "&Recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_penses.setText(QtGui.QApplication.translate("MainWindow", "&Dépenses", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Banque.setText(QtGui.QApplication.translate("MainWindow", "&Banque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoupement_bancaire.setText(QtGui.QApplication.translate("MainWindow", "Recoupement bancaire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTVA.setText(QtGui.QApplication.translate("MainWindow", "TVA", None, QtGui.QApplication.UnicodeUTF8))
        self.action2035.setText(QtGui.QApplication.translate("MainWindow", "2035", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommandes.setText(QtGui.QApplication.translate("MainWindow", "&Commandes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalyse.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Facturation.setText(QtGui.QApplication.translate("MainWindow", "&Facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setText(QtGui.QApplication.translate("MainWindow", "Bureau", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_M_dicaments.setText(QtGui.QApplication.translate("MainWindow", "&Médicaments", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Pathologies.setText(QtGui.QApplication.translate("MainWindow", "&Pathologies", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionR_seau_S_curit.setText(QtGui.QApplication.translate("MainWindow", "Réseau/Sécurité", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setToolTip(QtGui.QApplication.translate("MainWindow", "Quitter l\'application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from Mywidgets import MyComboBox
import resources_rc
