# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_consultation.ui'
#
# Created: Tue May 13 11:27:54 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_tabWidget_medical(object):
    def setupUi(self, tabWidget_medical):
        tabWidget_medical.setObjectName("tabWidget_medical")
        tabWidget_medical.resize(1024, 521)
        self.tab_consulation = QtGui.QWidget()
        self.tab_consulation.setObjectName("tab_consulation")
        self.splitter = QtGui.QSplitter(self.tab_consulation)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1018, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_med_sup = QtGui.QFrame(self.splitter)
        self.frame_med_sup.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_med_sup.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_sup.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_sup.setObjectName("frame_med_sup")
        self.tableWidget_vacciner = QtGui.QTableWidget(self.frame_med_sup)
        self.tableWidget_vacciner.setGeometry(QtCore.QRect(690, 10, 311, 121))
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setObjectName("tableWidget_vacciner")
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.verticalHeader().setVisible(False)
        self.button_vacciner = QtGui.QPushButton(self.frame_med_sup)
        self.button_vacciner.setGeometry(QtCore.QRect(910, 230, 93, 27))
        self.button_vacciner.setObjectName("button_vacciner")
        self.dateEdit_vacciner_start = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_start.setGeometry(QtCore.QRect(750, 140, 101, 27))
        self.dateEdit_vacciner_start.setCalendarPopup(True)
        self.dateEdit_vacciner_start.setObjectName("dateEdit_vacciner_start")
        self.dateEdit_vacciner_end = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_end.setGeometry(QtCore.QRect(900, 180, 101, 27))
        self.dateEdit_vacciner_end.setCalendarPopup(True)
        self.dateEdit_vacciner_end.setObjectName("dateEdit_vacciner_end")
        self.comboBox_vacciner = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_vacciner.setGeometry(QtCore.QRect(900, 140, 101, 27))
        self.comboBox_vacciner.setObjectName("comboBox_vacciner")
        self.comboBox_rappel = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_rappel.setGeometry(QtCore.QRect(750, 180, 141, 27))
        self.comboBox_rappel.setObjectName("comboBox_rappel")
        self.label_2 = QtGui.QLabel(self.frame_med_sup)
        self.label_2.setGeometry(QtCore.QRect(690, 190, 62, 17))
        self.label_2.setObjectName("label_2")
        self.label_vaccinerStart = QtGui.QLabel(self.frame_med_sup)
        self.label_vaccinerStart.setGeometry(QtCore.QRect(690, 150, 31, 17))
        self.label_vaccinerStart.setObjectName("label_vaccinerStart")
        self.textBrowser_consultations = QtGui.QTextBrowser(self.frame_med_sup)
        self.textBrowser_consultations.setGeometry(QtCore.QRect(10, 10, 671, 401))
        self.textBrowser_consultations.setStyleSheet("background-position: right; background-image:  url(:/newPrefix/images/openvet.png);background-repeat: no-repeat; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));")
        self.textBrowser_consultations.setObjectName("textBrowser_consultations")
        self.frame_med_inf = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_med_inf.sizePolicy().hasHeightForWidth())
        self.frame_med_inf.setSizePolicy(sizePolicy)
        self.frame_med_inf.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_med_inf.setStyleSheet("None")
        self.frame_med_inf.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_inf.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_inf.setObjectName("frame_med_inf")
        self.layoutWidget = QtGui.QWidget(self.frame_med_inf)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 993, 246))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(25, 27))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.dateEdit_consult = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_consult.sizePolicy().hasHeightForWidth())
        self.dateEdit_consult.setSizePolicy(sizePolicy)
        self.dateEdit_consult.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_consult.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dateEdit_consult.setCalendarPopup(True)
        self.dateEdit_consult.setObjectName("dateEdit_consult")
        self.horizontalLayout.addWidget(self.dateEdit_consult)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(82, 0))
        self.label.setMaximumSize(QtCore.QSize(82, 27))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_veterinaire = MyComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_veterinaire.sizePolicy().hasHeightForWidth())
        self.comboBox_veterinaire.setSizePolicy(sizePolicy)
        self.comboBox_veterinaire.setMinimumSize(QtCore.QSize(200, 27))
        self.comboBox_veterinaire.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_veterinaire.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_veterinaire.setEditable(True)
        self.comboBox_veterinaire.setFrame(True)
        self.comboBox_veterinaire.setObjectName("comboBox_veterinaire")
        self.horizontalLayout.addWidget(self.comboBox_veterinaire)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(50, 27))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.comboBox_consultType = MyComboBox(self.layoutWidget)
        self.comboBox_consultType.setMinimumSize(QtCore.QSize(160, 27))
        self.comboBox_consultType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_consultType.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_consultType.setObjectName("comboBox_consultType")
        self.horizontalLayout.addWidget(self.comboBox_consultType)
        self.label_Referant = QtGui.QLabel(self.layoutWidget)
        self.label_Referant.setMaximumSize(QtCore.QSize(63, 27))
        self.label_Referant.setObjectName("label_Referant")
        self.horizontalLayout.addWidget(self.label_Referant)
        self.comboBox_Referant = MyComboBox(self.layoutWidget)
        self.comboBox_Referant.setMinimumSize(QtCore.QSize(181, 27))
        self.comboBox_Referant.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Referant.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Referant.setEditable(True)
        self.comboBox_Referant.setObjectName("comboBox_Referant")
        self.horizontalLayout.addWidget(self.comboBox_Referant)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(160, 27))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(200, 27))
        self.comboBox_PathologieDomaine.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieDomaine.setObjectName("comboBox_PathologieDomaine")
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieDomaine)
        self.label_Pathologie = QtGui.QLabel(self.layoutWidget)
        self.label_Pathologie.setMinimumSize(QtCore.QSize(81, 0))
        self.label_Pathologie.setMaximumSize(QtCore.QSize(81, 27))
        self.label_Pathologie.setObjectName("label_Pathologie")
        self.horizontalLayout_7.addWidget(self.label_Pathologie)
        self.comboBox_Pathologie = MyComboBox(self.layoutWidget)
        self.comboBox_Pathologie.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox_Pathologie.setMaximumSize(QtCore.QSize(261, 27))
        self.comboBox_Pathologie.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Pathologie.setEditable(False)
        self.comboBox_Pathologie.setObjectName("comboBox_Pathologie")
        self.horizontalLayout_7.addWidget(self.comboBox_Pathologie)
        self.toolButton_Pathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_Pathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_Pathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/pathologie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Pathologie.setIcon(icon)
        self.toolButton_Pathologie.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Pathologie.setObjectName("toolButton_Pathologie")
        self.horizontalLayout_7.addWidget(self.toolButton_Pathologie)
        self.toolButton_comment = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_comment.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setMaximumSize(QtCore.QSize(27, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_comment.setIcon(icon1)
        self.toolButton_comment.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_comment.setObjectName("toolButton_comment")
        self.horizontalLayout_7.addWidget(self.toolButton_comment)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.textEdit_consultObs = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultObs.sizePolicy().hasHeightForWidth())
        self.textEdit_consultObs.setSizePolicy(sizePolicy)
        self.textEdit_consultObs.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultObs.setMaximumSize(QtCore.QSize(16777215, 111))
        self.textEdit_consultObs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_consultObs.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_consultObs.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit_consultObs.setObjectName("textEdit_consultObs")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit_consultObs)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.textEdit_consultTrait = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultTrait.sizePolicy().hasHeightForWidth())
        self.textEdit_consultTrait.setSizePolicy(sizePolicy)
        self.textEdit_consultTrait.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultTrait.setMaximumSize(QtCore.QSize(16777215, 51))
        self.textEdit_consultTrait.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_consultTrait.setObjectName("textEdit_consultTrait")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEdit_consultTrait)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_valider = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_valider.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_valider.setObjectName("pushButton_valider")
        self.verticalLayout.addWidget(self.pushButton_valider)
        self.pushButton_Nouveau = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Nouveau.setObjectName("pushButton_Nouveau")
        self.verticalLayout.addWidget(self.pushButton_Nouveau)
        self.pushButton_Hospit = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Hospit.setObjectName("pushButton_Hospit")
        self.verticalLayout.addWidget(self.pushButton_Hospit)
        self.pushButton_Facturation = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Facturation.setObjectName("pushButton_Facturation")
        self.verticalLayout.addWidget(self.pushButton_Facturation)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        tabWidget_medical.addTab(self.tab_consulation, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        tabWidget_medical.addTab(self.tab, "")
        self.tab_analyses = QtGui.QWidget()
        self.tab_analyses.setObjectName("tab_analyses")
        self.line = QtGui.QFrame(self.tab_analyses)
        self.line.setGeometry(QtCore.QRect(610, 30, 20, 411))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.tab_analyses)
        self.line_2.setGeometry(QtCore.QRect(280, 30, 20, 411))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtGui.QLabel(self.tab_analyses)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 171, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.listView_Analyses = QtGui.QListView(self.tab_analyses)
        self.listView_Analyses.setGeometry(QtCore.QRect(8, 50, 271, 341))
        self.listView_Analyses.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView_Analyses.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView_Analyses.setObjectName("listView_Analyses")
        self.toolButton_AddAnalyse = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_AddAnalyse.setGeometry(QtCore.QRect(10, 400, 26, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddAnalyse.setIcon(icon2)
        self.toolButton_AddAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddAnalyse.setObjectName("toolButton_AddAnalyse")
        self.toolButton_DeleteAnalyse = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_DeleteAnalyse.setGeometry(QtCore.QRect(50, 400, 26, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/delete2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_DeleteAnalyse.setIcon(icon3)
        self.toolButton_DeleteAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_DeleteAnalyse.setObjectName("toolButton_DeleteAnalyse")
        self.pushButton_SaveAnalyse = QtGui.QPushButton(self.tab_analyses)
        self.pushButton_SaveAnalyse.setGeometry(QtCore.QRect(190, 400, 90, 27))
        self.pushButton_SaveAnalyse.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_SaveAnalyse.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_SaveAnalyse.setObjectName("pushButton_SaveAnalyse")
        self.layoutWidget1 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget1.setGeometry(QtCore.QRect(304, 13, 303, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_analyse = QtGui.QDateTimeEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_analyse.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_analyse.setSizePolicy(sizePolicy)
        self.dateTimeEdit_analyse.setMinimumSize(QtCore.QSize(170, 27))
        self.dateTimeEdit_analyse.setCalendarPopup(True)
        self.dateTimeEdit_analyse.setObjectName("dateTimeEdit_analyse")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_analyse)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_description = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_description.sizePolicy().hasHeightForWidth())
        self.lineEdit_description.setSizePolicy(sizePolicy)
        self.lineEdit_description.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_description.setMaxLength(80)
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.verticalLayout_2.addWidget(self.lineEdit_description)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.lineEdit_prelevement = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prelevement.sizePolicy().hasHeightForWidth())
        self.lineEdit_prelevement.setSizePolicy(sizePolicy)
        self.lineEdit_prelevement.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_prelevement.setMaxLength(80)
        self.lineEdit_prelevement.setObjectName("lineEdit_prelevement")
        self.verticalLayout_2.addWidget(self.lineEdit_prelevement)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.plainTextEdit_syntheseanalyse = MyPlainTextEdit(self.layoutWidget1)
        self.plainTextEdit_syntheseanalyse.setObjectName("plainTextEdit_syntheseanalyse")
        self.verticalLayout_2.addWidget(self.plainTextEdit_syntheseanalyse)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.plainTextEdit_conclusions = MyPlainTextEdit(self.layoutWidget1)
        self.plainTextEdit_conclusions.setMaximumSize(QtCore.QSize(16777215, 150))
        self.plainTextEdit_conclusions.setObjectName("plainTextEdit_conclusions")
        self.verticalLayout_2.addWidget(self.plainTextEdit_conclusions)
        self.tableView_Parametres = QtGui.QTableView(self.tab_analyses)
        self.tableView_Parametres.setGeometry(QtCore.QRect(630, 130, 381, 241))
        self.tableView_Parametres.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView_Parametres.setObjectName("tableView_Parametres")
        self.layoutWidget2 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget2.setGeometry(QtCore.QRect(650, 8, 351, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_TypeAnalyse = QtGui.QLabel(self.layoutWidget2)
        self.label_TypeAnalyse.setMinimumSize(QtCore.QSize(0, 27))
        self.label_TypeAnalyse.setMaximumSize(QtCore.QSize(110, 27))
        self.label_TypeAnalyse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_TypeAnalyse.setObjectName("label_TypeAnalyse")
        self.horizontalLayout_6.addWidget(self.label_TypeAnalyse)
        self.comboBox_typeanalyse = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_typeanalyse.sizePolicy().hasHeightForWidth())
        self.comboBox_typeanalyse.setSizePolicy(sizePolicy)
        self.comboBox_typeanalyse.setMinimumSize(QtCore.QSize(180, 27))
        self.comboBox_typeanalyse.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_typeanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_typeanalyse.setObjectName("comboBox_typeanalyse")
        self.horizontalLayout_6.addWidget(self.comboBox_typeanalyse)
        self.toolButton_EditTypeAnalyse = QtGui.QToolButton(self.layoutWidget2)
        self.toolButton_EditTypeAnalyse.setMinimumSize(QtCore.QSize(0, 28))
        self.toolButton_EditTypeAnalyse.setMaximumSize(QtCore.QSize(16777215, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_EditTypeAnalyse.setIcon(icon4)
        self.toolButton_EditTypeAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_EditTypeAnalyse.setObjectName("toolButton_EditTypeAnalyse")
        self.horizontalLayout_6.addWidget(self.toolButton_EditTypeAnalyse)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_model = QtGui.QLabel(self.layoutWidget2)
        self.label_model.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_model.setObjectName("label_model")
        self.horizontalLayout_10.addWidget(self.label_model)
        self.comboBox_model = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_model.setMinimumSize(QtCore.QSize(180, 27))
        self.comboBox_model.setMaximumSize(QtCore.QSize(9999, 27))
        self.comboBox_model.setObjectName("comboBox_model")
        self.horizontalLayout_10.addWidget(self.comboBox_model)
        self.toolButton_EditModelAnalyse = QtGui.QToolButton(self.layoutWidget2)
        self.toolButton_EditModelAnalyse.setMinimumSize(QtCore.QSize(0, 28))
        self.toolButton_EditModelAnalyse.setMaximumSize(QtCore.QSize(16777215, 28))
        self.toolButton_EditModelAnalyse.setIcon(icon4)
        self.toolButton_EditModelAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_EditModelAnalyse.setObjectName("toolButton_EditModelAnalyse")
        self.horizontalLayout_10.addWidget(self.toolButton_EditModelAnalyse)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_Parametre = QtGui.QLabel(self.layoutWidget2)
        self.label_Parametre.setMinimumSize(QtCore.QSize(0, 27))
        self.label_Parametre.setMaximumSize(QtCore.QSize(110, 27))
        self.label_Parametre.setObjectName("label_Parametre")
        self.horizontalLayout_9.addWidget(self.label_Parametre)
        self.comboBox_Parametre = MyComboBox(self.layoutWidget2)
        self.comboBox_Parametre.setMinimumSize(QtCore.QSize(180, 27))
        self.comboBox_Parametre.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Parametre.setObjectName("comboBox_Parametre")
        self.horizontalLayout_9.addWidget(self.comboBox_Parametre)
        self.toolButton_EditParametre = QtGui.QToolButton(self.layoutWidget2)
        self.toolButton_EditParametre.setMinimumSize(QtCore.QSize(0, 28))
        self.toolButton_EditParametre.setMaximumSize(QtCore.QSize(16777215, 28))
        self.toolButton_EditParametre.setIcon(icon4)
        self.toolButton_EditParametre.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_EditParametre.setObjectName("toolButton_EditParametre")
        self.horizontalLayout_9.addWidget(self.toolButton_EditParametre)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.lineEdit_AnalyseRemarque = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_AnalyseRemarque.setGeometry(QtCore.QRect(730, 380, 271, 27))
        self.lineEdit_AnalyseRemarque.setMaxLength(200)
        self.lineEdit_AnalyseRemarque.setObjectName("lineEdit_AnalyseRemarque")
        self.label_Analyse_Remarque = QtGui.QLabel(self.tab_analyses)
        self.label_Analyse_Remarque.setGeometry(QtCore.QRect(650, 385, 81, 17))
        self.label_Analyse_Remarque.setObjectName("label_Analyse_Remarque")
        self.listView_AnalyseImage = QtGui.QListView(self.tab_analyses)
        self.listView_AnalyseImage.setGeometry(QtCore.QRect(650, 130, 351, 231))
        self.listView_AnalyseImage.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listView_AnalyseImage.setObjectName("listView_AnalyseImage")
        self.layoutWidget3 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget3.setGeometry(QtCore.QRect(651, 421, 351, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_AnalyseImport = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_AnalyseImport.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_AnalyseImport.setObjectName("pushButton_AnalyseImport")
        self.horizontalLayout_11.addWidget(self.pushButton_AnalyseImport)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.label_VueAnalyse = QtGui.QLabel(self.layoutWidget3)
        self.label_VueAnalyse.setObjectName("label_VueAnalyse")
        self.horizontalLayout_11.addWidget(self.label_VueAnalyse)
        self.radioButton_Parametre = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_Parametre.setObjectName("radioButton_Parametre")
        self.horizontalLayout_11.addWidget(self.radioButton_Parametre)
        self.radioButton_Document = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButton_Document.setObjectName("radioButton_Document")
        self.horizontalLayout_11.addWidget(self.radioButton_Document)
        tabWidget_medical.addTab(self.tab_analyses, "")
        self.tab_ordonnances = QtGui.QWidget()
        self.tab_ordonnances.setObjectName("tab_ordonnances")
        self.textBrowser_medicament = QtGui.QTextBrowser(self.tab_ordonnances)
        self.textBrowser_medicament.setGeometry(QtCore.QRect(540, 220, 451, 231))
        self.textBrowser_medicament.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_medicament.setObjectName("textBrowser_medicament")
        self.label_RCP = QtGui.QLabel(self.tab_ordonnances)
        self.label_RCP.setGeometry(QtCore.QRect(540, 200, 131, 17))
        self.label_RCP.setObjectName("label_RCP")
        self.line_3 = QtGui.QFrame(self.tab_ordonnances)
        self.line_3.setGeometry(QtCore.QRect(515, 20, 20, 501))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.toolButton = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton.setGeometry(QtCore.QRect(960, 190, 26, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_2.setGeometry(QtCore.QRect(920, 190, 26, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_abst.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon6)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName("toolButton_2")
        self.layoutWidget_3 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_3.setGeometry(QtCore.QRect(543, 10, 451, 176))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_medicament = QtGui.QLabel(self.layoutWidget_3)
        self.label_medicament.setObjectName("label_medicament")
        self.gridLayout.addWidget(self.label_medicament, 0, 0, 1, 1)
        self.label_molecule = QtGui.QLabel(self.layoutWidget_3)
        self.label_molecule.setObjectName("label_molecule")
        self.gridLayout.addWidget(self.label_molecule, 0, 1, 1, 1)
        self.comboBox_medicament = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_medicament.sizePolicy().hasHeightForWidth())
        self.comboBox_medicament.setSizePolicy(sizePolicy)
        self.comboBox_medicament.setObjectName("comboBox_medicament")
        self.gridLayout.addWidget(self.comboBox_medicament, 1, 0, 1, 1)
        self.comboBox_molecule = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_molecule.sizePolicy().hasHeightForWidth())
        self.comboBox_molecule.setSizePolicy(sizePolicy)
        self.comboBox_molecule.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_molecule.setObjectName("comboBox_molecule")
        self.gridLayout.addWidget(self.comboBox_molecule, 1, 1, 1, 1)
        self.label_posomol = QtGui.QLabel(self.layoutWidget_3)
        self.label_posomol.setObjectName("label_posomol")
        self.gridLayout.addWidget(self.label_posomol, 2, 0, 1, 1)
        self.label_presentation = QtGui.QLabel(self.layoutWidget_3)
        self.label_presentation.setObjectName("label_presentation")
        self.gridLayout.addWidget(self.label_presentation, 2, 1, 1, 1)
        self.lineEdit_posomol = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomol.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomol.setSizePolicy(sizePolicy)
        self.lineEdit_posomol.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomol.setObjectName("lineEdit_posomol")
        self.gridLayout.addWidget(self.lineEdit_posomol, 3, 0, 1, 1)
        self.comboBox_presentation = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBox_presentation.setObjectName("comboBox_presentation")
        self.gridLayout.addWidget(self.comboBox_presentation, 3, 1, 1, 1)
        self.label_posomed = QtGui.QLabel(self.layoutWidget_3)
        self.label_posomed.setObjectName("label_posomed")
        self.gridLayout.addWidget(self.label_posomed, 4, 0, 1, 1)
        self.label_especeCible = QtGui.QLabel(self.layoutWidget_3)
        self.label_especeCible.setObjectName("label_especeCible")
        self.gridLayout.addWidget(self.label_especeCible, 4, 1, 1, 1)
        self.lineEdit_posomed = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomed.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomed.setSizePolicy(sizePolicy)
        self.lineEdit_posomed.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomed.setObjectName("lineEdit_posomed")
        self.gridLayout.addWidget(self.lineEdit_posomed, 5, 0, 1, 1)
        self.comboBox_especeCible = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBox_especeCible.setObjectName("comboBox_especeCible")
        self.gridLayout.addWidget(self.comboBox_especeCible, 5, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_4.setGeometry(QtCore.QRect(540, 490, 451, 29))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_validOrdonnance = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_validOrdonnance.setObjectName("pushButton_validOrdonnance")
        self.horizontalLayout_4.addWidget(self.pushButton_validOrdonnance)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_CalculPoso = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_CalculPoso.setObjectName("pushButton_CalculPoso")
        self.horizontalLayout_4.addWidget(self.pushButton_CalculPoso)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_DMV = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_DMV.setObjectName("pushButton_DMV")
        self.horizontalLayout_4.addWidget(self.pushButton_DMV)
        self.layoutWidget_5 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_5.setGeometry(QtCore.QRect(11, 31, 512, 387))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.layoutWidget_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.dateEdit_ordonance = QtGui.QDateEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ordonance.sizePolicy().hasHeightForWidth())
        self.dateEdit_ordonance.setSizePolicy(sizePolicy)
        self.dateEdit_ordonance.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_ordonance.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_ordonance.setCalendarPopup(True)
        self.dateEdit_ordonance.setObjectName("dateEdit_ordonance")
        self.horizontalLayout_3.addWidget(self.dateEdit_ordonance)
        spacerItem4 = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_11 = QtGui.QLabel(self.layoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lineEdit_poids = QtGui.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_poids.sizePolicy().hasHeightForWidth())
        self.lineEdit_poids.setSizePolicy(sizePolicy)
        self.lineEdit_poids.setMinimumSize(QtCore.QSize(66, 27))
        self.lineEdit_poids.setObjectName("lineEdit_poids")
        self.horizontalLayout_3.addWidget(self.lineEdit_poids)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(496, 391))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.pushButton_OrdonnanceValid = QtGui.QPushButton(self.tab_ordonnances)
        self.pushButton_OrdonnanceValid.setGeometry(QtCore.QRect(200, 430, 93, 27))
        self.pushButton_OrdonnanceValid.setObjectName("pushButton_OrdonnanceValid")
        tabWidget_medical.addTab(self.tab_ordonnances, "")
        self.tab_planTherapeutique = QtGui.QWidget()
        self.tab_planTherapeutique.setObjectName("tab_planTherapeutique")
        tabWidget_medical.addTab(self.tab_planTherapeutique, "")
        self.tab_documents = QtGui.QWidget()
        self.tab_documents.setObjectName("tab_documents")
        self.listView_doc = QtGui.QListView(self.tab_documents)
        self.listView_doc.setGeometry(QtCore.QRect(20, 90, 241, 341))
        self.listView_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView_doc.setObjectName("listView_doc")
        self.label_doc = QtGui.QLabel(self.tab_documents)
        self.label_doc.setGeometry(QtCore.QRect(10, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_doc.setFont(font)
        self.label_doc.setTextFormat(QtCore.Qt.PlainText)
        self.label_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doc.setObjectName("label_doc")
        self.layoutWidget_6 = QtGui.QWidget(self.tab_documents)
        self.layoutWidget_6.setGeometry(QtCore.QRect(320, 52, 631, 378))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_docDate = QtGui.QLabel(self.layoutWidget_6)
        self.label_docDate.setObjectName("label_docDate")
        self.horizontalLayout_5.addWidget(self.label_docDate)
        self.dateEdit_docDate = QtGui.QDateEdit(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_docDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_docDate.setSizePolicy(sizePolicy)
        self.dateEdit_docDate.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_docDate.setCalendarPopup(True)
        self.dateEdit_docDate.setObjectName("dateEdit_docDate")
        self.horizontalLayout_5.addWidget(self.dateEdit_docDate)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_docFile = QtGui.QLabel(self.layoutWidget_6)
        self.label_docFile.setObjectName("label_docFile")
        self.horizontalLayout_5.addWidget(self.label_docFile)
        self.lineEdit_docFile = QtGui.QLineEdit(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_docFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_docFile.setSizePolicy(sizePolicy)
        self.lineEdit_docFile.setMinimumSize(QtCore.QSize(212, 27))
        self.lineEdit_docFile.setObjectName("lineEdit_docFile")
        self.horizontalLayout_5.addWidget(self.lineEdit_docFile)
        self.toolButton_docFile = QtGui.QToolButton(self.layoutWidget_6)
        self.toolButton_docFile.setObjectName("toolButton_docFile")
        self.horizontalLayout_5.addWidget(self.toolButton_docFile)
        self.pushButton_docAdd = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButton_docAdd.setObjectName("pushButton_docAdd")
        self.horizontalLayout_5.addWidget(self.pushButton_docAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.textBrowser_doc = QtGui.QTextBrowser(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_doc.sizePolicy().hasHeightForWidth())
        self.textBrowser_doc.setSizePolicy(sizePolicy)
        self.textBrowser_doc.setMinimumSize(QtCore.QSize(571, 341))
        self.textBrowser_doc.setMaximumSize(QtCore.QSize(16777215, 611))
        self.textBrowser_doc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_doc.setObjectName("textBrowser_doc")
        self.verticalLayout_3.addWidget(self.textBrowser_doc)
        tabWidget_medical.addTab(self.tab_documents, "")
        self.DoDeleteDoc = QtGui.QAction(tabWidget_medical)
        self.DoDeleteDoc.setIcon(icon3)
        self.DoDeleteDoc.setObjectName("DoDeleteDoc")
        self.DoEditDocument = QtGui.QAction(tabWidget_medical)
        self.DoEditDocument.setIcon(icon4)
        self.DoEditDocument.setObjectName("DoEditDocument")
        self.DoDeleteParametre = QtGui.QAction(tabWidget_medical)
        self.DoDeleteParametre.setIcon(icon3)
        self.DoDeleteParametre.setObjectName("DoDeleteParametre")
        self.label_2.setBuddy(self.comboBox_rappel)
        self.label_vaccinerStart.setBuddy(self.dateEdit_vacciner_start)
        self.label_13.setBuddy(self.dateEdit_consult)
        self.label.setBuddy(self.comboBox_veterinaire)
        self.label_12.setBuddy(self.comboBox_consultType)
        self.label_Referant.setBuddy(self.comboBox_Referant)
        self.label_3.setBuddy(self.listView_Analyses)
        self.label_4.setBuddy(self.dateTimeEdit_analyse)
        self.label_6.setBuddy(self.lineEdit_description)
        self.label_7.setBuddy(self.lineEdit_prelevement)
        self.label_TypeAnalyse.setBuddy(self.comboBox_typeanalyse)
        self.label_model.setBuddy(self.comboBox_model)
        self.label_Parametre.setBuddy(self.comboBox_Parametre)
        self.label_Analyse_Remarque.setBuddy(self.lineEdit_AnalyseRemarque)
        self.label_RCP.setBuddy(self.textBrowser_medicament)
        self.label_medicament.setBuddy(self.comboBox_medicament)
        self.label_molecule.setBuddy(self.comboBox_molecule)
        self.label_posomol.setBuddy(self.lineEdit_posomol)
        self.label_presentation.setBuddy(self.comboBox_presentation)
        self.label_posomed.setBuddy(self.lineEdit_posomed)
        self.label_especeCible.setBuddy(self.comboBox_especeCible)
        self.label_10.setBuddy(self.dateEdit_ordonance)
        self.label_11.setBuddy(self.lineEdit_poids)
        self.label_doc.setBuddy(self.listView_doc)
        self.label_docFile.setBuddy(self.lineEdit_docFile)

        self.retranslateUi(tabWidget_medical)
        tabWidget_medical.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(tabWidget_medical)

    def retranslateUi(self, tabWidget_medical):
        self.button_vacciner.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Ajouter ce vaccin dans le dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.button_vacciner.setText(QtGui.QApplication.translate("tabWidget_medical", "Vacciner", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_vacciner_start.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Date de vaccination", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_vacciner_end.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Date de rappel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_vacciner.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Vaccin", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rappel.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Période de rappel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("tabWidget_medical", "Rappel :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vaccinerStart.setText(QtGui.QApplication.translate("tabWidget_medical", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_med_inf.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Ajouter un commentaire", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("tabWidget_medical", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_consult.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Date de consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_consult.setDisplayFormat(QtGui.QApplication.translate("tabWidget_medical", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("tabWidget_medical", "Vétérinaire :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_veterinaire.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Vétérinaire consultant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("tabWidget_medical", "   Type :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_consultType.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Choir le type dominant de la consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Referant.setText(QtGui.QApplication.translate("tabWidget_medical", "Référant :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Referant.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Choisir un vétérinaire référant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("tabWidget_medical", "Domaine Pathologique :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PathologieDomaine.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Domaine pathologique dominant de la consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Pathologie.setText(QtGui.QApplication.translate("tabWidget_medical", "Pathologie :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Pathologie.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Choisir une Pathologie Dominante pour cette Consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Pathologie.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Accès au formulaire de pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Pathologie.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_comment.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("tabWidget_medical", "Observations :", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_consultObs.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Insérer les observations cliniques", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("tabWidget_medical", "Traitements :", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_consultTrait.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Inserez les traitements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valider.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Enregistrer cette consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_valider.setText(QtGui.QApplication.translate("tabWidget_medical", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Nouveau.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Nouvelle Consultation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Nouveau.setText(QtGui.QApplication.translate("tabWidget_medical", "Nouveau", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Hospit.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Imprimer la fiche d\'hospitalisation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Hospit.setText(QtGui.QApplication.translate("tabWidget_medical", "Hospitalisation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Facturation.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Basculer en facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Facturation.setText(QtGui.QApplication.translate("tabWidget_medical", "Facturation", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_consulation), QtGui.QApplication.translate("tabWidget_medical", "Consultation", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab), QtGui.QApplication.translate("tabWidget_medical", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("tabWidget_medical", "Analyses précédentes", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_Analyses.setStatusTip(QtGui.QApplication.translate("tabWidget_medical", "Double click pour éditer l\'analyse", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_DeleteAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveAnalyse.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Ajouter l\'analyse au dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("tabWidget_medical", "Date Heure :  ", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit_analyse.setDisplayFormat(QtGui.QApplication.translate("tabWidget_medical", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("tabWidget_medical", "Description de l\'analyse:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("tabWidget_medical", "Prélèvement :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("tabWidget_medical", "Observations :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("tabWidget_medical", "Conclusions :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_TypeAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "Type d\'analyse :  ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditTypeAnalyse.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "AJouter des types d\'analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditTypeAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_model.setText(QtGui.QApplication.translate("tabWidget_medical", "Modèle :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditModelAnalyse.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "AJouter des types d\'analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditModelAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Parametre.setText(QtGui.QApplication.translate("tabWidget_medical", "Paramètre :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditParametre.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "AJouter des types d\'analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_EditParametre.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Analyse_Remarque.setText(QtGui.QApplication.translate("tabWidget_medical", "Remarque :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AnalyseImport.setText(QtGui.QApplication.translate("tabWidget_medical", "Importer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_VueAnalyse.setText(QtGui.QApplication.translate("tabWidget_medical", "Vue :", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Parametre.setText(QtGui.QApplication.translate("tabWidget_medical", "Parametres", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Document.setText(QtGui.QApplication.translate("tabWidget_medical", "Documents", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_analyses), QtGui.QApplication.translate("tabWidget_medical", "Analyses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_RCP.setText(QtGui.QApplication.translate("tabWidget_medical", "Mentions légales :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Texte complet", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Résumé", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_medicament.setText(QtGui.QApplication.translate("tabWidget_medical", "Médicament :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_molecule.setText(QtGui.QApplication.translate("tabWidget_medical", "Molécule :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_posomol.setText(QtGui.QApplication.translate("tabWidget_medical", "Posologie de principe actif :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_presentation.setText(QtGui.QApplication.translate("tabWidget_medical", "Présentation :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_posomed.setText(QtGui.QApplication.translate("tabWidget_medical", "Posologie de médicament :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_especeCible.setText(QtGui.QApplication.translate("tabWidget_medical", "Espèce cible :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_validOrdonnance.setText(QtGui.QApplication.translate("tabWidget_medical", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CalculPoso.setText(QtGui.QApplication.translate("tabWidget_medical", "Calculatrice", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DMV.setText(QtGui.QApplication.translate("tabWidget_medical", "Editer DMV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("tabWidget_medical", "Le :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_ordonance.setDisplayFormat(QtGui.QApplication.translate("tabWidget_medical", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("tabWidget_medical", "Poids :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_OrdonnanceValid.setText(QtGui.QApplication.translate("tabWidget_medical", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_ordonnances), QtGui.QApplication.translate("tabWidget_medical", "Ordonnances", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_planTherapeutique), QtGui.QApplication.translate("tabWidget_medical", "Plan Thérapeutique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_doc.setText(QtGui.QApplication.translate("tabWidget_medical", "Documents disponibles :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_docDate.setText(QtGui.QApplication.translate("tabWidget_medical", "Date :", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_docDate.setDisplayFormat(QtGui.QApplication.translate("tabWidget_medical", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_docFile.setText(QtGui.QApplication.translate("tabWidget_medical", "Fichier :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_docFile.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Selectionner un fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_docFile.setText(QtGui.QApplication.translate("tabWidget_medical", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_docAdd.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Ajouter nouveau document au dossier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_docAdd.setText(QtGui.QApplication.translate("tabWidget_medical", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_documents), QtGui.QApplication.translate("tabWidget_medical", "Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.DoDeleteDoc.setText(QtGui.QApplication.translate("tabWidget_medical", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.DoDeleteDoc.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Supprime le document séléctionné", None, QtGui.QApplication.UnicodeUTF8))
        self.DoEditDocument.setText(QtGui.QApplication.translate("tabWidget_medical", "Editer", None, QtGui.QApplication.UnicodeUTF8))
        self.DoEditDocument.setToolTip(QtGui.QApplication.translate("tabWidget_medical", "Editer l\'image selectionnée", None, QtGui.QApplication.UnicodeUTF8))
        self.DoDeleteParametre.setText(QtGui.QApplication.translate("tabWidget_medical", "Supprimer le paramètre", None, QtGui.QApplication.UnicodeUTF8))

from Mywidgets import MyPlainTextEdit, MyComboBox
import resources_rc
