# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_pathologie.ui'
#
# Created: Mon May  5 12:27:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogPathologie(object):
    def setupUi(self, DialogPathologie):
        DialogPathologie.setObjectName(_fromUtf8("DialogPathologie"))
        DialogPathologie.resize(788, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPathologie.setWindowIcon(icon)
        self.pushButton = QtGui.QPushButton(DialogPathologie)
        self.pushButton.setGeometry(QtCore.QRect(590, 50, 151, 27))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.layoutWidget = QtGui.QWidget(DialogPathologie)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 10, 521, 116))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_PathologieDomaine = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieDomaine.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_PathologieDomaine.setEditable(True)
        self.comboBox_PathologieDomaine.setObjectName(_fromUtf8("comboBox_PathologieDomaine"))
        self.horizontalLayout_5.addWidget(self.comboBox_PathologieDomaine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_PathologiePathologie = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_PathologiePathologie.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologiePathologie.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologiePathologie.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_PathologiePathologie.setEditable(True)
        self.comboBox_PathologiePathologie.setObjectName(_fromUtf8("comboBox_PathologiePathologie"))
        self.horizontalLayout_6.addWidget(self.comboBox_PathologiePathologie)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboBox_PathologieSelection = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_PathologieSelection.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieSelection.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieSelection.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_PathologieSelection.setObjectName(_fromUtf8("comboBox_PathologieSelection"))
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieSelection)
        self.toolButton_deletePathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_deletePathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/delete2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deletePathologie.setIcon(icon1)
        self.toolButton_deletePathologie.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_deletePathologie.setObjectName(_fromUtf8("toolButton_deletePathologie"))
        self.horizontalLayout_7.addWidget(self.toolButton_deletePathologie)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.widget = QtGui.QWidget(DialogPathologie)
        self.widget.setGeometry(QtCore.QRect(20, 130, 752, 441))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_NomPathologie = QtGui.QLabel(self.widget)
        self.label_NomPathologie.setMinimumSize(QtCore.QSize(500, 30))
        self.label_NomPathologie.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_NomPathologie.setFont(font)
        self.label_NomPathologie.setFrameShape(QtGui.QFrame.Box)
        self.label_NomPathologie.setLineWidth(2)
        self.label_NomPathologie.setTextFormat(QtCore.Qt.RichText)
        self.label_NomPathologie.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NomPathologie.setObjectName(_fromUtf8("label_NomPathologie"))
        self.horizontalLayout.addWidget(self.label_NomPathologie)
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setMinimumSize(QtCore.QSize(150, 27))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout.addWidget(self.checkBox)
        self.toolButton_documentPathologie = QtGui.QToolButton(self.widget)
        self.toolButton_documentPathologie.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_documentPathologie.setMaximumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_documentPathologie.setIcon(icon2)
        self.toolButton_documentPathologie.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_documentPathologie.setObjectName(_fromUtf8("toolButton_documentPathologie"))
        self.horizontalLayout.addWidget(self.toolButton_documentPathologie)
        self.toolButton_traitements = QtGui.QToolButton(self.widget)
        self.toolButton_traitements.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_traitements.setMaximumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/gelule.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_traitements.setIcon(icon3)
        self.toolButton_traitements.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_traitements.setObjectName(_fromUtf8("toolButton_traitements"))
        self.horizontalLayout.addWidget(self.toolButton_traitements)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.widget)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_3.addWidget(self.plainTextEdit)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.listWidget = QtGui.QListWidget(self.widget)
        self.listWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_Examen = QtGui.QComboBox(self.widget)
        self.comboBox_Examen.setMinimumSize(QtCore.QSize(230, 27))
        self.comboBox_Examen.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Examen.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Examen.setEditable(True)
        self.comboBox_Examen.setObjectName(_fromUtf8("comboBox_Examen"))
        self.horizontalLayout_2.addWidget(self.comboBox_Examen)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(260, 27))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.textBrowser = QtGui.QTextBrowser(self.widget)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolButton_deleteCritereSelection = QtGui.QToolButton(self.widget)
        self.toolButton_deleteCritereSelection.setMaximumSize(QtCore.QSize(27, 27))
        self.toolButton_deleteCritereSelection.setIcon(icon1)
        self.toolButton_deleteCritereSelection.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_deleteCritereSelection.setObjectName(_fromUtf8("toolButton_deleteCritereSelection"))
        self.verticalLayout.addWidget(self.toolButton_deleteCritereSelection)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.label.setBuddy(self.comboBox_PathologieDomaine)
        self.label_2.setBuddy(self.comboBox_PathologiePathologie)
        self.label_3.setBuddy(self.comboBox_PathologieSelection)
        self.label_5.setBuddy(self.plainTextEdit)
        self.label_8.setBuddy(self.listWidget)
        self.label_6.setBuddy(self.comboBox_Examen)
        self.label_7.setBuddy(self.comboBox)

        self.retranslateUi(DialogPathologie)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogPathologie.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogPathologie.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPathologie)

    def retranslateUi(self, DialogPathologie):
        DialogPathologie.setWindowTitle(_translate("DialogPathologie", "Formulaire de Pathologie", None))
        DialogPathologie.setToolTip(_translate("DialogPathologie", "Documents relatifs cette pathologie", None))
        self.pushButton.setText(_translate("DialogPathologie", "Plan Thérapeutique", None))
        self.label.setText(_translate("DialogPathologie", "Domaine :", None))
        self.label_2.setText(_translate("DialogPathologie", "Pathologie :", None))
        self.label_3.setText(_translate("DialogPathologie", "Sélection :", None))
        self.toolButton_deletePathologie.setText(_translate("DialogPathologie", "...", None))
        self.label_NomPathologie.setText(_translate("DialogPathologie", "Nom de référence ", None))
        self.checkBox.setText(_translate("DialogPathologie", "Maladie chronique", None))
        self.toolButton_documentPathologie.setText(_translate("DialogPathologie", "...", None))
        self.toolButton_traitements.setToolTip(_translate("DialogPathologie", "Traitements proposés", None))
        self.toolButton_traitements.setText(_translate("DialogPathologie", "...", None))
        self.label_5.setText(_translate("DialogPathologie", "Descriptif :", None))
        self.label_8.setText(_translate("DialogPathologie", "Synonymes :", None))
        self.label_6.setText(_translate("DialogPathologie", "Examen :", None))
        self.label_7.setText(_translate("DialogPathologie", "Critère :", None))
        self.toolButton_deleteCritereSelection.setText(_translate("DialogPathologie", "...", None))

import resources_rc
