# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_pathologie.ui'
#
# Created: Wed Feb 19 23:32:27 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogPathologie(object):
    def setupUi(self, DialogPathologie):
        DialogPathologie.setObjectName("DialogPathologie")
        DialogPathologie.resize(784, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPathologie.setWindowIcon(icon)
        self.pushButton_PlanTherapeutique = QtGui.QPushButton(DialogPathologie)
        self.pushButton_PlanTherapeutique.setGeometry(QtCore.QRect(590, 80, 151, 27))
        self.pushButton_PlanTherapeutique.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_PlanTherapeutique.setObjectName("pushButton_PlanTherapeutique")
        self.layoutWidget = QtGui.QWidget(DialogPathologie)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 752, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_NomPathologie = QtGui.QLabel(self.layoutWidget)
        self.label_NomPathologie.setMinimumSize(QtCore.QSize(500, 30))
        self.label_NomPathologie.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_NomPathologie.setFont(font)
        self.label_NomPathologie.setFrameShape(QtGui.QFrame.Box)
        self.label_NomPathologie.setLineWidth(2)
        self.label_NomPathologie.setTextFormat(QtCore.Qt.RichText)
        self.label_NomPathologie.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NomPathologie.setObjectName("label_NomPathologie")
        self.horizontalLayout.addWidget(self.label_NomPathologie)
        self.checkBox_Chronic = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Chronic.setMinimumSize(QtCore.QSize(150, 27))
        self.checkBox_Chronic.setObjectName("checkBox_Chronic")
        self.horizontalLayout.addWidget(self.checkBox_Chronic)
        self.toolButton_documentPathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_documentPathologie.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_documentPathologie.setMaximumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/doc_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_documentPathologie.setIcon(icon1)
        self.toolButton_documentPathologie.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_documentPathologie.setObjectName("toolButton_documentPathologie")
        self.horizontalLayout.addWidget(self.toolButton_documentPathologie)
        self.toolButton_traitements = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_traitements.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_traitements.setMaximumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/gelule.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_traitements.setIcon(icon2)
        self.toolButton_traitements.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_traitements.setObjectName("toolButton_traitements")
        self.horizontalLayout.addWidget(self.toolButton_traitements)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.plainTextEdit_Descriptif = QtGui.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit_Descriptif.setObjectName("plainTextEdit_Descriptif")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_Descriptif)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.listWidget_Synonymes = QtGui.QListWidget(self.layoutWidget)
        self.listWidget_Synonymes.setMaximumSize(QtCore.QSize(220, 16777215))
        self.listWidget_Synonymes.setObjectName("listWidget_Synonymes")
        self.horizontalLayout_3.addWidget(self.listWidget_Synonymes)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_Examen = MyComboBox(self.layoutWidget)
        self.comboBox_Examen.setMinimumSize(QtCore.QSize(230, 27))
        self.comboBox_Examen.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Examen.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Examen.setEditable(True)
        self.comboBox_Examen.setObjectName("comboBox_Examen")
        self.horizontalLayout_2.addWidget(self.comboBox_Examen)
        spacerItem = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboBox_Critere = MyComboBox(self.layoutWidget)
        self.comboBox_Critere.setMinimumSize(QtCore.QSize(320, 27))
        self.comboBox_Critere.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Critere.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Critere.setEditable(True)
        self.comboBox_Critere.setObjectName("comboBox_Critere")
        self.horizontalLayout_2.addWidget(self.comboBox_Critere)
        self.toolButton_AddCritere = QtGui.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/add1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddCritere.setIcon(icon3)
        self.toolButton_AddCritere.setIconSize(QtCore.QSize(18, 18))
        self.toolButton_AddCritere.setObjectName("toolButton_AddCritere")
        self.horizontalLayout_2.addWidget(self.toolButton_AddCritere)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_Criteres = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidget_Criteres.setRowCount(10)
        self.tableWidget_Criteres.setColumnCount(6)
        self.tableWidget_Criteres.setObjectName("tableWidget_Criteres")
        self.tableWidget_Criteres.setColumnCount(6)
        self.tableWidget_Criteres.setRowCount(10)
        self.tableWidget_Criteres.horizontalHeader().setVisible(True)
        self.tableWidget_Criteres.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.tableWidget_Criteres)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.layoutWidget1 = QtGui.QWidget(DialogPathologie)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 11, 501, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget1)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieDomaine.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieDomaine.setEditable(False)
        self.comboBox_PathologieDomaine.setObjectName("comboBox_PathologieDomaine")
        self.horizontalLayout_5.addWidget(self.comboBox_PathologieDomaine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_PathologiePathologie = MyComboBox(self.layoutWidget1)
        self.comboBox_PathologiePathologie.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologiePathologie.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologiePathologie.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologiePathologie.setEditable(True)
        self.comboBox_PathologiePathologie.setObjectName("comboBox_PathologiePathologie")
        self.horizontalLayout_6.addWidget(self.comboBox_PathologiePathologie)
        self.toolButton_AddPathologie = QtGui.QToolButton(self.layoutWidget1)
        self.toolButton_AddPathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_AddPathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/valid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddPathologie.setIcon(icon4)
        self.toolButton_AddPathologie.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_AddPathologie.setObjectName("toolButton_AddPathologie")
        self.horizontalLayout_6.addWidget(self.toolButton_AddPathologie)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboBox_PathologieSelection = MyComboBox(self.layoutWidget1)
        self.comboBox_PathologieSelection.setMinimumSize(QtCore.QSize(0, 27))
        self.comboBox_PathologieSelection.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_PathologieSelection.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_PathologieSelection.setObjectName("comboBox_PathologieSelection")
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieSelection)
        self.toolButton_deletePathologie = QtGui.QToolButton(self.layoutWidget1)
        self.toolButton_deletePathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/delete2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deletePathologie.setIcon(icon5)
        self.toolButton_deletePathologie.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_deletePathologie.setObjectName("toolButton_deletePathologie")
        self.horizontalLayout_7.addWidget(self.toolButton_deletePathologie)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.pushButton_PathologieSauve = QtGui.QPushButton(DialogPathologie)
        self.pushButton_PathologieSauve.setGeometry(QtCore.QRect(590, 40, 151, 27))
        self.pushButton_PathologieSauve.setObjectName("pushButton_PathologieSauve")
        self.label_5.setBuddy(self.plainTextEdit_Descriptif)
        self.label_8.setBuddy(self.listWidget_Synonymes)
        self.label_6.setBuddy(self.comboBox_Examen)
        self.label_7.setBuddy(self.comboBox_Critere)
        self.label.setBuddy(self.comboBox_PathologieDomaine)
        self.label_2.setBuddy(self.comboBox_PathologiePathologie)
        self.label_3.setBuddy(self.comboBox_PathologieSelection)

        self.retranslateUi(DialogPathologie)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DialogPathologie.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DialogPathologie.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPathologie)

    def retranslateUi(self, DialogPathologie):
        DialogPathologie.setWindowTitle(QtGui.QApplication.translate("DialogPathologie", "Formulaire de Pathologie", None, QtGui.QApplication.UnicodeUTF8))
        DialogPathologie.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Documents relatifs cette pathologie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PlanTherapeutique.setText(QtGui.QApplication.translate("DialogPathologie", "Plan Thérapeutique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NomPathologie.setText(QtGui.QApplication.translate("DialogPathologie", "Nom de référence ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Chronic.setText(QtGui.QApplication.translate("DialogPathologie", "Maladie chronique", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_documentPathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_traitements.setToolTip(QtGui.QApplication.translate("DialogPathologie", "Traitements proposés", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_traitements.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DialogPathologie", "Descriptif :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DialogPathologie", "Synonymes :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DialogPathologie", "Examen :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DialogPathologie", "Critère :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddCritere.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogPathologie", "Domaine :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogPathologie", "Pathologie :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_AddPathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DialogPathologie", "Sélection :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_deletePathologie.setText(QtGui.QApplication.translate("DialogPathologie", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_PathologieSauve.setText(QtGui.QApplication.translate("DialogPathologie", "Sauve Pathologie", None, QtGui.QApplication.UnicodeUTF8))

from Mywidgets import MyComboBox
import resources_rc
