# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_consultation_base.ui'
#
# Created: Mon May 12 12:17:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowConsultation(object):
    def setupUi(self, MainWindowConsultation):
        MainWindowConsultation.setObjectName(_fromUtf8("MainWindowConsultation"))
        MainWindowConsultation.resize(1080, 751)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowConsultation.sizePolicy().hasHeightForWidth())
        MainWindowConsultation.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowConsultation.setWindowIcon(icon)
        MainWindowConsultation.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindowConsultation)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_consultation = QtGui.QFrame(self.centralwidget)
        self.frame_consultation.setGeometry(QtCore.QRect(0, 0, 1080, 771))
        self.frame_consultation.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_consultation.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_consultation.setObjectName(_fromUtf8("frame_consultation"))
        self.frame_haut = QtGui.QFrame(self.frame_consultation)
        self.frame_haut.setGeometry(QtCore.QRect(10, 20, 1070, 160))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_haut.sizePolicy().hasHeightForWidth())
        self.frame_haut.setSizePolicy(sizePolicy)
        self.frame_haut.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_haut.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_haut.setObjectName(_fromUtf8("frame_haut"))
        self.frame_client = QtGui.QFrame(self.frame_haut)
        self.frame_client.setGeometry(QtCore.QRect(2, 20, 470, 120))
        self.frame_client.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_client.setFrameShape(QtGui.QFrame.Box)
        self.frame_client.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_client.setLineWidth(1)
        self.frame_client.setObjectName(_fromUtf8("frame_client"))
        self.textBrowser_client = QtGui.QTextBrowser(self.frame_client)
        self.textBrowser_client.setGeometry(QtCore.QRect(10, 50, 451, 61))
        self.textBrowser_client.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.textBrowser_client.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_client.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_client.setLineWidth(1)
        self.textBrowser_client.setMidLineWidth(0)
        self.textBrowser_client.setObjectName(_fromUtf8("textBrowser_client"))
        self.toolButton_ClientInfo = QtGui.QToolButton(self.frame_client)
        self.toolButton_ClientInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClientInfo.setIcon(icon1)
        self.toolButton_ClientInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_ClientInfo.setObjectName(_fromUtf8("toolButton_ClientInfo"))
        self.comboBox = QtGui.QComboBox(self.frame_client)
        self.comboBox.setGeometry(QtCore.QRect(120, -10, 78, 23))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_client = QtGui.QComboBox(self.frame_client)
        self.comboBox_client.setGeometry(QtCore.QRect(17, 10, 401, 23))
        self.comboBox_client.setObjectName(_fromUtf8("comboBox_client"))
        self.frame_animal = QtGui.QFrame(self.frame_haut)
        self.frame_animal.setGeometry(QtCore.QRect(570, 20, 470, 120))
        self.frame_animal.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_animal.setFrameShape(QtGui.QFrame.Box)
        self.frame_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_animal.setObjectName(_fromUtf8("frame_animal"))
        self.textBrowser_animal = QtGui.QTextBrowser(self.frame_animal)
        self.textBrowser_animal.setGeometry(QtCore.QRect(10, 50, 454, 61))
        self.textBrowser_animal.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.textBrowser_animal.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_animal.setObjectName(_fromUtf8("textBrowser_animal"))
        self.toolButton_AnimalInfo = QtGui.QToolButton(self.frame_animal)
        self.toolButton_AnimalInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        self.toolButton_AnimalInfo.setIcon(icon1)
        self.toolButton_AnimalInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_AnimalInfo.setObjectName(_fromUtf8("toolButton_AnimalInfo"))
        self.comboBox_Animal = QtGui.QComboBox(self.frame_animal)
        self.comboBox_Animal.setGeometry(QtCore.QRect(10, 10, 401, 23))
        self.comboBox_Animal.setObjectName(_fromUtf8("comboBox_Animal"))
        self.toolButton_scan = QtGui.QToolButton(self.frame_haut)
        self.toolButton_scan.setGeometry(QtCore.QRect(510, 120, 26, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/loupe2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scan.setIcon(icon2)
        self.toolButton_scan.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan.setObjectName(_fromUtf8("toolButton_scan"))
        self.toolButton_addAnimal = QtGui.QToolButton(self.frame_haut)
        self.toolButton_addAnimal.setGeometry(QtCore.QRect(527, 25, 26, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/add1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addAnimal.setIcon(icon3)
        self.toolButton_addAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addAnimal.setObjectName(_fromUtf8("toolButton_addAnimal"))
        self.toolButton_editClient = QtGui.QToolButton(self.frame_haut)
        self.toolButton_editClient.setGeometry(QtCore.QRect(491, 57, 26, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/edit1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editClient.setIcon(icon4)
        self.toolButton_editClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editClient.setObjectName(_fromUtf8("toolButton_editClient"))
        self.toolButton_deleteAnimal = QtGui.QToolButton(self.frame_haut)
        self.toolButton_deleteAnimal.setGeometry(QtCore.QRect(527, 89, 26, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/delete2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deleteAnimal.setIcon(icon5)
        self.toolButton_deleteAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteAnimal.setObjectName(_fromUtf8("toolButton_deleteAnimal"))
        self.toolButton_deleteClient = QtGui.QToolButton(self.frame_haut)
        self.toolButton_deleteClient.setGeometry(QtCore.QRect(491, 89, 26, 25))
        self.toolButton_deleteClient.setIcon(icon5)
        self.toolButton_deleteClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteClient.setObjectName(_fromUtf8("toolButton_deleteClient"))
        self.toolButton_addClient = QtGui.QToolButton(self.frame_haut)
        self.toolButton_addClient.setGeometry(QtCore.QRect(491, 25, 26, 25))
        self.toolButton_addClient.setIcon(icon3)
        self.toolButton_addClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addClient.setObjectName(_fromUtf8("toolButton_addClient"))
        self.toolButton_editAnimal = QtGui.QToolButton(self.frame_haut)
        self.toolButton_editAnimal.setGeometry(QtCore.QRect(527, 57, 26, 25))
        self.toolButton_editAnimal.setIcon(icon4)
        self.toolButton_editAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editAnimal.setObjectName(_fromUtf8("toolButton_editAnimal"))
        self.frame_bas = QtGui.QFrame(self.frame_consultation)
        self.frame_bas.setGeometry(QtCore.QRect(10, 190, 1070, 561))
        self.frame_bas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_bas.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_bas.setObjectName(_fromUtf8("frame_bas"))
        self.tabWidget_medical = QtGui.QTabWidget(self.frame_bas)
        self.tabWidget_medical.setGeometry(QtCore.QRect(10, 10, 1031, 541))
        self.tabWidget_medical.setObjectName(_fromUtf8("tabWidget_medical"))
        self.tab_consulation = QtGui.QWidget()
        self.tab_consulation.setObjectName(_fromUtf8("tab_consulation"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_consulation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 531))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.textBrowser_consultations = QtGui.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_consultations.sizePolicy().hasHeightForWidth())
        self.textBrowser_consultations.setSizePolicy(sizePolicy)
        self.textBrowser_consultations.setMaximumSize(QtCore.QSize(10000, 15000))
        self.textBrowser_consultations.setStyleSheet(_fromUtf8("background-position: right; background-image:  url(:/newPrefix/images/openvet.png);background-repeat: no-repeat; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.textBrowser_consultations.setObjectName(_fromUtf8("textBrowser_consultations"))
        self.horizontalLayout.addWidget(self.textBrowser_consultations)
        self.frame_vaccin = QtGui.QFrame(self.verticalLayoutWidget)
        self.frame_vaccin.setMinimumSize(QtCore.QSize(380, 90))
        self.frame_vaccin.setMaximumSize(QtCore.QSize(370, 220))
        self.frame_vaccin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_vaccin.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_vaccin.setObjectName(_fromUtf8("frame_vaccin"))
        self.button_vacciner = QtGui.QPushButton(self.frame_vaccin)
        self.button_vacciner.setGeometry(QtCore.QRect(230, 180, 93, 27))
        self.button_vacciner.setObjectName(_fromUtf8("button_vacciner"))
        self.tableWidget_vacciner = QtGui.QTableWidget(self.frame_vaccin)
        self.tableWidget_vacciner.setGeometry(QtCore.QRect(50, 0, 311, 121))
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setObjectName(_fromUtf8("tableWidget_vacciner"))
        self.tableWidget_vacciner.verticalHeader().setVisible(False)
        self.label_vaccinerStart = QtGui.QLabel(self.frame_vaccin)
        self.label_vaccinerStart.setGeometry(QtCore.QRect(40, 140, 31, 17))
        self.label_vaccinerStart.setObjectName(_fromUtf8("label_vaccinerStart"))
        self.comboBox_rappel = QtGui.QComboBox(self.frame_vaccin)
        self.comboBox_rappel.setGeometry(QtCore.QRect(70, 160, 141, 27))
        self.comboBox_rappel.setObjectName(_fromUtf8("comboBox_rappel"))
        self.dateEdit_vacciner_end = QtGui.QDateEdit(self.frame_vaccin)
        self.dateEdit_vacciner_end.setGeometry(QtCore.QRect(230, 150, 101, 27))
        self.dateEdit_vacciner_end.setCalendarPopup(True)
        self.dateEdit_vacciner_end.setObjectName(_fromUtf8("dateEdit_vacciner_end"))
        self.dateEdit_vacciner_start = QtGui.QDateEdit(self.frame_vaccin)
        self.dateEdit_vacciner_start.setGeometry(QtCore.QRect(80, 130, 101, 27))
        self.dateEdit_vacciner_start.setCalendarPopup(True)
        self.dateEdit_vacciner_start.setObjectName(_fromUtf8("dateEdit_vacciner_start"))
        self.label_23 = QtGui.QLabel(self.frame_vaccin)
        self.label_23.setGeometry(QtCore.QRect(10, 160, 62, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.comboBox_vacciner = QtGui.QComboBox(self.frame_vaccin)
        self.comboBox_vacciner.setGeometry(QtCore.QRect(230, 120, 101, 27))
        self.comboBox_vacciner.setObjectName(_fromUtf8("comboBox_vacciner"))
        self.horizontalLayout.addWidget(self.frame_vaccin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_edit_consult = QtGui.QFrame(self.verticalLayoutWidget)
        self.frame_edit_consult.setMinimumSize(QtCore.QSize(800, 266))
        self.frame_edit_consult.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.frame_edit_consult.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_edit_consult.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_edit_consult.setObjectName(_fromUtf8("frame_edit_consult"))
        self.layoutWidget_8 = QtGui.QWidget(self.frame_edit_consult)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 10, 987, 246))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_8)
        self.label_17.setMaximumSize(QtCore.QSize(25, 27))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.dateEdit_consult = QtGui.QDateEdit(self.layoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_consult.sizePolicy().hasHeightForWidth())
        self.dateEdit_consult.setSizePolicy(sizePolicy)
        self.dateEdit_consult.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_consult.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dateEdit_consult.setCalendarPopup(True)
        self.dateEdit_consult.setObjectName(_fromUtf8("dateEdit_consult"))
        self.horizontalLayout_12.addWidget(self.dateEdit_consult)
        self.label_24 = QtGui.QLabel(self.layoutWidget_8)
        self.label_24.setMinimumSize(QtCore.QSize(82, 0))
        self.label_24.setMaximumSize(QtCore.QSize(82, 27))
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_12.addWidget(self.label_24)
        self.comboBox_veterinaire = MyComboBox(self.layoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_veterinaire.sizePolicy().hasHeightForWidth())
        self.comboBox_veterinaire.setSizePolicy(sizePolicy)
        self.comboBox_veterinaire.setMinimumSize(QtCore.QSize(200, 27))
        self.comboBox_veterinaire.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_veterinaire.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_veterinaire.setEditable(True)
        self.comboBox_veterinaire.setFrame(True)
        self.comboBox_veterinaire.setObjectName(_fromUtf8("comboBox_veterinaire"))
        self.horizontalLayout_12.addWidget(self.comboBox_veterinaire)
        self.label_25 = QtGui.QLabel(self.layoutWidget_8)
        self.label_25.setMaximumSize(QtCore.QSize(50, 27))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_12.addWidget(self.label_25)
        self.comboBox_consultType = MyComboBox(self.layoutWidget_8)
        self.comboBox_consultType.setMinimumSize(QtCore.QSize(160, 27))
        self.comboBox_consultType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_consultType.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_consultType.setObjectName(_fromUtf8("comboBox_consultType"))
        self.horizontalLayout_12.addWidget(self.comboBox_consultType)
        self.label_Referant = QtGui.QLabel(self.layoutWidget_8)
        self.label_Referant.setMaximumSize(QtCore.QSize(63, 27))
        self.label_Referant.setObjectName(_fromUtf8("label_Referant"))
        self.horizontalLayout_12.addWidget(self.label_Referant)
        self.comboBox_Referant = MyComboBox(self.layoutWidget_8)
        self.comboBox_Referant.setMinimumSize(QtCore.QSize(181, 27))
        self.comboBox_Referant.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Referant.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Referant.setEditable(True)
        self.comboBox_Referant.setObjectName(_fromUtf8("comboBox_Referant"))
        self.horizontalLayout_12.addWidget(self.comboBox_Referant)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_8)
        self.label_26.setMaximumSize(QtCore.QSize(160, 27))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_14.addWidget(self.label_26)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget_8)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(200, 27))
        self.comboBox_PathologieDomaine.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_PathologieDomaine.setObjectName(_fromUtf8("comboBox_PathologieDomaine"))
        self.horizontalLayout_14.addWidget(self.comboBox_PathologieDomaine)
        self.label_Pathologie = QtGui.QLabel(self.layoutWidget_8)
        self.label_Pathologie.setMinimumSize(QtCore.QSize(81, 0))
        self.label_Pathologie.setMaximumSize(QtCore.QSize(81, 27))
        self.label_Pathologie.setObjectName(_fromUtf8("label_Pathologie"))
        self.horizontalLayout_14.addWidget(self.label_Pathologie)
        self.comboBox_Pathologie = MyComboBox(self.layoutWidget_8)
        self.comboBox_Pathologie.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox_Pathologie.setMaximumSize(QtCore.QSize(261, 27))
        self.comboBox_Pathologie.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Pathologie.setEditable(False)
        self.comboBox_Pathologie.setObjectName(_fromUtf8("comboBox_Pathologie"))
        self.horizontalLayout_14.addWidget(self.comboBox_Pathologie)
        self.toolButton_Pathologie = QtGui.QToolButton(self.layoutWidget_8)
        self.toolButton_Pathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_Pathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/pathologie.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Pathologie.setIcon(icon6)
        self.toolButton_Pathologie.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Pathologie.setObjectName(_fromUtf8("toolButton_Pathologie"))
        self.horizontalLayout_14.addWidget(self.toolButton_Pathologie)
        self.toolButton_comment = QtGui.QToolButton(self.layoutWidget_8)
        self.toolButton_comment.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setMaximumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setIcon(icon1)
        self.toolButton_comment.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_comment.setObjectName(_fromUtf8("toolButton_comment"))
        self.horizontalLayout_14.addWidget(self.toolButton_comment)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_27 = QtGui.QLabel(self.layoutWidget_8)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_27)
        self.textEdit_consultObs = QtGui.QTextEdit(self.layoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultObs.sizePolicy().hasHeightForWidth())
        self.textEdit_consultObs.setSizePolicy(sizePolicy)
        self.textEdit_consultObs.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultObs.setMaximumSize(QtCore.QSize(16777215, 111))
        self.textEdit_consultObs.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultObs.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_consultObs.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit_consultObs.setObjectName(_fromUtf8("textEdit_consultObs"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit_consultObs)
        self.label_28 = QtGui.QLabel(self.layoutWidget_8)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_28)
        self.textEdit_consultTrait = QtGui.QTextEdit(self.layoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultTrait.sizePolicy().hasHeightForWidth())
        self.textEdit_consultTrait.setSizePolicy(sizePolicy)
        self.textEdit_consultTrait.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultTrait.setMaximumSize(QtCore.QSize(16777215, 51))
        self.textEdit_consultTrait.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultTrait.setObjectName(_fromUtf8("textEdit_consultTrait"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEdit_consultTrait)
        self.verticalLayout_11.addLayout(self.formLayout_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_valider = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_valider.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.verticalLayout_12.addWidget(self.pushButton_valider)
        self.pushButton_Nouveau = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_Nouveau.setObjectName(_fromUtf8("pushButton_Nouveau"))
        self.verticalLayout_12.addWidget(self.pushButton_Nouveau)
        self.pushButton_Hospit = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_Hospit.setObjectName(_fromUtf8("pushButton_Hospit"))
        self.verticalLayout_12.addWidget(self.pushButton_Hospit)
        self.pushButton_Facturation = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_Facturation.setObjectName(_fromUtf8("pushButton_Facturation"))
        self.verticalLayout_12.addWidget(self.pushButton_Facturation)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.frame_edit_consult)
        self.tabWidget_medical.addTab(self.tab_consulation, _fromUtf8(""))
        self.tab_vaccins = QtGui.QWidget()
        self.tab_vaccins.setObjectName(_fromUtf8("tab_vaccins"))
        self.tabWidget_medical.addTab(self.tab_vaccins, _fromUtf8(""))
        self.tab_analyses = QtGui.QWidget()
        self.tab_analyses.setObjectName(_fromUtf8("tab_analyses"))
        self.tableWidget_analyses = QtGui.QTableWidget(self.tab_analyses)
        self.tableWidget_analyses.setEnabled(True)
        self.tableWidget_analyses.setGeometry(QtCore.QRect(650, 70, 350, 241))
        self.tableWidget_analyses.setShowGrid(True)
        self.tableWidget_analyses.setRowCount(16)
        self.tableWidget_analyses.setColumnCount(4)
        self.tableWidget_analyses.setObjectName(_fromUtf8("tableWidget_analyses"))
        self.tableWidget_analyses.verticalHeader().setVisible(False)
        self.listWidget_analyse = QtGui.QListWidget(self.tab_analyses)
        self.listWidget_analyse.setGeometry(QtCore.QRect(650, 60, 351, 192))
        self.listWidget_analyse.setObjectName(_fromUtf8("listWidget_analyse"))
        self.lineEdit_titreImage = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_titreImage.setGeometry(QtCore.QRect(650, 340, 311, 27))
        self.lineEdit_titreImage.setObjectName(_fromUtf8("lineEdit_titreImage"))
        self.lineEdit_fichier = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_fichier.setGeometry(QtCore.QRect(650, 390, 311, 27))
        self.lineEdit_fichier.setObjectName(_fromUtf8("lineEdit_fichier"))
        self.toolButton_fichier = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_fichier.setGeometry(QtCore.QRect(970, 390, 26, 25))
        self.toolButton_fichier.setObjectName(_fromUtf8("toolButton_fichier"))
        self.pushButton_addImage = QtGui.QPushButton(self.tab_analyses)
        self.pushButton_addImage.setGeometry(QtCore.QRect(760, 430, 111, 27))
        self.pushButton_addImage.setObjectName(_fromUtf8("pushButton_addImage"))
        self.line_4 = QtGui.QFrame(self.tab_analyses)
        self.line_4.setGeometry(QtCore.QRect(620, 30, 20, 420))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.tab_analyses)
        self.line_5.setGeometry(QtCore.QRect(270, 30, 20, 420))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_12 = QtGui.QLabel(self.tab_analyses)
        self.label_12.setGeometry(QtCore.QRect(660, 11, 113, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox_typeanalyse = QtGui.QComboBox(self.tab_analyses)
        self.comboBox_typeanalyse.setGeometry(QtCore.QRect(780, 10, 181, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_typeanalyse.sizePolicy().hasHeightForWidth())
        self.comboBox_typeanalyse.setSizePolicy(sizePolicy)
        self.comboBox_typeanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_typeanalyse.setObjectName(_fromUtf8("comboBox_typeanalyse"))
        self.label_13 = QtGui.QLabel(self.tab_analyses)
        self.label_13.setGeometry(QtCore.QRect(50, 12, 171, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.listView = QtGui.QListView(self.tab_analyses)
        self.listView.setGeometry(QtCore.QRect(18, 37, 239, 410))
        self.listView.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.layoutWidget_9 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget_9.setGeometry(QtCore.QRect(303, 12, 303, 438))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_9)
        self.label_14.setBaseSize(QtCore.QSize(0, 0))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.dateTimeEdit_analyse = QtGui.QDateTimeEdit(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_analyse.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_analyse.setSizePolicy(sizePolicy)
        self.dateTimeEdit_analyse.setMinimumSize(QtCore.QSize(156, 27))
        self.dateTimeEdit_analyse.setCalendarPopup(True)
        self.dateTimeEdit_analyse.setObjectName(_fromUtf8("dateTimeEdit_analyse"))
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_analyse)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.label_15 = QtGui.QLabel(self.layoutWidget_9)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.lineEdit_description = QtGui.QLineEdit(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_description.sizePolicy().hasHeightForWidth())
        self.lineEdit_description.setSizePolicy(sizePolicy)
        self.lineEdit_description.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_description.setObjectName(_fromUtf8("lineEdit_description"))
        self.verticalLayout_5.addWidget(self.lineEdit_description)
        self.label_30 = QtGui.QLabel(self.layoutWidget_9)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_5.addWidget(self.label_30)
        self.lineEdit_prelevement = QtGui.QLineEdit(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prelevement.sizePolicy().hasHeightForWidth())
        self.lineEdit_prelevement.setSizePolicy(sizePolicy)
        self.lineEdit_prelevement.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_prelevement.setObjectName(_fromUtf8("lineEdit_prelevement"))
        self.verticalLayout_5.addWidget(self.lineEdit_prelevement)
        self.label_31 = QtGui.QLabel(self.layoutWidget_9)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_5.addWidget(self.label_31)
        self.textEdit_syntheseanalyse = QtGui.QTextEdit(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_syntheseanalyse.sizePolicy().hasHeightForWidth())
        self.textEdit_syntheseanalyse.setSizePolicy(sizePolicy)
        self.textEdit_syntheseanalyse.setMinimumSize(QtCore.QSize(301, 120))
        self.textEdit_syntheseanalyse.setMaximumSize(QtCore.QSize(16777215, 141))
        self.textEdit_syntheseanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_syntheseanalyse.setAutoFillBackground(False)
        self.textEdit_syntheseanalyse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_syntheseanalyse.setObjectName(_fromUtf8("textEdit_syntheseanalyse"))
        self.verticalLayout_5.addWidget(self.textEdit_syntheseanalyse)
        self.label_32 = QtGui.QLabel(self.layoutWidget_9)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_5.addWidget(self.label_32)
        self.textEdit_conclusions = QtGui.QTextEdit(self.layoutWidget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_conclusions.sizePolicy().hasHeightForWidth())
        self.textEdit_conclusions.setSizePolicy(sizePolicy)
        self.textEdit_conclusions.setMinimumSize(QtCore.QSize(301, 0))
        self.textEdit_conclusions.setMaximumSize(QtCore.QSize(16777215, 61))
        self.textEdit_conclusions.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_conclusions.setObjectName(_fromUtf8("textEdit_conclusions"))
        self.verticalLayout_5.addWidget(self.textEdit_conclusions)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_valide = QtGui.QPushButton(self.layoutWidget_9)
        self.pushButton_valide.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_valide.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_valide.setObjectName(_fromUtf8("pushButton_valide"))
        self.horizontalLayout_8.addWidget(self.pushButton_valide)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.toolButton_AddTypeAnalyse = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_AddTypeAnalyse.setGeometry(QtCore.QRect(970, 10, 26, 25))
        self.toolButton_AddTypeAnalyse.setIcon(icon3)
        self.toolButton_AddTypeAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddTypeAnalyse.setObjectName(_fromUtf8("toolButton_AddTypeAnalyse"))
        self.tabWidget_medical.addTab(self.tab_analyses, _fromUtf8(""))
        self.tab_ordonnances = QtGui.QWidget()
        self.tab_ordonnances.setObjectName(_fromUtf8("tab_ordonnances"))
        self.textBrowser_medicament = QtGui.QTextBrowser(self.tab_ordonnances)
        self.textBrowser_medicament.setGeometry(QtCore.QRect(540, 220, 451, 231))
        self.textBrowser_medicament.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_medicament.setObjectName(_fromUtf8("textBrowser_medicament"))
        self.label_RCP = QtGui.QLabel(self.tab_ordonnances)
        self.label_RCP.setGeometry(QtCore.QRect(540, 200, 131, 17))
        self.label_RCP.setObjectName(_fromUtf8("label_RCP"))
        self.line_6 = QtGui.QFrame(self.tab_ordonnances)
        self.line_6.setGeometry(QtCore.QRect(515, 20, 20, 501))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.toolButton_3 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_3.setGeometry(QtCore.QRect(960, 190, 26, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon7)
        self.toolButton_3.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.toolButton_4 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_4.setGeometry(QtCore.QRect(920, 190, 26, 25))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_abst.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon8)
        self.toolButton_4.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.layoutWidget_10 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_10.setGeometry(QtCore.QRect(543, 10, 451, 171))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_10)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_medicament = QtGui.QLabel(self.layoutWidget_10)
        self.label_medicament.setObjectName(_fromUtf8("label_medicament"))
        self.gridLayout.addWidget(self.label_medicament, 0, 0, 1, 1)
        self.label_molecule = QtGui.QLabel(self.layoutWidget_10)
        self.label_molecule.setObjectName(_fromUtf8("label_molecule"))
        self.gridLayout.addWidget(self.label_molecule, 0, 1, 1, 1)
        self.comboBox_medicament = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_medicament.sizePolicy().hasHeightForWidth())
        self.comboBox_medicament.setSizePolicy(sizePolicy)
        self.comboBox_medicament.setObjectName(_fromUtf8("comboBox_medicament"))
        self.gridLayout.addWidget(self.comboBox_medicament, 1, 0, 1, 1)
        self.comboBox_molecule = QtGui.QComboBox(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_molecule.sizePolicy().hasHeightForWidth())
        self.comboBox_molecule.setSizePolicy(sizePolicy)
        self.comboBox_molecule.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_molecule.setObjectName(_fromUtf8("comboBox_molecule"))
        self.gridLayout.addWidget(self.comboBox_molecule, 1, 1, 1, 1)
        self.label_posomol = QtGui.QLabel(self.layoutWidget_10)
        self.label_posomol.setObjectName(_fromUtf8("label_posomol"))
        self.gridLayout.addWidget(self.label_posomol, 2, 0, 1, 1)
        self.label_presentation = QtGui.QLabel(self.layoutWidget_10)
        self.label_presentation.setObjectName(_fromUtf8("label_presentation"))
        self.gridLayout.addWidget(self.label_presentation, 2, 1, 1, 1)
        self.lineEdit_posomol = QtGui.QLineEdit(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomol.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomol.setSizePolicy(sizePolicy)
        self.lineEdit_posomol.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomol.setObjectName(_fromUtf8("lineEdit_posomol"))
        self.gridLayout.addWidget(self.lineEdit_posomol, 3, 0, 1, 1)
        self.comboBox_presentation = QtGui.QComboBox(self.layoutWidget_10)
        self.comboBox_presentation.setObjectName(_fromUtf8("comboBox_presentation"))
        self.gridLayout.addWidget(self.comboBox_presentation, 3, 1, 1, 1)
        self.label_posomed = QtGui.QLabel(self.layoutWidget_10)
        self.label_posomed.setObjectName(_fromUtf8("label_posomed"))
        self.gridLayout.addWidget(self.label_posomed, 4, 0, 1, 1)
        self.label_especeCible = QtGui.QLabel(self.layoutWidget_10)
        self.label_especeCible.setObjectName(_fromUtf8("label_especeCible"))
        self.gridLayout.addWidget(self.label_especeCible, 4, 1, 1, 1)
        self.lineEdit_posomed = QtGui.QLineEdit(self.layoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomed.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomed.setSizePolicy(sizePolicy)
        self.lineEdit_posomed.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomed.setObjectName(_fromUtf8("lineEdit_posomed"))
        self.gridLayout.addWidget(self.lineEdit_posomed, 5, 0, 1, 1)
        self.comboBox_especeCible = QtGui.QComboBox(self.layoutWidget_10)
        self.comboBox_especeCible.setObjectName(_fromUtf8("comboBox_especeCible"))
        self.gridLayout.addWidget(self.comboBox_especeCible, 5, 1, 1, 1)
        self.layoutWidget_11 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_11.setGeometry(QtCore.QRect(540, 490, 451, 29))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButton_validOrdonnance = QtGui.QPushButton(self.layoutWidget_11)
        self.pushButton_validOrdonnance.setObjectName(_fromUtf8("pushButton_validOrdonnance"))
        self.horizontalLayout_15.addWidget(self.pushButton_validOrdonnance)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.pushButton_CalculPoso = QtGui.QPushButton(self.layoutWidget_11)
        self.pushButton_CalculPoso.setObjectName(_fromUtf8("pushButton_CalculPoso"))
        self.horizontalLayout_15.addWidget(self.pushButton_CalculPoso)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.pushButton_DMV = QtGui.QPushButton(self.layoutWidget_11)
        self.pushButton_DMV.setObjectName(_fromUtf8("pushButton_DMV"))
        self.horizontalLayout_15.addWidget(self.pushButton_DMV)
        self.layoutWidget_12 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_12.setGeometry(QtCore.QRect(11, 31, 512, 387))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_33 = QtGui.QLabel(self.layoutWidget_12)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_16.addWidget(self.label_33)
        self.dateEdit_ordonance = QtGui.QDateEdit(self.layoutWidget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ordonance.sizePolicy().hasHeightForWidth())
        self.dateEdit_ordonance.setSizePolicy(sizePolicy)
        self.dateEdit_ordonance.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_ordonance.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_ordonance.setCalendarPopup(True)
        self.dateEdit_ordonance.setObjectName(_fromUtf8("dateEdit_ordonance"))
        self.horizontalLayout_16.addWidget(self.dateEdit_ordonance)
        spacerItem2 = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.label_34 = QtGui.QLabel(self.layoutWidget_12)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_16.addWidget(self.label_34)
        self.lineEdit_poids = QtGui.QLineEdit(self.layoutWidget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_poids.sizePolicy().hasHeightForWidth())
        self.lineEdit_poids.setSizePolicy(sizePolicy)
        self.lineEdit_poids.setMinimumSize(QtCore.QSize(66, 27))
        self.lineEdit_poids.setObjectName(_fromUtf8("lineEdit_poids"))
        self.horizontalLayout_16.addWidget(self.lineEdit_poids)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(496, 391))
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_6.addWidget(self.textEdit)
        self.pushButton_OrdonnanceValid = QtGui.QPushButton(self.tab_ordonnances)
        self.pushButton_OrdonnanceValid.setGeometry(QtCore.QRect(200, 430, 93, 27))
        self.pushButton_OrdonnanceValid.setObjectName(_fromUtf8("pushButton_OrdonnanceValid"))
        self.tabWidget_medical.addTab(self.tab_ordonnances, _fromUtf8(""))
        self.tab_planTherapeutique = QtGui.QWidget()
        self.tab_planTherapeutique.setObjectName(_fromUtf8("tab_planTherapeutique"))
        self.tabWidget_medical.addTab(self.tab_planTherapeutique, _fromUtf8(""))
        self.tab_documents = QtGui.QWidget()
        self.tab_documents.setObjectName(_fromUtf8("tab_documents"))
        self.listView_doc = QtGui.QListView(self.tab_documents)
        self.listView_doc.setGeometry(QtCore.QRect(20, 90, 241, 341))
        self.listView_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView_doc.setObjectName(_fromUtf8("listView_doc"))
        self.label_doc = QtGui.QLabel(self.tab_documents)
        self.label_doc.setGeometry(QtCore.QRect(10, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_doc.setFont(font)
        self.label_doc.setTextFormat(QtCore.Qt.PlainText)
        self.label_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doc.setObjectName(_fromUtf8("label_doc"))
        self.layoutWidget_13 = QtGui.QWidget(self.tab_documents)
        self.layoutWidget_13.setGeometry(QtCore.QRect(320, 52, 631, 378))
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_docDate = QtGui.QLabel(self.layoutWidget_13)
        self.label_docDate.setObjectName(_fromUtf8("label_docDate"))
        self.horizontalLayout_17.addWidget(self.label_docDate)
        self.dateEdit_docDate = QtGui.QDateEdit(self.layoutWidget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_docDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_docDate.setSizePolicy(sizePolicy)
        self.dateEdit_docDate.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_docDate.setCalendarPopup(True)
        self.dateEdit_docDate.setObjectName(_fromUtf8("dateEdit_docDate"))
        self.horizontalLayout_17.addWidget(self.dateEdit_docDate)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.label_docFile = QtGui.QLabel(self.layoutWidget_13)
        self.label_docFile.setObjectName(_fromUtf8("label_docFile"))
        self.horizontalLayout_17.addWidget(self.label_docFile)
        self.lineEdit_docFile = QtGui.QLineEdit(self.layoutWidget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_docFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_docFile.setSizePolicy(sizePolicy)
        self.lineEdit_docFile.setMinimumSize(QtCore.QSize(212, 27))
        self.lineEdit_docFile.setObjectName(_fromUtf8("lineEdit_docFile"))
        self.horizontalLayout_17.addWidget(self.lineEdit_docFile)
        self.toolButton_docFile = QtGui.QToolButton(self.layoutWidget_13)
        self.toolButton_docFile.setObjectName(_fromUtf8("toolButton_docFile"))
        self.horizontalLayout_17.addWidget(self.toolButton_docFile)
        self.pushButton_docAdd = QtGui.QPushButton(self.layoutWidget_13)
        self.pushButton_docAdd.setObjectName(_fromUtf8("pushButton_docAdd"))
        self.horizontalLayout_17.addWidget(self.pushButton_docAdd)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.textBrowser_doc = QtGui.QTextBrowser(self.layoutWidget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_doc.sizePolicy().hasHeightForWidth())
        self.textBrowser_doc.setSizePolicy(sizePolicy)
        self.textBrowser_doc.setMinimumSize(QtCore.QSize(571, 341))
        self.textBrowser_doc.setMaximumSize(QtCore.QSize(16777215, 611))
        self.textBrowser_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_doc.setObjectName(_fromUtf8("textBrowser_doc"))
        self.verticalLayout_13.addWidget(self.textBrowser_doc)
        self.tabWidget_medical.addTab(self.tab_documents, _fromUtf8(""))
        MainWindowConsultation.setCentralWidget(self.centralwidget)
        self.action_Recettes = QtGui.QAction(MainWindowConsultation)
        self.action_Recettes.setObjectName(_fromUtf8("action_Recettes"))
        self.actionD_penses = QtGui.QAction(MainWindowConsultation)
        self.actionD_penses.setObjectName(_fromUtf8("actionD_penses"))
        self.action_Banque = QtGui.QAction(MainWindowConsultation)
        self.action_Banque.setObjectName(_fromUtf8("action_Banque"))
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindowConsultation)
        self.actionRecoupement_bancaire.setObjectName(_fromUtf8("actionRecoupement_bancaire"))
        self.actionTVA = QtGui.QAction(MainWindowConsultation)
        self.actionTVA.setObjectName(_fromUtf8("actionTVA"))
        self.action2035 = QtGui.QAction(MainWindowConsultation)
        self.action2035.setObjectName(_fromUtf8("action2035"))
        self.actionCommandes = QtGui.QAction(MainWindowConsultation)
        self.actionCommandes.setObjectName(_fromUtf8("actionCommandes"))
        self.actionAnalyse = QtGui.QAction(MainWindowConsultation)
        self.actionAnalyse.setObjectName(_fromUtf8("actionAnalyse"))
        self.action_Facturation = QtGui.QAction(MainWindowConsultation)
        self.action_Facturation.setObjectName(_fromUtf8("action_Facturation"))
        self.actionBureau = QtGui.QAction(MainWindowConsultation)
        self.actionBureau.setObjectName(_fromUtf8("actionBureau"))
        self.action_M_dicaments = QtGui.QAction(MainWindowConsultation)
        self.action_M_dicaments.setObjectName(_fromUtf8("action_M_dicaments"))
        self.action_Pathologies = QtGui.QAction(MainWindowConsultation)
        self.action_Pathologies.setObjectName(_fromUtf8("action_Pathologies"))
        self.actionBackup = QtGui.QAction(MainWindowConsultation)
        self.actionBackup.setObjectName(_fromUtf8("actionBackup"))
        self.actionRestore = QtGui.QAction(MainWindowConsultation)
        self.actionRestore.setObjectName(_fromUtf8("actionRestore"))
        self.actionImport = QtGui.QAction(MainWindowConsultation)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionR_seau_S_curit = QtGui.QAction(MainWindowConsultation)
        self.actionR_seau_S_curit.setObjectName(_fromUtf8("actionR_seau_S_curit"))
        self.actionQuitter = QtGui.QAction(MainWindowConsultation)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.label_13.setBuddy(self.listView)
        self.label_14.setBuddy(self.dateTimeEdit_analyse)
        self.label_15.setBuddy(self.lineEdit_description)
        self.label_30.setBuddy(self.lineEdit_prelevement)
        self.label_31.setBuddy(self.textEdit_syntheseanalyse)
        self.label_32.setBuddy(self.textEdit_conclusions)
        self.label_RCP.setBuddy(self.textBrowser_medicament)
        self.label_medicament.setBuddy(self.comboBox_medicament)
        self.label_molecule.setBuddy(self.comboBox_molecule)
        self.label_posomol.setBuddy(self.lineEdit_posomol)
        self.label_presentation.setBuddy(self.comboBox_presentation)
        self.label_posomed.setBuddy(self.lineEdit_posomed)
        self.label_especeCible.setBuddy(self.comboBox_especeCible)
        self.label_33.setBuddy(self.dateEdit_ordonance)
        self.label_34.setBuddy(self.lineEdit_poids)
        self.label_doc.setBuddy(self.listView_doc)
        self.label_docFile.setBuddy(self.lineEdit_docFile)

        self.retranslateUi(MainWindowConsultation)
        self.tabWidget_medical.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowConsultation)

    def retranslateUi(self, MainWindowConsultation):
        MainWindowConsultation.setWindowTitle(_translate("MainWindowConsultation", "Open Vet", None))
        self.textBrowser_client.setToolTip(_translate("MainWindowConsultation", "Double click pour sélectionner l\'édition", None))
        self.toolButton_ClientInfo.setText(_translate("MainWindowConsultation", "...", None))
        self.textBrowser_animal.setToolTip(_translate("MainWindowConsultation", "Double click pour sélectionner l\'édition", None))
        self.toolButton_AnimalInfo.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_scan.setToolTip(_translate("MainWindowConsultation", "Recherche client / animal", None))
        self.toolButton_scan.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_addAnimal.setToolTip(_translate("MainWindowConsultation", "Nouvel animal", None))
        self.toolButton_addAnimal.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_editClient.setToolTip(_translate("MainWindowConsultation", "Modifie client", None))
        self.toolButton_editClient.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_deleteAnimal.setToolTip(_translate("MainWindowConsultation", "Efface animal", None))
        self.toolButton_deleteAnimal.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_deleteClient.setToolTip(_translate("MainWindowConsultation", "Efface client", None))
        self.toolButton_deleteClient.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_addClient.setToolTip(_translate("MainWindowConsultation", "Nouveau client", None))
        self.toolButton_addClient.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_editAnimal.setToolTip(_translate("MainWindowConsultation", "Modifie animal", None))
        self.toolButton_editAnimal.setText(_translate("MainWindowConsultation", "...", None))
        self.button_vacciner.setToolTip(_translate("MainWindowConsultation", "Ajouter ce vaccin dans le dossier", None))
        self.button_vacciner.setText(_translate("MainWindowConsultation", "Vacciner", None))
        self.label_vaccinerStart.setText(_translate("MainWindowConsultation", "Le :", None))
        self.comboBox_rappel.setToolTip(_translate("MainWindowConsultation", "Période de rappel", None))
        self.dateEdit_vacciner_end.setToolTip(_translate("MainWindowConsultation", "Date de rappel", None))
        self.dateEdit_vacciner_start.setToolTip(_translate("MainWindowConsultation", "Date de vaccination", None))
        self.label_23.setText(_translate("MainWindowConsultation", "Rappel :", None))
        self.comboBox_vacciner.setToolTip(_translate("MainWindowConsultation", "Vaccin", None))
        self.label_17.setText(_translate("MainWindowConsultation", "Le :", None))
        self.dateEdit_consult.setToolTip(_translate("MainWindowConsultation", "Date de consultation", None))
        self.dateEdit_consult.setDisplayFormat(_translate("MainWindowConsultation", "dd/MM/yyyy", None))
        self.label_24.setText(_translate("MainWindowConsultation", "Vétérinaire :", None))
        self.comboBox_veterinaire.setToolTip(_translate("MainWindowConsultation", "Vétérinaire consultant", None))
        self.label_25.setText(_translate("MainWindowConsultation", "   Type :", None))
        self.comboBox_consultType.setToolTip(_translate("MainWindowConsultation", "Choir le type dominant de la consultation", None))
        self.label_Referant.setText(_translate("MainWindowConsultation", "Référant :", None))
        self.comboBox_Referant.setToolTip(_translate("MainWindowConsultation", "Choisir un vétérinaire référant", None))
        self.label_26.setText(_translate("MainWindowConsultation", "Domaine Pathologique :", None))
        self.comboBox_PathologieDomaine.setToolTip(_translate("MainWindowConsultation", "Domaine pathologique dominant de la consultation", None))
        self.label_Pathologie.setText(_translate("MainWindowConsultation", "Pathologie :", None))
        self.comboBox_Pathologie.setToolTip(_translate("MainWindowConsultation", "Choisir une Pathologie Dominante pour cette Consultation", None))
        self.toolButton_Pathologie.setToolTip(_translate("MainWindowConsultation", "Accès au formulaire de pathologie", None))
        self.toolButton_Pathologie.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_comment.setText(_translate("MainWindowConsultation", "...", None))
        self.label_27.setText(_translate("MainWindowConsultation", "Observations :", None))
        self.textEdit_consultObs.setToolTip(_translate("MainWindowConsultation", "Insérer les observations cliniques", None))
        self.label_28.setText(_translate("MainWindowConsultation", "Traitements :", None))
        self.textEdit_consultTrait.setToolTip(_translate("MainWindowConsultation", "Inserez les traitements", None))
        self.pushButton_valider.setToolTip(_translate("MainWindowConsultation", "Enregistrer cette consultation", None))
        self.pushButton_valider.setText(_translate("MainWindowConsultation", "Valider", None))
        self.pushButton_Nouveau.setToolTip(_translate("MainWindowConsultation", "Nouvelle Consultation", None))
        self.pushButton_Nouveau.setText(_translate("MainWindowConsultation", "Nouveau", None))
        self.pushButton_Hospit.setToolTip(_translate("MainWindowConsultation", "Imprimer la fiche d\'hospitalisation", None))
        self.pushButton_Hospit.setText(_translate("MainWindowConsultation", "Hospitalisation", None))
        self.pushButton_Facturation.setToolTip(_translate("MainWindowConsultation", "Basculer en facturation", None))
        self.pushButton_Facturation.setText(_translate("MainWindowConsultation", "Facturation", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_consulation), _translate("MainWindowConsultation", "Consultation", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_vaccins), _translate("MainWindowConsultation", "Vaccinations", None))
        self.toolButton_fichier.setText(_translate("MainWindowConsultation", "...", None))
        self.pushButton_addImage.setToolTip(_translate("MainWindowConsultation", "Ajouter une nouvelle image à l\'examen", None))
        self.pushButton_addImage.setText(_translate("MainWindowConsultation", "Ajouter image", None))
        self.label_12.setText(_translate("MainWindowConsultation", "Type d\'analyse :  ", None))
        self.label_13.setText(_translate("MainWindowConsultation", "Analyses précédentes", None))
        self.listView.setStatusTip(_translate("MainWindowConsultation", "Double click pour éditer l\'analyse", None))
        self.label_14.setText(_translate("MainWindowConsultation", "Date Heure :  ", None))
        self.dateTimeEdit_analyse.setDisplayFormat(_translate("MainWindowConsultation", "dd/MM/yyyy HH:mm", None))
        self.label_15.setText(_translate("MainWindowConsultation", "Description de l\'analyse:", None))
        self.label_30.setText(_translate("MainWindowConsultation", "Prélèvement :", None))
        self.label_31.setText(_translate("MainWindowConsultation", "Observations :", None))
        self.label_32.setText(_translate("MainWindowConsultation", "Conclusions :", None))
        self.pushButton_valide.setToolTip(_translate("MainWindowConsultation", "Ajouter l\'analyse au dossier", None))
        self.pushButton_valide.setText(_translate("MainWindowConsultation", "Valider", None))
        self.toolButton_AddTypeAnalyse.setToolTip(_translate("MainWindowConsultation", "AJouter des types d\'analyses", None))
        self.toolButton_AddTypeAnalyse.setText(_translate("MainWindowConsultation", "...", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_analyses), _translate("MainWindowConsultation", "Analyses", None))
        self.label_RCP.setText(_translate("MainWindowConsultation", "Mentions légales :", None))
        self.toolButton_3.setToolTip(_translate("MainWindowConsultation", "Texte complet", None))
        self.toolButton_3.setText(_translate("MainWindowConsultation", "...", None))
        self.toolButton_4.setToolTip(_translate("MainWindowConsultation", "Résumé", None))
        self.toolButton_4.setText(_translate("MainWindowConsultation", "...", None))
        self.label_medicament.setText(_translate("MainWindowConsultation", "Médicament :", None))
        self.label_molecule.setText(_translate("MainWindowConsultation", "Molécule :", None))
        self.label_posomol.setText(_translate("MainWindowConsultation", "Posologie de principe actif :", None))
        self.label_presentation.setText(_translate("MainWindowConsultation", "Présentation :", None))
        self.label_posomed.setText(_translate("MainWindowConsultation", "Posologie de médicament :", None))
        self.label_especeCible.setText(_translate("MainWindowConsultation", "Espèce cible :", None))
        self.pushButton_validOrdonnance.setText(_translate("MainWindowConsultation", "Valider", None))
        self.pushButton_CalculPoso.setText(_translate("MainWindowConsultation", "Calculatrice", None))
        self.pushButton_DMV.setText(_translate("MainWindowConsultation", "Editer DMV", None))
        self.label_33.setText(_translate("MainWindowConsultation", "Le :", None))
        self.dateEdit_ordonance.setDisplayFormat(_translate("MainWindowConsultation", "dd/MM/yyyy", None))
        self.label_34.setText(_translate("MainWindowConsultation", "Poids :", None))
        self.pushButton_OrdonnanceValid.setText(_translate("MainWindowConsultation", "Valider", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_ordonnances), _translate("MainWindowConsultation", "Ordonnances", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_planTherapeutique), _translate("MainWindowConsultation", "Plan Thérapeutique", None))
        self.label_doc.setText(_translate("MainWindowConsultation", "Documents disponibles :", None))
        self.label_docDate.setText(_translate("MainWindowConsultation", "Date :", None))
        self.dateEdit_docDate.setDisplayFormat(_translate("MainWindowConsultation", "dd/MM/yyyy", None))
        self.label_docFile.setText(_translate("MainWindowConsultation", "Fichier :", None))
        self.toolButton_docFile.setToolTip(_translate("MainWindowConsultation", "Selectionner un fichier", None))
        self.toolButton_docFile.setText(_translate("MainWindowConsultation", "...", None))
        self.pushButton_docAdd.setToolTip(_translate("MainWindowConsultation", "Ajouter nouveau document au dossier", None))
        self.pushButton_docAdd.setText(_translate("MainWindowConsultation", "Ajouter", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_documents), _translate("MainWindowConsultation", "Documents", None))
        self.action_Recettes.setText(_translate("MainWindowConsultation", "&Recettes", None))
        self.actionD_penses.setText(_translate("MainWindowConsultation", "&Dépenses", None))
        self.action_Banque.setText(_translate("MainWindowConsultation", "&Banque", None))
        self.actionRecoupement_bancaire.setText(_translate("MainWindowConsultation", "Recoupement bancaire", None))
        self.actionTVA.setText(_translate("MainWindowConsultation", "TVA", None))
        self.action2035.setText(_translate("MainWindowConsultation", "2035", None))
        self.actionCommandes.setText(_translate("MainWindowConsultation", "&Commandes", None))
        self.actionAnalyse.setText(_translate("MainWindowConsultation", "Visualisation", None))
        self.action_Facturation.setText(_translate("MainWindowConsultation", "&Facturation", None))
        self.actionBureau.setText(_translate("MainWindowConsultation", "Bureau", None))
        self.actionBureau.setShortcut(_translate("MainWindowConsultation", "Ctrl+Alt+B", None))
        self.action_M_dicaments.setText(_translate("MainWindowConsultation", "&Médicaments", None))
        self.action_Pathologies.setText(_translate("MainWindowConsultation", "&Pathologies", None))
        self.actionBackup.setText(_translate("MainWindowConsultation", "Backup", None))
        self.actionRestore.setText(_translate("MainWindowConsultation", "Restore", None))
        self.actionImport.setText(_translate("MainWindowConsultation", "Import", None))
        self.actionR_seau_S_curit.setText(_translate("MainWindowConsultation", "Réseau/Sécurité", None))
        self.actionQuitter.setText(_translate("MainWindowConsultation", "Quitter", None))
        self.actionQuitter.setToolTip(_translate("MainWindowConsultation", "Quitter l\'application", None))
        self.actionQuitter.setShortcut(_translate("MainWindowConsultation", "Ctrl+Q", None))

from Mywidgets import MyComboBox
import resources_rc
