# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './oldForm_consultation.ui'
#
# Created: Mon May  5 12:27:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tabWidget_medical(object):
    def setupUi(self, tabWidget_medical):
        tabWidget_medical.setObjectName(_fromUtf8("tabWidget_medical"))
        tabWidget_medical.resize(1024, 521)
        self.tab_consulation = QtGui.QWidget()
        self.tab_consulation.setObjectName(_fromUtf8("tab_consulation"))
        self.splitter = QtGui.QSplitter(self.tab_consulation)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1018, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_med_sup = QtGui.QFrame(self.splitter)
        self.frame_med_sup.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_med_sup.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_sup.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_sup.setObjectName(_fromUtf8("frame_med_sup"))
        self.tableWidget_vacciner = QtGui.QTableWidget(self.frame_med_sup)
        self.tableWidget_vacciner.setGeometry(QtCore.QRect(690, 10, 311, 121))
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setObjectName(_fromUtf8("tableWidget_vacciner"))
        self.tableWidget_vacciner.verticalHeader().setVisible(False)
        self.button_vacciner = QtGui.QPushButton(self.frame_med_sup)
        self.button_vacciner.setGeometry(QtCore.QRect(910, 230, 93, 27))
        self.button_vacciner.setObjectName(_fromUtf8("button_vacciner"))
        self.dateEdit_vacciner_start = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_start.setGeometry(QtCore.QRect(750, 140, 101, 27))
        self.dateEdit_vacciner_start.setCalendarPopup(True)
        self.dateEdit_vacciner_start.setObjectName(_fromUtf8("dateEdit_vacciner_start"))
        self.dateEdit_vacciner_end = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_end.setGeometry(QtCore.QRect(900, 180, 101, 27))
        self.dateEdit_vacciner_end.setCalendarPopup(True)
        self.dateEdit_vacciner_end.setObjectName(_fromUtf8("dateEdit_vacciner_end"))
        self.comboBox_vacciner = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_vacciner.setGeometry(QtCore.QRect(900, 140, 101, 27))
        self.comboBox_vacciner.setObjectName(_fromUtf8("comboBox_vacciner"))
        self.comboBox_rappel = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_rappel.setGeometry(QtCore.QRect(750, 180, 141, 27))
        self.comboBox_rappel.setObjectName(_fromUtf8("comboBox_rappel"))
        self.label_2 = QtGui.QLabel(self.frame_med_sup)
        self.label_2.setGeometry(QtCore.QRect(690, 190, 62, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_vaccinerStart = QtGui.QLabel(self.frame_med_sup)
        self.label_vaccinerStart.setGeometry(QtCore.QRect(690, 150, 31, 17))
        self.label_vaccinerStart.setObjectName(_fromUtf8("label_vaccinerStart"))
        self.textBrowser_consultations = QtGui.QTextBrowser(self.frame_med_sup)
        self.textBrowser_consultations.setGeometry(QtCore.QRect(10, 10, 671, 401))
        self.textBrowser_consultations.setStyleSheet(_fromUtf8("background-position: right; background-image:  url(:/newPrefix/images/openvet.png);background-repeat: no-repeat; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.textBrowser_consultations.setObjectName(_fromUtf8("textBrowser_consultations"))
        self.frame_med_inf = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_med_inf.sizePolicy().hasHeightForWidth())
        self.frame_med_inf.setSizePolicy(sizePolicy)
        self.frame_med_inf.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_med_inf.setStyleSheet(_fromUtf8(""))
        self.frame_med_inf.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_inf.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_inf.setObjectName(_fromUtf8("frame_med_inf"))
        self.layoutWidget = QtGui.QWidget(self.frame_med_inf)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 993, 246))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(25, 27))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.dateEdit_consult = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_consult.sizePolicy().hasHeightForWidth())
        self.dateEdit_consult.setSizePolicy(sizePolicy)
        self.dateEdit_consult.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_consult.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dateEdit_consult.setCalendarPopup(True)
        self.dateEdit_consult.setObjectName(_fromUtf8("dateEdit_consult"))
        self.horizontalLayout.addWidget(self.dateEdit_consult)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(82, 0))
        self.label.setMaximumSize(QtCore.QSize(82, 27))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_veterinaire = MyComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_veterinaire.sizePolicy().hasHeightForWidth())
        self.comboBox_veterinaire.setSizePolicy(sizePolicy)
        self.comboBox_veterinaire.setMinimumSize(QtCore.QSize(200, 27))
        self.comboBox_veterinaire.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_veterinaire.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_veterinaire.setEditable(True)
        self.comboBox_veterinaire.setFrame(True)
        self.comboBox_veterinaire.setObjectName(_fromUtf8("comboBox_veterinaire"))
        self.horizontalLayout.addWidget(self.comboBox_veterinaire)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(50, 27))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.comboBox_consultType = MyComboBox(self.layoutWidget)
        self.comboBox_consultType.setMinimumSize(QtCore.QSize(160, 27))
        self.comboBox_consultType.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_consultType.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_consultType.setObjectName(_fromUtf8("comboBox_consultType"))
        self.horizontalLayout.addWidget(self.comboBox_consultType)
        self.label_Referant = QtGui.QLabel(self.layoutWidget)
        self.label_Referant.setMaximumSize(QtCore.QSize(63, 27))
        self.label_Referant.setObjectName(_fromUtf8("label_Referant"))
        self.horizontalLayout.addWidget(self.label_Referant)
        self.comboBox_Referant = MyComboBox(self.layoutWidget)
        self.comboBox_Referant.setMinimumSize(QtCore.QSize(181, 27))
        self.comboBox_Referant.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Referant.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Referant.setEditable(True)
        self.comboBox_Referant.setObjectName(_fromUtf8("comboBox_Referant"))
        self.horizontalLayout.addWidget(self.comboBox_Referant)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(160, 27))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBox_PathologieDomaine = MyComboBox(self.layoutWidget)
        self.comboBox_PathologieDomaine.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_PathologieDomaine.setMaximumSize(QtCore.QSize(200, 27))
        self.comboBox_PathologieDomaine.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_PathologieDomaine.setObjectName(_fromUtf8("comboBox_PathologieDomaine"))
        self.horizontalLayout_7.addWidget(self.comboBox_PathologieDomaine)
        self.label_Pathologie = QtGui.QLabel(self.layoutWidget)
        self.label_Pathologie.setMinimumSize(QtCore.QSize(81, 0))
        self.label_Pathologie.setMaximumSize(QtCore.QSize(81, 27))
        self.label_Pathologie.setObjectName(_fromUtf8("label_Pathologie"))
        self.horizontalLayout_7.addWidget(self.label_Pathologie)
        self.comboBox_Pathologie = MyComboBox(self.layoutWidget)
        self.comboBox_Pathologie.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox_Pathologie.setMaximumSize(QtCore.QSize(261, 27))
        self.comboBox_Pathologie.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Pathologie.setEditable(False)
        self.comboBox_Pathologie.setObjectName(_fromUtf8("comboBox_Pathologie"))
        self.horizontalLayout_7.addWidget(self.comboBox_Pathologie)
        self.toolButton_Pathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_Pathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_Pathologie.setMaximumSize(QtCore.QSize(27, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/pathologie.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Pathologie.setIcon(icon)
        self.toolButton_Pathologie.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Pathologie.setObjectName(_fromUtf8("toolButton_Pathologie"))
        self.horizontalLayout_7.addWidget(self.toolButton_Pathologie)
        self.toolButton_comment = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_comment.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setMaximumSize(QtCore.QSize(27, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_comment.setIcon(icon1)
        self.toolButton_comment.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_comment.setObjectName(_fromUtf8("toolButton_comment"))
        self.horizontalLayout_7.addWidget(self.toolButton_comment)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.textEdit_consultObs = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultObs.sizePolicy().hasHeightForWidth())
        self.textEdit_consultObs.setSizePolicy(sizePolicy)
        self.textEdit_consultObs.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultObs.setMaximumSize(QtCore.QSize(16777215, 111))
        self.textEdit_consultObs.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultObs.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_consultObs.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit_consultObs.setObjectName(_fromUtf8("textEdit_consultObs"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit_consultObs)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.textEdit_consultTrait = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultTrait.sizePolicy().hasHeightForWidth())
        self.textEdit_consultTrait.setSizePolicy(sizePolicy)
        self.textEdit_consultTrait.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultTrait.setMaximumSize(QtCore.QSize(16777215, 51))
        self.textEdit_consultTrait.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultTrait.setObjectName(_fromUtf8("textEdit_consultTrait"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEdit_consultTrait)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_valider = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_valider.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.verticalLayout.addWidget(self.pushButton_valider)
        self.pushButton_Nouveau = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Nouveau.setObjectName(_fromUtf8("pushButton_Nouveau"))
        self.verticalLayout.addWidget(self.pushButton_Nouveau)
        self.pushButton_Hospit = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Hospit.setObjectName(_fromUtf8("pushButton_Hospit"))
        self.verticalLayout.addWidget(self.pushButton_Hospit)
        self.pushButton_Facturation = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Facturation.setObjectName(_fromUtf8("pushButton_Facturation"))
        self.verticalLayout.addWidget(self.pushButton_Facturation)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        tabWidget_medical.addTab(self.tab_consulation, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        tabWidget_medical.addTab(self.tab, _fromUtf8(""))
        self.tab_analyses = QtGui.QWidget()
        self.tab_analyses.setObjectName(_fromUtf8("tab_analyses"))
        self.tableWidget_analyses = QtGui.QTableWidget(self.tab_analyses)
        self.tableWidget_analyses.setEnabled(True)
        self.tableWidget_analyses.setGeometry(QtCore.QRect(650, 70, 350, 241))
        self.tableWidget_analyses.setShowGrid(True)
        self.tableWidget_analyses.setRowCount(16)
        self.tableWidget_analyses.setColumnCount(4)
        self.tableWidget_analyses.setObjectName(_fromUtf8("tableWidget_analyses"))
        self.tableWidget_analyses.verticalHeader().setVisible(False)
        self.listWidget_analyse = QtGui.QListWidget(self.tab_analyses)
        self.listWidget_analyse.setGeometry(QtCore.QRect(650, 60, 351, 192))
        self.listWidget_analyse.setObjectName(_fromUtf8("listWidget_analyse"))
        self.lineEdit_titreImage = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_titreImage.setGeometry(QtCore.QRect(650, 340, 311, 27))
        self.lineEdit_titreImage.setObjectName(_fromUtf8("lineEdit_titreImage"))
        self.lineEdit_fichier = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_fichier.setGeometry(QtCore.QRect(650, 390, 311, 27))
        self.lineEdit_fichier.setObjectName(_fromUtf8("lineEdit_fichier"))
        self.toolButton_fichier = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_fichier.setGeometry(QtCore.QRect(970, 390, 26, 25))
        self.toolButton_fichier.setObjectName(_fromUtf8("toolButton_fichier"))
        self.pushButton_addImage = QtGui.QPushButton(self.tab_analyses)
        self.pushButton_addImage.setGeometry(QtCore.QRect(760, 430, 111, 27))
        self.pushButton_addImage.setObjectName(_fromUtf8("pushButton_addImage"))
        self.line = QtGui.QFrame(self.tab_analyses)
        self.line.setGeometry(QtCore.QRect(620, 30, 20, 420))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_analyses)
        self.line_2.setGeometry(QtCore.QRect(270, 30, 20, 420))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_5 = QtGui.QLabel(self.tab_analyses)
        self.label_5.setGeometry(QtCore.QRect(660, 11, 113, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_typeanalyse = QtGui.QComboBox(self.tab_analyses)
        self.comboBox_typeanalyse.setGeometry(QtCore.QRect(780, 10, 181, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_typeanalyse.sizePolicy().hasHeightForWidth())
        self.comboBox_typeanalyse.setSizePolicy(sizePolicy)
        self.comboBox_typeanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_typeanalyse.setObjectName(_fromUtf8("comboBox_typeanalyse"))
        self.label_3 = QtGui.QLabel(self.tab_analyses)
        self.label_3.setGeometry(QtCore.QRect(50, 12, 171, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listView = QtGui.QListView(self.tab_analyses)
        self.listView.setGeometry(QtCore.QRect(18, 37, 239, 410))
        self.listView.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget_2.setGeometry(QtCore.QRect(303, 12, 303, 438))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_analyse = QtGui.QDateTimeEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_analyse.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_analyse.setSizePolicy(sizePolicy)
        self.dateTimeEdit_analyse.setMinimumSize(QtCore.QSize(156, 27))
        self.dateTimeEdit_analyse.setCalendarPopup(True)
        self.dateTimeEdit_analyse.setObjectName(_fromUtf8("dateTimeEdit_analyse"))
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_analyse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_description = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_description.sizePolicy().hasHeightForWidth())
        self.lineEdit_description.setSizePolicy(sizePolicy)
        self.lineEdit_description.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_description.setObjectName(_fromUtf8("lineEdit_description"))
        self.verticalLayout_2.addWidget(self.lineEdit_description)
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.lineEdit_prelevement = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prelevement.sizePolicy().hasHeightForWidth())
        self.lineEdit_prelevement.setSizePolicy(sizePolicy)
        self.lineEdit_prelevement.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_prelevement.setObjectName(_fromUtf8("lineEdit_prelevement"))
        self.verticalLayout_2.addWidget(self.lineEdit_prelevement)
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.textEdit_syntheseanalyse = QtGui.QTextEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_syntheseanalyse.sizePolicy().hasHeightForWidth())
        self.textEdit_syntheseanalyse.setSizePolicy(sizePolicy)
        self.textEdit_syntheseanalyse.setMinimumSize(QtCore.QSize(301, 120))
        self.textEdit_syntheseanalyse.setMaximumSize(QtCore.QSize(16777215, 141))
        self.textEdit_syntheseanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_syntheseanalyse.setAutoFillBackground(False)
        self.textEdit_syntheseanalyse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_syntheseanalyse.setObjectName(_fromUtf8("textEdit_syntheseanalyse"))
        self.verticalLayout_2.addWidget(self.textEdit_syntheseanalyse)
        self.label_9 = QtGui.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.textEdit_conclusions = QtGui.QTextEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_conclusions.sizePolicy().hasHeightForWidth())
        self.textEdit_conclusions.setSizePolicy(sizePolicy)
        self.textEdit_conclusions.setMinimumSize(QtCore.QSize(301, 0))
        self.textEdit_conclusions.setMaximumSize(QtCore.QSize(16777215, 61))
        self.textEdit_conclusions.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_conclusions.setObjectName(_fromUtf8("textEdit_conclusions"))
        self.verticalLayout_2.addWidget(self.textEdit_conclusions)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_valide = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_valide.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_valide.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_valide.setObjectName(_fromUtf8("pushButton_valide"))
        self.horizontalLayout_6.addWidget(self.pushButton_valide)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.toolButton_AddTypeAnalyse = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_AddTypeAnalyse.setGeometry(QtCore.QRect(970, 10, 26, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/add1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AddTypeAnalyse.setIcon(icon2)
        self.toolButton_AddTypeAnalyse.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_AddTypeAnalyse.setObjectName(_fromUtf8("toolButton_AddTypeAnalyse"))
        tabWidget_medical.addTab(self.tab_analyses, _fromUtf8(""))
        self.tab_ordonnances = QtGui.QWidget()
        self.tab_ordonnances.setObjectName(_fromUtf8("tab_ordonnances"))
        self.textBrowser_medicament = QtGui.QTextBrowser(self.tab_ordonnances)
        self.textBrowser_medicament.setGeometry(QtCore.QRect(540, 220, 451, 231))
        self.textBrowser_medicament.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_medicament.setObjectName(_fromUtf8("textBrowser_medicament"))
        self.label_RCP = QtGui.QLabel(self.tab_ordonnances)
        self.label_RCP.setGeometry(QtCore.QRect(540, 200, 131, 17))
        self.label_RCP.setObjectName(_fromUtf8("label_RCP"))
        self.line_3 = QtGui.QFrame(self.tab_ordonnances)
        self.line_3.setGeometry(QtCore.QRect(515, 20, 20, 501))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.toolButton = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton.setGeometry(QtCore.QRect(960, 190, 26, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_2.setGeometry(QtCore.QRect(920, 190, 26, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_abst.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_3.setGeometry(QtCore.QRect(543, 10, 451, 176))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_medicament = QtGui.QLabel(self.layoutWidget_3)
        self.label_medicament.setObjectName(_fromUtf8("label_medicament"))
        self.gridLayout.addWidget(self.label_medicament, 0, 0, 1, 1)
        self.label_molecule = QtGui.QLabel(self.layoutWidget_3)
        self.label_molecule.setObjectName(_fromUtf8("label_molecule"))
        self.gridLayout.addWidget(self.label_molecule, 0, 1, 1, 1)
        self.comboBox_medicament = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_medicament.sizePolicy().hasHeightForWidth())
        self.comboBox_medicament.setSizePolicy(sizePolicy)
        self.comboBox_medicament.setObjectName(_fromUtf8("comboBox_medicament"))
        self.gridLayout.addWidget(self.comboBox_medicament, 1, 0, 1, 1)
        self.comboBox_molecule = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_molecule.sizePolicy().hasHeightForWidth())
        self.comboBox_molecule.setSizePolicy(sizePolicy)
        self.comboBox_molecule.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_molecule.setObjectName(_fromUtf8("comboBox_molecule"))
        self.gridLayout.addWidget(self.comboBox_molecule, 1, 1, 1, 1)
        self.label_posomol = QtGui.QLabel(self.layoutWidget_3)
        self.label_posomol.setObjectName(_fromUtf8("label_posomol"))
        self.gridLayout.addWidget(self.label_posomol, 2, 0, 1, 1)
        self.label_presentation = QtGui.QLabel(self.layoutWidget_3)
        self.label_presentation.setObjectName(_fromUtf8("label_presentation"))
        self.gridLayout.addWidget(self.label_presentation, 2, 1, 1, 1)
        self.lineEdit_posomol = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomol.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomol.setSizePolicy(sizePolicy)
        self.lineEdit_posomol.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomol.setObjectName(_fromUtf8("lineEdit_posomol"))
        self.gridLayout.addWidget(self.lineEdit_posomol, 3, 0, 1, 1)
        self.comboBox_presentation = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBox_presentation.setObjectName(_fromUtf8("comboBox_presentation"))
        self.gridLayout.addWidget(self.comboBox_presentation, 3, 1, 1, 1)
        self.label_posomed = QtGui.QLabel(self.layoutWidget_3)
        self.label_posomed.setObjectName(_fromUtf8("label_posomed"))
        self.gridLayout.addWidget(self.label_posomed, 4, 0, 1, 1)
        self.label_especeCible = QtGui.QLabel(self.layoutWidget_3)
        self.label_especeCible.setObjectName(_fromUtf8("label_especeCible"))
        self.gridLayout.addWidget(self.label_especeCible, 4, 1, 1, 1)
        self.lineEdit_posomed = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomed.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomed.setSizePolicy(sizePolicy)
        self.lineEdit_posomed.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomed.setObjectName(_fromUtf8("lineEdit_posomed"))
        self.gridLayout.addWidget(self.lineEdit_posomed, 5, 0, 1, 1)
        self.comboBox_especeCible = QtGui.QComboBox(self.layoutWidget_3)
        self.comboBox_especeCible.setObjectName(_fromUtf8("comboBox_especeCible"))
        self.gridLayout.addWidget(self.comboBox_especeCible, 5, 1, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_4.setGeometry(QtCore.QRect(540, 490, 451, 29))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_validOrdonnance = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_validOrdonnance.setObjectName(_fromUtf8("pushButton_validOrdonnance"))
        self.horizontalLayout_4.addWidget(self.pushButton_validOrdonnance)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_CalculPoso = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_CalculPoso.setObjectName(_fromUtf8("pushButton_CalculPoso"))
        self.horizontalLayout_4.addWidget(self.pushButton_CalculPoso)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_DMV = QtGui.QPushButton(self.layoutWidget_4)
        self.pushButton_DMV.setObjectName(_fromUtf8("pushButton_DMV"))
        self.horizontalLayout_4.addWidget(self.pushButton_DMV)
        self.layoutWidget_5 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget_5.setGeometry(QtCore.QRect(11, 31, 512, 387))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.dateEdit_ordonance = QtGui.QDateEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ordonance.sizePolicy().hasHeightForWidth())
        self.dateEdit_ordonance.setSizePolicy(sizePolicy)
        self.dateEdit_ordonance.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_ordonance.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_ordonance.setCalendarPopup(True)
        self.dateEdit_ordonance.setObjectName(_fromUtf8("dateEdit_ordonance"))
        self.horizontalLayout_3.addWidget(self.dateEdit_ordonance)
        spacerItem2 = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_11 = QtGui.QLabel(self.layoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lineEdit_poids = QtGui.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_poids.sizePolicy().hasHeightForWidth())
        self.lineEdit_poids.setSizePolicy(sizePolicy)
        self.lineEdit_poids.setMinimumSize(QtCore.QSize(66, 27))
        self.lineEdit_poids.setObjectName(_fromUtf8("lineEdit_poids"))
        self.horizontalLayout_3.addWidget(self.lineEdit_poids)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(496, 391))
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.pushButton_OrdonnanceValid = QtGui.QPushButton(self.tab_ordonnances)
        self.pushButton_OrdonnanceValid.setGeometry(QtCore.QRect(200, 430, 93, 27))
        self.pushButton_OrdonnanceValid.setObjectName(_fromUtf8("pushButton_OrdonnanceValid"))
        tabWidget_medical.addTab(self.tab_ordonnances, _fromUtf8(""))
        self.tab_planTherapeutique = QtGui.QWidget()
        self.tab_planTherapeutique.setObjectName(_fromUtf8("tab_planTherapeutique"))
        tabWidget_medical.addTab(self.tab_planTherapeutique, _fromUtf8(""))
        self.tab_documents = QtGui.QWidget()
        self.tab_documents.setObjectName(_fromUtf8("tab_documents"))
        self.listView_doc = QtGui.QListView(self.tab_documents)
        self.listView_doc.setGeometry(QtCore.QRect(20, 90, 241, 341))
        self.listView_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView_doc.setObjectName(_fromUtf8("listView_doc"))
        self.label_doc = QtGui.QLabel(self.tab_documents)
        self.label_doc.setGeometry(QtCore.QRect(10, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_doc.setFont(font)
        self.label_doc.setTextFormat(QtCore.Qt.PlainText)
        self.label_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doc.setObjectName(_fromUtf8("label_doc"))
        self.layoutWidget_6 = QtGui.QWidget(self.tab_documents)
        self.layoutWidget_6.setGeometry(QtCore.QRect(320, 52, 631, 378))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_docDate = QtGui.QLabel(self.layoutWidget_6)
        self.label_docDate.setObjectName(_fromUtf8("label_docDate"))
        self.horizontalLayout_5.addWidget(self.label_docDate)
        self.dateEdit_docDate = QtGui.QDateEdit(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_docDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_docDate.setSizePolicy(sizePolicy)
        self.dateEdit_docDate.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_docDate.setCalendarPopup(True)
        self.dateEdit_docDate.setObjectName(_fromUtf8("dateEdit_docDate"))
        self.horizontalLayout_5.addWidget(self.dateEdit_docDate)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_docFile = QtGui.QLabel(self.layoutWidget_6)
        self.label_docFile.setObjectName(_fromUtf8("label_docFile"))
        self.horizontalLayout_5.addWidget(self.label_docFile)
        self.lineEdit_docFile = QtGui.QLineEdit(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_docFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_docFile.setSizePolicy(sizePolicy)
        self.lineEdit_docFile.setMinimumSize(QtCore.QSize(212, 27))
        self.lineEdit_docFile.setObjectName(_fromUtf8("lineEdit_docFile"))
        self.horizontalLayout_5.addWidget(self.lineEdit_docFile)
        self.toolButton_docFile = QtGui.QToolButton(self.layoutWidget_6)
        self.toolButton_docFile.setObjectName(_fromUtf8("toolButton_docFile"))
        self.horizontalLayout_5.addWidget(self.toolButton_docFile)
        self.pushButton_docAdd = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButton_docAdd.setObjectName(_fromUtf8("pushButton_docAdd"))
        self.horizontalLayout_5.addWidget(self.pushButton_docAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.textBrowser_doc = QtGui.QTextBrowser(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_doc.sizePolicy().hasHeightForWidth())
        self.textBrowser_doc.setSizePolicy(sizePolicy)
        self.textBrowser_doc.setMinimumSize(QtCore.QSize(571, 341))
        self.textBrowser_doc.setMaximumSize(QtCore.QSize(16777215, 611))
        self.textBrowser_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_doc.setObjectName(_fromUtf8("textBrowser_doc"))
        self.verticalLayout_3.addWidget(self.textBrowser_doc)
        tabWidget_medical.addTab(self.tab_documents, _fromUtf8(""))
        self.label_2.setBuddy(self.comboBox_rappel)
        self.label_vaccinerStart.setBuddy(self.dateEdit_vacciner_start)
        self.label_13.setBuddy(self.dateEdit_consult)
        self.label.setBuddy(self.comboBox_veterinaire)
        self.label_12.setBuddy(self.comboBox_consultType)
        self.label_Referant.setBuddy(self.comboBox_Referant)
        self.label_3.setBuddy(self.listView)
        self.label_4.setBuddy(self.dateTimeEdit_analyse)
        self.label_6.setBuddy(self.lineEdit_description)
        self.label_7.setBuddy(self.lineEdit_prelevement)
        self.label_8.setBuddy(self.textEdit_syntheseanalyse)
        self.label_9.setBuddy(self.textEdit_conclusions)
        self.label_RCP.setBuddy(self.textBrowser_medicament)
        self.label_medicament.setBuddy(self.comboBox_medicament)
        self.label_molecule.setBuddy(self.comboBox_molecule)
        self.label_posomol.setBuddy(self.lineEdit_posomol)
        self.label_presentation.setBuddy(self.comboBox_presentation)
        self.label_posomed.setBuddy(self.lineEdit_posomed)
        self.label_especeCible.setBuddy(self.comboBox_especeCible)
        self.label_10.setBuddy(self.dateEdit_ordonance)
        self.label_11.setBuddy(self.lineEdit_poids)
        self.label_doc.setBuddy(self.listView_doc)
        self.label_docFile.setBuddy(self.lineEdit_docFile)

        self.retranslateUi(tabWidget_medical)
        tabWidget_medical.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabWidget_medical)

    def retranslateUi(self, tabWidget_medical):
        self.button_vacciner.setToolTip(_translate("tabWidget_medical", "Ajouter ce vaccin dans le dossier", None))
        self.button_vacciner.setText(_translate("tabWidget_medical", "Vacciner", None))
        self.dateEdit_vacciner_start.setToolTip(_translate("tabWidget_medical", "Date de vaccination", None))
        self.dateEdit_vacciner_end.setToolTip(_translate("tabWidget_medical", "Date de rappel", None))
        self.comboBox_vacciner.setToolTip(_translate("tabWidget_medical", "Vaccin", None))
        self.comboBox_rappel.setToolTip(_translate("tabWidget_medical", "Période de rappel", None))
        self.label_2.setText(_translate("tabWidget_medical", "Rappel :", None))
        self.label_vaccinerStart.setText(_translate("tabWidget_medical", "Le :", None))
        self.frame_med_inf.setToolTip(_translate("tabWidget_medical", "Ajouter un commentaire", None))
        self.label_13.setText(_translate("tabWidget_medical", "Le :", None))
        self.dateEdit_consult.setToolTip(_translate("tabWidget_medical", "Date de consultation", None))
        self.dateEdit_consult.setDisplayFormat(_translate("tabWidget_medical", "dd/MM/yyyy", None))
        self.label.setText(_translate("tabWidget_medical", "Vétérinaire :", None))
        self.comboBox_veterinaire.setToolTip(_translate("tabWidget_medical", "Vétérinaire consultant", None))
        self.label_12.setText(_translate("tabWidget_medical", "   Type :", None))
        self.comboBox_consultType.setToolTip(_translate("tabWidget_medical", "Choir le type dominant de la consultation", None))
        self.label_Referant.setText(_translate("tabWidget_medical", "Référant :", None))
        self.comboBox_Referant.setToolTip(_translate("tabWidget_medical", "Choisir un vétérinaire référant", None))
        self.label_17.setText(_translate("tabWidget_medical", "Domaine Pathologique :", None))
        self.comboBox_PathologieDomaine.setToolTip(_translate("tabWidget_medical", "Domaine pathologique dominant de la consultation", None))
        self.label_Pathologie.setText(_translate("tabWidget_medical", "Pathologie :", None))
        self.comboBox_Pathologie.setToolTip(_translate("tabWidget_medical", "Choisir une Pathologie Dominante pour cette Consultation", None))
        self.toolButton_Pathologie.setToolTip(_translate("tabWidget_medical", "Accès au formulaire de pathologie", None))
        self.toolButton_Pathologie.setText(_translate("tabWidget_medical", "...", None))
        self.toolButton_comment.setText(_translate("tabWidget_medical", "...", None))
        self.label_14.setText(_translate("tabWidget_medical", "Observations :", None))
        self.textEdit_consultObs.setToolTip(_translate("tabWidget_medical", "Insérer les observations cliniques", None))
        self.label_15.setText(_translate("tabWidget_medical", "Traitements :", None))
        self.textEdit_consultTrait.setToolTip(_translate("tabWidget_medical", "Inserez les traitements", None))
        self.pushButton_valider.setToolTip(_translate("tabWidget_medical", "Enregistrer cette consultation", None))
        self.pushButton_valider.setText(_translate("tabWidget_medical", "Valider", None))
        self.pushButton_Nouveau.setToolTip(_translate("tabWidget_medical", "Nouvelle Consultation", None))
        self.pushButton_Nouveau.setText(_translate("tabWidget_medical", "Nouveau", None))
        self.pushButton_Hospit.setToolTip(_translate("tabWidget_medical", "Imprimer la fiche d\'hospitalisation", None))
        self.pushButton_Hospit.setText(_translate("tabWidget_medical", "Hospitalisation", None))
        self.pushButton_Facturation.setToolTip(_translate("tabWidget_medical", "Basculer en facturation", None))
        self.pushButton_Facturation.setText(_translate("tabWidget_medical", "Facturation", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_consulation), _translate("tabWidget_medical", "Consultation", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab), _translate("tabWidget_medical", "Vaccinations", None))
        self.toolButton_fichier.setText(_translate("tabWidget_medical", "...", None))
        self.pushButton_addImage.setToolTip(_translate("tabWidget_medical", "Ajouter une nouvelle image à l\'examen", None))
        self.pushButton_addImage.setText(_translate("tabWidget_medical", "Ajouter image", None))
        self.label_5.setText(_translate("tabWidget_medical", "Type d\'analyse :  ", None))
        self.label_3.setText(_translate("tabWidget_medical", "Analyses précédentes", None))
        self.listView.setStatusTip(_translate("tabWidget_medical", "Double click pour éditer l\'analyse", None))
        self.label_4.setText(_translate("tabWidget_medical", "Date Heure :  ", None))
        self.dateTimeEdit_analyse.setDisplayFormat(_translate("tabWidget_medical", "dd/MM/yyyy HH:mm", None))
        self.label_6.setText(_translate("tabWidget_medical", "Description de l\'analyse:", None))
        self.label_7.setText(_translate("tabWidget_medical", "Prélèvement :", None))
        self.label_8.setText(_translate("tabWidget_medical", "Observations :", None))
        self.label_9.setText(_translate("tabWidget_medical", "Conclusions :", None))
        self.pushButton_valide.setToolTip(_translate("tabWidget_medical", "Ajouter l\'analyse au dossier", None))
        self.pushButton_valide.setText(_translate("tabWidget_medical", "Valider", None))
        self.toolButton_AddTypeAnalyse.setToolTip(_translate("tabWidget_medical", "AJouter des types d\'analyses", None))
        self.toolButton_AddTypeAnalyse.setText(_translate("tabWidget_medical", "...", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_analyses), _translate("tabWidget_medical", "Analyses", None))
        self.label_RCP.setText(_translate("tabWidget_medical", "Mentions légales :", None))
        self.toolButton.setToolTip(_translate("tabWidget_medical", "Texte complet", None))
        self.toolButton.setText(_translate("tabWidget_medical", "...", None))
        self.toolButton_2.setToolTip(_translate("tabWidget_medical", "Résumé", None))
        self.toolButton_2.setText(_translate("tabWidget_medical", "...", None))
        self.label_medicament.setText(_translate("tabWidget_medical", "Médicament :", None))
        self.label_molecule.setText(_translate("tabWidget_medical", "Molécule :", None))
        self.label_posomol.setText(_translate("tabWidget_medical", "Posologie de principe actif :", None))
        self.label_presentation.setText(_translate("tabWidget_medical", "Présentation :", None))
        self.label_posomed.setText(_translate("tabWidget_medical", "Posologie de médicament :", None))
        self.label_especeCible.setText(_translate("tabWidget_medical", "Espèce cible :", None))
        self.pushButton_validOrdonnance.setText(_translate("tabWidget_medical", "Valider", None))
        self.pushButton_CalculPoso.setText(_translate("tabWidget_medical", "Calculatrice", None))
        self.pushButton_DMV.setText(_translate("tabWidget_medical", "Editer DMV", None))
        self.label_10.setText(_translate("tabWidget_medical", "Le :", None))
        self.dateEdit_ordonance.setDisplayFormat(_translate("tabWidget_medical", "dd/MM/yyyy", None))
        self.label_11.setText(_translate("tabWidget_medical", "Poids :", None))
        self.pushButton_OrdonnanceValid.setText(_translate("tabWidget_medical", "Valider", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_ordonnances), _translate("tabWidget_medical", "Ordonnances", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_planTherapeutique), _translate("tabWidget_medical", "Plan Thérapeutique", None))
        self.label_doc.setText(_translate("tabWidget_medical", "Documents disponibles :", None))
        self.label_docDate.setText(_translate("tabWidget_medical", "Date :", None))
        self.dateEdit_docDate.setDisplayFormat(_translate("tabWidget_medical", "dd/MM/yyyy", None))
        self.label_docFile.setText(_translate("tabWidget_medical", "Fichier :", None))
        self.toolButton_docFile.setToolTip(_translate("tabWidget_medical", "Selectionner un fichier", None))
        self.toolButton_docFile.setText(_translate("tabWidget_medical", "...", None))
        self.pushButton_docAdd.setToolTip(_translate("tabWidget_medical", "Ajouter nouveau document au dossier", None))
        self.pushButton_docAdd.setText(_translate("tabWidget_medical", "Ajouter", None))
        tabWidget_medical.setTabText(tabWidget_medical.indexOf(self.tab_documents), _translate("tabWidget_medical", "Documents", None))

from Mywidgets import MyComboBox
import resources_rc
