# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './OLD Form_consultation.ui'
#
# Created: Mon May  5 12:27:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../.designer/images/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.stackedWidget.setStyleSheet(_fromUtf8("background-color: rgba(188, 255, 231, 0);"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.tabWidget_fiches = QtGui.QTabWidget(self.page)
        self.tabWidget_fiches.setGeometry(QtCore.QRect(0, 0, 1024, 671))
        self.tabWidget_fiches.setAutoFillBackground(False)
        self.tabWidget_fiches.setStyleSheet(_fromUtf8(""))
        self.tabWidget_fiches.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_fiches.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_fiches.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_fiches.setDocumentMode(False)
        self.tabWidget_fiches.setTabsClosable(False)
        self.tabWidget_fiches.setMovable(False)
        self.tabWidget_fiches.setObjectName(_fromUtf8("tabWidget_fiches"))
        self.tab_fiche1 = QtGui.QWidget()
        self.tab_fiche1.setObjectName(_fromUtf8("tab_fiche1"))
        self.frame_client = QtGui.QFrame(self.tab_fiche1)
        self.frame_client.setGeometry(QtCore.QRect(0, 0, 474, 120))
        self.frame_client.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_client.setFrameShape(QtGui.QFrame.Box)
        self.frame_client.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_client.setLineWidth(1)
        self.frame_client.setObjectName(_fromUtf8("frame_client"))
        self.comboBox_client = QtGui.QComboBox(self.frame_client)
        self.comboBox_client.setGeometry(QtCore.QRect(10, 10, 371, 27))
        self.comboBox_client.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_client.setEditable(True)
        self.comboBox_client.setFrame(True)
        self.comboBox_client.setObjectName(_fromUtf8("comboBox_client"))
        self.textBrowser_client = QtGui.QTextBrowser(self.frame_client)
        self.textBrowser_client.setGeometry(QtCore.QRect(10, 50, 451, 61))
        self.textBrowser_client.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.textBrowser_client.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_client.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_client.setLineWidth(1)
        self.textBrowser_client.setMidLineWidth(0)
        self.textBrowser_client.setObjectName(_fromUtf8("textBrowser_client"))
        self.toolButton_ClientInfo = QtGui.QToolButton(self.frame_client)
        self.toolButton_ClientInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClientInfo.setIcon(icon1)
        self.toolButton_ClientInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_ClientInfo.setObjectName(_fromUtf8("toolButton_ClientInfo"))
        self.frame_animal = QtGui.QFrame(self.tab_fiche1)
        self.frame_animal.setGeometry(QtCore.QRect(536, 0, 482, 120))
        self.frame_animal.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_animal.setFrameShape(QtGui.QFrame.Box)
        self.frame_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_animal.setObjectName(_fromUtf8("frame_animal"))
        self.comboBox_Animal = QtGui.QComboBox(self.frame_animal)
        self.comboBox_Animal.setGeometry(QtCore.QRect(10, 10, 261, 27))
        self.comboBox_Animal.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Animal.setEditable(True)
        self.comboBox_Animal.setObjectName(_fromUtf8("comboBox_Animal"))
        self.textBrowser_animal = QtGui.QTextBrowser(self.frame_animal)
        self.textBrowser_animal.setGeometry(QtCore.QRect(10, 50, 454, 61))
        self.textBrowser_animal.setStyleSheet(_fromUtf8("background-color: rgb(231, 231, 231);"))
        self.textBrowser_animal.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_animal.setObjectName(_fromUtf8("textBrowser_animal"))
        self.toolButton_AnimalInfo = QtGui.QToolButton(self.frame_animal)
        self.toolButton_AnimalInfo.setGeometry(QtCore.QRect(430, 10, 26, 25))
        self.toolButton_AnimalInfo.setIcon(icon1)
        self.toolButton_AnimalInfo.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_AnimalInfo.setObjectName(_fromUtf8("toolButton_AnimalInfo"))
        self.toolButton_addAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addAnimal.setGeometry(QtCore.QRect(510, 0, 26, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../.designer/images/add1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addAnimal.setIcon(icon2)
        self.toolButton_addAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addAnimal.setObjectName(_fromUtf8("toolButton_addAnimal"))
        self.toolButton_editAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editAnimal.setGeometry(QtCore.QRect(510, 32, 26, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../.designer/images/edit1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editAnimal.setIcon(icon3)
        self.toolButton_editAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editAnimal.setObjectName(_fromUtf8("toolButton_editAnimal"))
        self.toolButton_deleteAnimal = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteAnimal.setGeometry(QtCore.QRect(510, 64, 26, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../.designer/images/delete2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deleteAnimal.setIcon(icon4)
        self.toolButton_deleteAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteAnimal.setObjectName(_fromUtf8("toolButton_deleteAnimal"))
        self.toolButton_scan = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_scan.setGeometry(QtCore.QRect(493, 95, 26, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../.designer/images/loupe2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scan.setIcon(icon5)
        self.toolButton_scan.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan.setObjectName(_fromUtf8("toolButton_scan"))
        self.tabWidget_medical = QtGui.QTabWidget(self.tab_fiche1)
        self.tabWidget_medical.setGeometry(QtCore.QRect(0, 120, 1024, 521))
        self.tabWidget_medical.setObjectName(_fromUtf8("tabWidget_medical"))
        self.tab_consulation = QtGui.QWidget()
        self.tab_consulation.setObjectName(_fromUtf8("tab_consulation"))
        self.splitter = QtGui.QSplitter(self.tab_consulation)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1018, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_med_sup = QtGui.QFrame(self.splitter)
        self.frame_med_sup.setStyleSheet(_fromUtf8("background-color: rgb(188, 255, 231,0);"))
        self.frame_med_sup.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_sup.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_sup.setObjectName(_fromUtf8("frame_med_sup"))
        self.tableWidget_vacciner = QtGui.QTableWidget(self.frame_med_sup)
        self.tableWidget_vacciner.setGeometry(QtCore.QRect(690, 10, 311, 121))
        self.tableWidget_vacciner.setRowCount(3)
        self.tableWidget_vacciner.setColumnCount(3)
        self.tableWidget_vacciner.setObjectName(_fromUtf8("tableWidget_vacciner"))
        self.tableWidget_vacciner.verticalHeader().setVisible(False)
        self.button_vacciner = QtGui.QPushButton(self.frame_med_sup)
        self.button_vacciner.setGeometry(QtCore.QRect(910, 230, 93, 27))
        self.button_vacciner.setObjectName(_fromUtf8("button_vacciner"))
        self.dateEdit_vacciner_start = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_start.setGeometry(QtCore.QRect(750, 140, 101, 27))
        self.dateEdit_vacciner_start.setCalendarPopup(True)
        self.dateEdit_vacciner_start.setObjectName(_fromUtf8("dateEdit_vacciner_start"))
        self.dateEdit_vacciner_end = QtGui.QDateEdit(self.frame_med_sup)
        self.dateEdit_vacciner_end.setGeometry(QtCore.QRect(900, 180, 101, 27))
        self.dateEdit_vacciner_end.setCalendarPopup(True)
        self.dateEdit_vacciner_end.setObjectName(_fromUtf8("dateEdit_vacciner_end"))
        self.comboBox_vacciner = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_vacciner.setGeometry(QtCore.QRect(900, 140, 101, 27))
        self.comboBox_vacciner.setObjectName(_fromUtf8("comboBox_vacciner"))
        self.comboBox_rappel = QtGui.QComboBox(self.frame_med_sup)
        self.comboBox_rappel.setGeometry(QtCore.QRect(750, 180, 141, 27))
        self.comboBox_rappel.setObjectName(_fromUtf8("comboBox_rappel"))
        self.label_2 = QtGui.QLabel(self.frame_med_sup)
        self.label_2.setGeometry(QtCore.QRect(690, 190, 62, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_vaccinerStart = QtGui.QLabel(self.frame_med_sup)
        self.label_vaccinerStart.setGeometry(QtCore.QRect(690, 150, 31, 17))
        self.label_vaccinerStart.setObjectName(_fromUtf8("label_vaccinerStart"))
        self.textBrowser_consultations = QtGui.QTextBrowser(self.frame_med_sup)
        self.textBrowser_consultations.setGeometry(QtCore.QRect(10, 10, 671, 401))
        self.textBrowser_consultations.setStyleSheet(_fromUtf8("background-position: right; background-image:  url(:/newPrefix/images/openvet.png);background-repeat: no-repeat; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.textBrowser_consultations.setObjectName(_fromUtf8("textBrowser_consultations"))
        self.frame_med_inf = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_med_inf.sizePolicy().hasHeightForWidth())
        self.frame_med_inf.setSizePolicy(sizePolicy)
        self.frame_med_inf.setStyleSheet(_fromUtf8(""))
        self.frame_med_inf.setFrameShape(QtGui.QFrame.Box)
        self.frame_med_inf.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_med_inf.setObjectName(_fromUtf8("frame_med_inf"))
        self.layoutWidget = QtGui.QWidget(self.frame_med_inf)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1007, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.dateEdit_consult = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_consult.sizePolicy().hasHeightForWidth())
        self.dateEdit_consult.setSizePolicy(sizePolicy)
        self.dateEdit_consult.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_consult.setCalendarPopup(True)
        self.dateEdit_consult.setObjectName(_fromUtf8("dateEdit_consult"))
        self.horizontalLayout.addWidget(self.dateEdit_consult)
        spacerItem = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_veterinaire = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_veterinaire.sizePolicy().hasHeightForWidth())
        self.comboBox_veterinaire.setSizePolicy(sizePolicy)
        self.comboBox_veterinaire.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox_veterinaire.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_veterinaire.setEditable(True)
        self.comboBox_veterinaire.setFrame(True)
        self.comboBox_veterinaire.setObjectName(_fromUtf8("comboBox_veterinaire"))
        self.horizontalLayout.addWidget(self.comboBox_veterinaire)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.comboBox_consultType = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_consultType.setMinimumSize(QtCore.QSize(131, 27))
        self.comboBox_consultType.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_consultType.setObjectName(_fromUtf8("comboBox_consultType"))
        self.horizontalLayout.addWidget(self.comboBox_consultType)
        self.label_Referant = QtGui.QLabel(self.layoutWidget)
        self.label_Referant.setMaximumSize(QtCore.QSize(63, 16777215))
        self.label_Referant.setObjectName(_fromUtf8("label_Referant"))
        self.horizontalLayout.addWidget(self.label_Referant)
        self.comboBox_Referant = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Referant.setMinimumSize(QtCore.QSize(181, 27))
        self.comboBox_Referant.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_Referant.setEditable(True)
        self.comboBox_Referant.setObjectName(_fromUtf8("comboBox_Referant"))
        self.horizontalLayout.addWidget(self.comboBox_Referant)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_2.setMaximumSize(QtCore.QSize(241, 32))
        self.comboBox_2.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(81, 0))
        self.label_16.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(221, 27))
        self.comboBox.setMaximumSize(QtCore.QSize(261, 32))
        self.comboBox.setStyleSheet(_fromUtf8("selection-background-color: rgb(255, 255, 127);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.toolButton_Pathologie = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_Pathologie.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_Pathologie.setMaximumSize(QtCore.QSize(36, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/pathologie.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Pathologie.setIcon(icon6)
        self.toolButton_Pathologie.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Pathologie.setObjectName(_fromUtf8("toolButton_Pathologie"))
        self.horizontalLayout_7.addWidget(self.toolButton_Pathologie)
        self.toolButton_comment = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_comment.setMinimumSize(QtCore.QSize(27, 27))
        self.toolButton_comment.setMaximumSize(QtCore.QSize(36, 16777215))
        self.toolButton_comment.setIcon(icon1)
        self.toolButton_comment.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_comment.setObjectName(_fromUtf8("toolButton_comment"))
        self.horizontalLayout_7.addWidget(self.toolButton_comment)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.textEdit_consultObs = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultObs.sizePolicy().hasHeightForWidth())
        self.textEdit_consultObs.setSizePolicy(sizePolicy)
        self.textEdit_consultObs.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultObs.setMaximumSize(QtCore.QSize(16777215, 111))
        self.textEdit_consultObs.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultObs.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_consultObs.setFrameShadow(QtGui.QFrame.Sunken)
        self.textEdit_consultObs.setObjectName(_fromUtf8("textEdit_consultObs"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit_consultObs)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.textEdit_consultTrait = QtGui.QTextEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_consultTrait.sizePolicy().hasHeightForWidth())
        self.textEdit_consultTrait.setSizePolicy(sizePolicy)
        self.textEdit_consultTrait.setMinimumSize(QtCore.QSize(760, 0))
        self.textEdit_consultTrait.setMaximumSize(QtCore.QSize(16777215, 51))
        self.textEdit_consultTrait.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_consultTrait.setObjectName(_fromUtf8("textEdit_consultTrait"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textEdit_consultTrait)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_valider = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_valider.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.verticalLayout.addWidget(self.pushButton_valider)
        self.pushButton_Nouveau = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Nouveau.setObjectName(_fromUtf8("pushButton_Nouveau"))
        self.verticalLayout.addWidget(self.pushButton_Nouveau)
        self.pushButton_Hospit = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Hospit.setObjectName(_fromUtf8("pushButton_Hospit"))
        self.verticalLayout.addWidget(self.pushButton_Hospit)
        self.pushButton_Facturation = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Facturation.setObjectName(_fromUtf8("pushButton_Facturation"))
        self.verticalLayout.addWidget(self.pushButton_Facturation)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget_medical.addTab(self.tab_consulation, _fromUtf8(""))
        self.tab_analyses = QtGui.QWidget()
        self.tab_analyses.setObjectName(_fromUtf8("tab_analyses"))
        self.tableWidget_analyses = QtGui.QTableWidget(self.tab_analyses)
        self.tableWidget_analyses.setEnabled(True)
        self.tableWidget_analyses.setGeometry(QtCore.QRect(650, 70, 350, 241))
        self.tableWidget_analyses.setShowGrid(True)
        self.tableWidget_analyses.setRowCount(16)
        self.tableWidget_analyses.setColumnCount(4)
        self.tableWidget_analyses.setObjectName(_fromUtf8("tableWidget_analyses"))
        self.tableWidget_analyses.verticalHeader().setVisible(False)
        self.listWidget_analyse = QtGui.QListWidget(self.tab_analyses)
        self.listWidget_analyse.setGeometry(QtCore.QRect(650, 60, 351, 192))
        self.listWidget_analyse.setObjectName(_fromUtf8("listWidget_analyse"))
        self.lineEdit_titreImage = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_titreImage.setGeometry(QtCore.QRect(650, 340, 311, 27))
        self.lineEdit_titreImage.setObjectName(_fromUtf8("lineEdit_titreImage"))
        self.lineEdit_fichier = QtGui.QLineEdit(self.tab_analyses)
        self.lineEdit_fichier.setGeometry(QtCore.QRect(650, 390, 311, 27))
        self.lineEdit_fichier.setObjectName(_fromUtf8("lineEdit_fichier"))
        self.toolButton_fichier = QtGui.QToolButton(self.tab_analyses)
        self.toolButton_fichier.setGeometry(QtCore.QRect(970, 390, 26, 25))
        self.toolButton_fichier.setObjectName(_fromUtf8("toolButton_fichier"))
        self.pushButton_addImage = QtGui.QPushButton(self.tab_analyses)
        self.pushButton_addImage.setGeometry(QtCore.QRect(760, 430, 111, 27))
        self.pushButton_addImage.setObjectName(_fromUtf8("pushButton_addImage"))
        self.line = QtGui.QFrame(self.tab_analyses)
        self.line.setGeometry(QtCore.QRect(620, 30, 20, 420))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_analyses)
        self.line_2.setGeometry(QtCore.QRect(270, 30, 20, 420))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_5 = QtGui.QLabel(self.tab_analyses)
        self.label_5.setGeometry(QtCore.QRect(660, 11, 113, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_typeanalyse = QtGui.QComboBox(self.tab_analyses)
        self.comboBox_typeanalyse.setGeometry(QtCore.QRect(780, 10, 181, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_typeanalyse.sizePolicy().hasHeightForWidth())
        self.comboBox_typeanalyse.setSizePolicy(sizePolicy)
        self.comboBox_typeanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_typeanalyse.setObjectName(_fromUtf8("comboBox_typeanalyse"))
        self.label_3 = QtGui.QLabel(self.tab_analyses)
        self.label_3.setGeometry(QtCore.QRect(50, 12, 171, 19))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listView = QtGui.QListView(self.tab_analyses)
        self.listView.setGeometry(QtCore.QRect(18, 37, 239, 410))
        self.listView.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_analyses)
        self.layoutWidget1.setGeometry(QtCore.QRect(303, 12, 303, 438))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_analyse = QtGui.QDateTimeEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_analyse.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_analyse.setSizePolicy(sizePolicy)
        self.dateTimeEdit_analyse.setMinimumSize(QtCore.QSize(156, 27))
        self.dateTimeEdit_analyse.setCalendarPopup(True)
        self.dateTimeEdit_analyse.setObjectName(_fromUtf8("dateTimeEdit_analyse"))
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_analyse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_description = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_description.sizePolicy().hasHeightForWidth())
        self.lineEdit_description.setSizePolicy(sizePolicy)
        self.lineEdit_description.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_description.setObjectName(_fromUtf8("lineEdit_description"))
        self.verticalLayout_2.addWidget(self.lineEdit_description)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.lineEdit_prelevement = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prelevement.sizePolicy().hasHeightForWidth())
        self.lineEdit_prelevement.setSizePolicy(sizePolicy)
        self.lineEdit_prelevement.setMinimumSize(QtCore.QSize(261, 27))
        self.lineEdit_prelevement.setObjectName(_fromUtf8("lineEdit_prelevement"))
        self.verticalLayout_2.addWidget(self.lineEdit_prelevement)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.textEdit_syntheseanalyse = QtGui.QTextEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_syntheseanalyse.sizePolicy().hasHeightForWidth())
        self.textEdit_syntheseanalyse.setSizePolicy(sizePolicy)
        self.textEdit_syntheseanalyse.setMinimumSize(QtCore.QSize(301, 120))
        self.textEdit_syntheseanalyse.setMaximumSize(QtCore.QSize(16777215, 141))
        self.textEdit_syntheseanalyse.setBaseSize(QtCore.QSize(0, 0))
        self.textEdit_syntheseanalyse.setAutoFillBackground(False)
        self.textEdit_syntheseanalyse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_syntheseanalyse.setObjectName(_fromUtf8("textEdit_syntheseanalyse"))
        self.verticalLayout_2.addWidget(self.textEdit_syntheseanalyse)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.textEdit_conclusions = QtGui.QTextEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_conclusions.sizePolicy().hasHeightForWidth())
        self.textEdit_conclusions.setSizePolicy(sizePolicy)
        self.textEdit_conclusions.setMinimumSize(QtCore.QSize(301, 0))
        self.textEdit_conclusions.setMaximumSize(QtCore.QSize(16777215, 61))
        self.textEdit_conclusions.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit_conclusions.setObjectName(_fromUtf8("textEdit_conclusions"))
        self.verticalLayout_2.addWidget(self.textEdit_conclusions)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_valide = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_valide.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_valide.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_valide.setObjectName(_fromUtf8("pushButton_valide"))
        self.horizontalLayout_6.addWidget(self.pushButton_valide)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.tabWidget_medical.addTab(self.tab_analyses, _fromUtf8(""))
        self.tab_ordonnances = QtGui.QWidget()
        self.tab_ordonnances.setObjectName(_fromUtf8("tab_ordonnances"))
        self.textBrowser_medicament = QtGui.QTextBrowser(self.tab_ordonnances)
        self.textBrowser_medicament.setGeometry(QtCore.QRect(540, 220, 451, 231))
        self.textBrowser_medicament.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_medicament.setObjectName(_fromUtf8("textBrowser_medicament"))
        self.label_RCP = QtGui.QLabel(self.tab_ordonnances)
        self.label_RCP.setGeometry(QtCore.QRect(540, 200, 131, 17))
        self.label_RCP.setObjectName(_fromUtf8("label_RCP"))
        self.line_3 = QtGui.QFrame(self.tab_ordonnances)
        self.line_3.setGeometry(QtCore.QRect(515, 20, 20, 501))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.toolButton = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton.setGeometry(QtCore.QRect(960, 190, 26, 25))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon7)
        self.toolButton.setIconSize(QtCore.QSize(20, 20))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.tab_ordonnances)
        self.toolButton_2.setGeometry(QtCore.QRect(920, 190, 26, 25))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/doc_abst.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon8)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget2.setGeometry(QtCore.QRect(543, 10, 451, 171))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_medicament = QtGui.QLabel(self.layoutWidget2)
        self.label_medicament.setObjectName(_fromUtf8("label_medicament"))
        self.gridLayout.addWidget(self.label_medicament, 0, 0, 1, 1)
        self.label_molecule = QtGui.QLabel(self.layoutWidget2)
        self.label_molecule.setObjectName(_fromUtf8("label_molecule"))
        self.gridLayout.addWidget(self.label_molecule, 0, 1, 1, 1)
        self.comboBox_medicament = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_medicament.sizePolicy().hasHeightForWidth())
        self.comboBox_medicament.setSizePolicy(sizePolicy)
        self.comboBox_medicament.setObjectName(_fromUtf8("comboBox_medicament"))
        self.gridLayout.addWidget(self.comboBox_medicament, 1, 0, 1, 1)
        self.comboBox_molecule = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_molecule.sizePolicy().hasHeightForWidth())
        self.comboBox_molecule.setSizePolicy(sizePolicy)
        self.comboBox_molecule.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_molecule.setObjectName(_fromUtf8("comboBox_molecule"))
        self.gridLayout.addWidget(self.comboBox_molecule, 1, 1, 1, 1)
        self.label_posomol = QtGui.QLabel(self.layoutWidget2)
        self.label_posomol.setObjectName(_fromUtf8("label_posomol"))
        self.gridLayout.addWidget(self.label_posomol, 2, 0, 1, 1)
        self.label_presentation = QtGui.QLabel(self.layoutWidget2)
        self.label_presentation.setObjectName(_fromUtf8("label_presentation"))
        self.gridLayout.addWidget(self.label_presentation, 2, 1, 1, 1)
        self.lineEdit_posomol = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomol.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomol.setSizePolicy(sizePolicy)
        self.lineEdit_posomol.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomol.setObjectName(_fromUtf8("lineEdit_posomol"))
        self.gridLayout.addWidget(self.lineEdit_posomol, 3, 0, 1, 1)
        self.comboBox_presentation = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_presentation.setObjectName(_fromUtf8("comboBox_presentation"))
        self.gridLayout.addWidget(self.comboBox_presentation, 3, 1, 1, 1)
        self.label_posomed = QtGui.QLabel(self.layoutWidget2)
        self.label_posomed.setObjectName(_fromUtf8("label_posomed"))
        self.gridLayout.addWidget(self.label_posomed, 4, 0, 1, 1)
        self.label_especeCible = QtGui.QLabel(self.layoutWidget2)
        self.label_especeCible.setObjectName(_fromUtf8("label_especeCible"))
        self.gridLayout.addWidget(self.label_especeCible, 4, 1, 1, 1)
        self.lineEdit_posomed = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_posomed.sizePolicy().hasHeightForWidth())
        self.lineEdit_posomed.setSizePolicy(sizePolicy)
        self.lineEdit_posomed.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_posomed.setObjectName(_fromUtf8("lineEdit_posomed"))
        self.gridLayout.addWidget(self.lineEdit_posomed, 5, 0, 1, 1)
        self.comboBox_especeCible = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_especeCible.setObjectName(_fromUtf8("comboBox_especeCible"))
        self.gridLayout.addWidget(self.comboBox_especeCible, 5, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget3.setGeometry(QtCore.QRect(540, 490, 451, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_validOrdonnance = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_validOrdonnance.setObjectName(_fromUtf8("pushButton_validOrdonnance"))
        self.horizontalLayout_4.addWidget(self.pushButton_validOrdonnance)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_CalculPoso = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_CalculPoso.setObjectName(_fromUtf8("pushButton_CalculPoso"))
        self.horizontalLayout_4.addWidget(self.pushButton_CalculPoso)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_DMV = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_DMV.setObjectName(_fromUtf8("pushButton_DMV"))
        self.horizontalLayout_4.addWidget(self.pushButton_DMV)
        self.layoutWidget4 = QtGui.QWidget(self.tab_ordonnances)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 31, 513, 387))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.dateEdit_ordonance = QtGui.QDateEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ordonance.sizePolicy().hasHeightForWidth())
        self.dateEdit_ordonance.setSizePolicy(sizePolicy)
        self.dateEdit_ordonance.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_ordonance.setBaseSize(QtCore.QSize(0, 0))
        self.dateEdit_ordonance.setCalendarPopup(True)
        self.dateEdit_ordonance.setObjectName(_fromUtf8("dateEdit_ordonance"))
        self.horizontalLayout_3.addWidget(self.dateEdit_ordonance)
        spacerItem3 = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_11 = QtGui.QLabel(self.layoutWidget4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lineEdit_poids = QtGui.QLineEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_poids.sizePolicy().hasHeightForWidth())
        self.lineEdit_poids.setSizePolicy(sizePolicy)
        self.lineEdit_poids.setMinimumSize(QtCore.QSize(66, 27))
        self.lineEdit_poids.setObjectName(_fromUtf8("lineEdit_poids"))
        self.horizontalLayout_3.addWidget(self.lineEdit_poids)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(491, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(496, 391))
        self.textEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_4.addWidget(self.textEdit)
        self.pushButton_OrdonnanceValid = QtGui.QPushButton(self.tab_ordonnances)
        self.pushButton_OrdonnanceValid.setGeometry(QtCore.QRect(200, 430, 93, 27))
        self.pushButton_OrdonnanceValid.setObjectName(_fromUtf8("pushButton_OrdonnanceValid"))
        self.tabWidget_medical.addTab(self.tab_ordonnances, _fromUtf8(""))
        self.tab_planTherapeutique = QtGui.QWidget()
        self.tab_planTherapeutique.setObjectName(_fromUtf8("tab_planTherapeutique"))
        self.tabWidget_medical.addTab(self.tab_planTherapeutique, _fromUtf8(""))
        self.tab_documents = QtGui.QWidget()
        self.tab_documents.setObjectName(_fromUtf8("tab_documents"))
        self.listView_doc = QtGui.QListView(self.tab_documents)
        self.listView_doc.setGeometry(QtCore.QRect(20, 90, 241, 341))
        self.listView_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.listView_doc.setObjectName(_fromUtf8("listView_doc"))
        self.label_doc = QtGui.QLabel(self.tab_documents)
        self.label_doc.setGeometry(QtCore.QRect(10, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_doc.setFont(font)
        self.label_doc.setTextFormat(QtCore.Qt.PlainText)
        self.label_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doc.setObjectName(_fromUtf8("label_doc"))
        self.layoutWidget5 = QtGui.QWidget(self.tab_documents)
        self.layoutWidget5.setGeometry(QtCore.QRect(320, 52, 631, 378))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_docDate = QtGui.QLabel(self.layoutWidget5)
        self.label_docDate.setObjectName(_fromUtf8("label_docDate"))
        self.horizontalLayout_5.addWidget(self.label_docDate)
        self.dateEdit_docDate = QtGui.QDateEdit(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_docDate.sizePolicy().hasHeightForWidth())
        self.dateEdit_docDate.setSizePolicy(sizePolicy)
        self.dateEdit_docDate.setMinimumSize(QtCore.QSize(112, 27))
        self.dateEdit_docDate.setCalendarPopup(True)
        self.dateEdit_docDate.setObjectName(_fromUtf8("dateEdit_docDate"))
        self.horizontalLayout_5.addWidget(self.dateEdit_docDate)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_docFile = QtGui.QLabel(self.layoutWidget5)
        self.label_docFile.setObjectName(_fromUtf8("label_docFile"))
        self.horizontalLayout_5.addWidget(self.label_docFile)
        self.lineEdit_docFile = QtGui.QLineEdit(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_docFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_docFile.setSizePolicy(sizePolicy)
        self.lineEdit_docFile.setMinimumSize(QtCore.QSize(212, 27))
        self.lineEdit_docFile.setObjectName(_fromUtf8("lineEdit_docFile"))
        self.horizontalLayout_5.addWidget(self.lineEdit_docFile)
        self.toolButton_docFile = QtGui.QToolButton(self.layoutWidget5)
        self.toolButton_docFile.setObjectName(_fromUtf8("toolButton_docFile"))
        self.horizontalLayout_5.addWidget(self.toolButton_docFile)
        self.pushButton_docAdd = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_docAdd.setObjectName(_fromUtf8("pushButton_docAdd"))
        self.horizontalLayout_5.addWidget(self.pushButton_docAdd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.textBrowser_doc = QtGui.QTextBrowser(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_doc.sizePolicy().hasHeightForWidth())
        self.textBrowser_doc.setSizePolicy(sizePolicy)
        self.textBrowser_doc.setMinimumSize(QtCore.QSize(571, 341))
        self.textBrowser_doc.setMaximumSize(QtCore.QSize(16777215, 611))
        self.textBrowser_doc.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textBrowser_doc.setObjectName(_fromUtf8("textBrowser_doc"))
        self.verticalLayout_3.addWidget(self.textBrowser_doc)
        self.tabWidget_medical.addTab(self.tab_documents, _fromUtf8(""))
        self.toolButton_addClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_addClient.setGeometry(QtCore.QRect(474, 0, 26, 25))
        self.toolButton_addClient.setIcon(icon2)
        self.toolButton_addClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_addClient.setObjectName(_fromUtf8("toolButton_addClient"))
        self.toolButton_deleteClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_deleteClient.setGeometry(QtCore.QRect(474, 64, 26, 25))
        self.toolButton_deleteClient.setIcon(icon4)
        self.toolButton_deleteClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_deleteClient.setObjectName(_fromUtf8("toolButton_deleteClient"))
        self.toolButton_editClient = QtGui.QToolButton(self.tab_fiche1)
        self.toolButton_editClient.setGeometry(QtCore.QRect(474, 32, 26, 25))
        self.toolButton_editClient.setIcon(icon3)
        self.toolButton_editClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editClient.setObjectName(_fromUtf8("toolButton_editClient"))
        self.tabWidget_fiches.addTab(self.tab_fiche1, _fromUtf8(""))
        self.tab_ajouter = QtGui.QWidget()
        self.tab_ajouter.setObjectName(_fromUtf8("tab_ajouter"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/add1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_fiches.addTab(self.tab_ajouter, icon9, _fromUtf8(""))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDossiers_M_dicaux = QtGui.QMenu(self.menubar)
        self.menuDossiers_M_dicaux.setObjectName(_fromUtf8("menuDossiers_M_dicaux"))
        self.menuComptabilit = QtGui.QMenu(self.menubar)
        self.menuComptabilit.setObjectName(_fromUtf8("menuComptabilit"))
        self.menuD_clarations = QtGui.QMenu(self.menuComptabilit)
        self.menuD_clarations.setObjectName(_fromUtf8("menuD_clarations"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuBase_de_donn_es = QtGui.QMenu(self.menuConfiguration)
        self.menuBase_de_donn_es.setObjectName(_fromUtf8("menuBase_de_donn_es"))
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName(_fromUtf8("menuQuitter"))
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName(_fromUtf8("menuStock"))
        self.menuStatistiques = QtGui.QMenu(self.menubar)
        self.menuStatistiques.setObjectName(_fromUtf8("menuStatistiques"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Recettes = QtGui.QAction(MainWindow)
        self.action_Recettes.setObjectName(_fromUtf8("action_Recettes"))
        self.actionD_penses = QtGui.QAction(MainWindow)
        self.actionD_penses.setObjectName(_fromUtf8("actionD_penses"))
        self.action_Banque = QtGui.QAction(MainWindow)
        self.action_Banque.setObjectName(_fromUtf8("action_Banque"))
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindow)
        self.actionRecoupement_bancaire.setObjectName(_fromUtf8("actionRecoupement_bancaire"))
        self.actionTVA = QtGui.QAction(MainWindow)
        self.actionTVA.setObjectName(_fromUtf8("actionTVA"))
        self.action2035 = QtGui.QAction(MainWindow)
        self.action2035.setObjectName(_fromUtf8("action2035"))
        self.actionCommandes = QtGui.QAction(MainWindow)
        self.actionCommandes.setObjectName(_fromUtf8("actionCommandes"))
        self.actionAnalyse = QtGui.QAction(MainWindow)
        self.actionAnalyse.setObjectName(_fromUtf8("actionAnalyse"))
        self.action_Facturation = QtGui.QAction(MainWindow)
        self.action_Facturation.setObjectName(_fromUtf8("action_Facturation"))
        self.actionBureau = QtGui.QAction(MainWindow)
        self.actionBureau.setObjectName(_fromUtf8("actionBureau"))
        self.action_M_dicaments = QtGui.QAction(MainWindow)
        self.action_M_dicaments.setObjectName(_fromUtf8("action_M_dicaments"))
        self.action_Pathologies = QtGui.QAction(MainWindow)
        self.action_Pathologies.setObjectName(_fromUtf8("action_Pathologies"))
        self.actionBackup = QtGui.QAction(MainWindow)
        self.actionBackup.setObjectName(_fromUtf8("actionBackup"))
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName(_fromUtf8("actionRestore"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionR_seau_S_curit = QtGui.QAction(MainWindow)
        self.actionR_seau_S_curit.setObjectName(_fromUtf8("actionR_seau_S_curit"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.menuD_clarations.addAction(self.actionTVA)
        self.menuD_clarations.addAction(self.action2035)
        self.menuComptabilit.addAction(self.action_Recettes)
        self.menuComptabilit.addAction(self.actionD_penses)
        self.menuComptabilit.addAction(self.action_Banque)
        self.menuComptabilit.addAction(self.actionRecoupement_bancaire)
        self.menuComptabilit.addAction(self.menuD_clarations.menuAction())
        self.menuBase_de_donn_es.addAction(self.actionBackup)
        self.menuBase_de_donn_es.addAction(self.actionRestore)
        self.menuBase_de_donn_es.addAction(self.actionImport)
        self.menuConfiguration.addAction(self.actionBureau)
        self.menuConfiguration.addAction(self.action_Facturation)
        self.menuConfiguration.addAction(self.action_M_dicaments)
        self.menuConfiguration.addAction(self.action_Pathologies)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuBase_de_donn_es.menuAction())
        self.menuConfiguration.addAction(self.actionR_seau_S_curit)
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuStock.addAction(self.actionCommandes)
        self.menuStock.addAction(self.actionAnalyse)
        self.menubar.addAction(self.menuDossiers_M_dicaux.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuComptabilit.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuQuitter.menuAction())
        self.label_2.setBuddy(self.comboBox_rappel)
        self.label_vaccinerStart.setBuddy(self.dateEdit_vacciner_start)
        self.label_13.setBuddy(self.dateEdit_consult)
        self.label.setBuddy(self.comboBox_veterinaire)
        self.label_12.setBuddy(self.comboBox_consultType)
        self.label_Referant.setBuddy(self.comboBox_Referant)
        self.label_3.setBuddy(self.listView)
        self.label_4.setBuddy(self.dateTimeEdit_analyse)
        self.label_6.setBuddy(self.lineEdit_description)
        self.label_7.setBuddy(self.lineEdit_prelevement)
        self.label_8.setBuddy(self.textEdit_syntheseanalyse)
        self.label_9.setBuddy(self.textEdit_conclusions)
        self.label_RCP.setBuddy(self.textBrowser_medicament)
        self.label_medicament.setBuddy(self.comboBox_medicament)
        self.label_molecule.setBuddy(self.comboBox_molecule)
        self.label_posomol.setBuddy(self.lineEdit_posomol)
        self.label_presentation.setBuddy(self.comboBox_presentation)
        self.label_posomed.setBuddy(self.lineEdit_posomed)
        self.label_especeCible.setBuddy(self.comboBox_especeCible)
        self.label_10.setBuddy(self.dateEdit_ordonance)
        self.label_11.setBuddy(self.lineEdit_poids)
        self.label_doc.setBuddy(self.listView_doc)
        self.label_docFile.setBuddy(self.lineEdit_docFile)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_fiches.setCurrentIndex(0)
        self.tabWidget_medical.setCurrentIndex(2)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL(_fromUtf8("clicked()")), self.comboBox_vacciner.show)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dateEdit_vacciner_start.show)
        QtCore.QObject.connect(self.button_vacciner, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dateEdit_vacciner_end.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Vet", None))
        self.textBrowser_client.setToolTip(_translate("MainWindow", "Double click pour sélectionner l\'édition", None))
        self.toolButton_ClientInfo.setText(_translate("MainWindow", "...", None))
        self.textBrowser_animal.setToolTip(_translate("MainWindow", "Double click pour sélectionner l\'édition", None))
        self.toolButton_AnimalInfo.setText(_translate("MainWindow", "...", None))
        self.toolButton_addAnimal.setToolTip(_translate("MainWindow", "Nouvel animal", None))
        self.toolButton_addAnimal.setText(_translate("MainWindow", "...", None))
        self.toolButton_editAnimal.setToolTip(_translate("MainWindow", "Modifie animal", None))
        self.toolButton_editAnimal.setText(_translate("MainWindow", "...", None))
        self.toolButton_deleteAnimal.setToolTip(_translate("MainWindow", "Efface animal", None))
        self.toolButton_deleteAnimal.setText(_translate("MainWindow", "...", None))
        self.toolButton_scan.setToolTip(_translate("MainWindow", "Recherche client / animal", None))
        self.toolButton_scan.setText(_translate("MainWindow", "...", None))
        self.button_vacciner.setToolTip(_translate("MainWindow", "Ajouter ce vaccin dans le dossier", None))
        self.button_vacciner.setText(_translate("MainWindow", "Vacciner", None))
        self.dateEdit_vacciner_start.setToolTip(_translate("MainWindow", "Date de vaccination", None))
        self.dateEdit_vacciner_end.setToolTip(_translate("MainWindow", "Date de rappel", None))
        self.comboBox_vacciner.setToolTip(_translate("MainWindow", "Vaccin", None))
        self.comboBox_rappel.setToolTip(_translate("MainWindow", "Période de rappel", None))
        self.label_2.setText(_translate("MainWindow", "Rappel :", None))
        self.label_vaccinerStart.setText(_translate("MainWindow", "Le :", None))
        self.frame_med_inf.setToolTip(_translate("MainWindow", "Ajouter un commentaire", None))
        self.label_13.setText(_translate("MainWindow", "Le :", None))
        self.dateEdit_consult.setToolTip(_translate("MainWindow", "Date de consultation", None))
        self.dateEdit_consult.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.label.setText(_translate("MainWindow", "Vétérinaire :", None))
        self.comboBox_veterinaire.setToolTip(_translate("MainWindow", "Vétérinaire consultant", None))
        self.label_12.setText(_translate("MainWindow", "   Type :", None))
        self.comboBox_consultType.setToolTip(_translate("MainWindow", "Choir le type dominant de la consultation", None))
        self.label_Referant.setText(_translate("MainWindow", "Référant :", None))
        self.comboBox_Referant.setToolTip(_translate("MainWindow", "Choisir un vétérinaire référant", None))
        self.label_17.setText(_translate("MainWindow", "Domaine Pathologique :", None))
        self.comboBox_2.setToolTip(_translate("MainWindow", "Domaine pathologique dominant de la consultation", None))
        self.label_16.setText(_translate("MainWindow", "Pathologie :", None))
        self.comboBox.setToolTip(_translate("MainWindow", "Choisir une Pathologie Dominante pour cette Consultation", None))
        self.toolButton_Pathologie.setToolTip(_translate("MainWindow", "Ouvre un plan thérapeutique", None))
        self.toolButton_Pathologie.setText(_translate("MainWindow", "...", None))
        self.toolButton_comment.setText(_translate("MainWindow", "...", None))
        self.label_14.setText(_translate("MainWindow", "Observations :", None))
        self.textEdit_consultObs.setToolTip(_translate("MainWindow", "Insérer les observations cliniques", None))
        self.label_15.setText(_translate("MainWindow", "Traitements :", None))
        self.textEdit_consultTrait.setToolTip(_translate("MainWindow", "Inserez les traitements", None))
        self.pushButton_valider.setToolTip(_translate("MainWindow", "Enregistrer cette consultation", None))
        self.pushButton_valider.setText(_translate("MainWindow", "Valider", None))
        self.pushButton_Nouveau.setToolTip(_translate("MainWindow", "Nouvelle Consultation", None))
        self.pushButton_Nouveau.setText(_translate("MainWindow", "Nouveau", None))
        self.pushButton_Hospit.setToolTip(_translate("MainWindow", "Imprimer la fiche d\'hospitalisation", None))
        self.pushButton_Hospit.setText(_translate("MainWindow", "Hospitalisation", None))
        self.pushButton_Facturation.setToolTip(_translate("MainWindow", "Basculer en facturation", None))
        self.pushButton_Facturation.setText(_translate("MainWindow", "Facturation", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_consulation), _translate("MainWindow", "Consultation", None))
        self.toolButton_fichier.setText(_translate("MainWindow", "...", None))
        self.pushButton_addImage.setToolTip(_translate("MainWindow", "Ajouter une nouvelle image à l\'examen", None))
        self.pushButton_addImage.setText(_translate("MainWindow", "Ajouter image", None))
        self.label_5.setText(_translate("MainWindow", "Type d\'analyse :  ", None))
        self.label_3.setText(_translate("MainWindow", "Analyses précédentes", None))
        self.listView.setStatusTip(_translate("MainWindow", "Double click pour éditer l\'analyse", None))
        self.label_4.setText(_translate("MainWindow", "Date Heure :  ", None))
        self.dateTimeEdit_analyse.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy HH:mm", None))
        self.label_6.setText(_translate("MainWindow", "Description de l\'analyse:", None))
        self.label_7.setText(_translate("MainWindow", "Prélèvement :", None))
        self.label_8.setText(_translate("MainWindow", "Observations :", None))
        self.label_9.setText(_translate("MainWindow", "Conclusions :", None))
        self.pushButton_valide.setToolTip(_translate("MainWindow", "Ajouter l\'analyse au dossier", None))
        self.pushButton_valide.setText(_translate("MainWindow", "Valider", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_analyses), _translate("MainWindow", "Analyses", None))
        self.label_RCP.setText(_translate("MainWindow", "Mentions légales :", None))
        self.toolButton.setToolTip(_translate("MainWindow", "Texte complet", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.toolButton_2.setToolTip(_translate("MainWindow", "Résumé", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.label_medicament.setText(_translate("MainWindow", "Médicament :", None))
        self.label_molecule.setText(_translate("MainWindow", "Molécule :", None))
        self.label_posomol.setText(_translate("MainWindow", "Posologie de principe actif :", None))
        self.label_presentation.setText(_translate("MainWindow", "Présentation :", None))
        self.label_posomed.setText(_translate("MainWindow", "Posologie de médicament :", None))
        self.label_especeCible.setText(_translate("MainWindow", "Espèce cible :", None))
        self.pushButton_validOrdonnance.setText(_translate("MainWindow", "Valider", None))
        self.pushButton_CalculPoso.setText(_translate("MainWindow", "Calculatrice", None))
        self.pushButton_DMV.setText(_translate("MainWindow", "Editer DMV", None))
        self.label_10.setText(_translate("MainWindow", "Le :", None))
        self.dateEdit_ordonance.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.label_11.setText(_translate("MainWindow", "Poids :", None))
        self.pushButton_OrdonnanceValid.setText(_translate("MainWindow", "Valider", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_ordonnances), _translate("MainWindow", "Ordonnances", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_planTherapeutique), _translate("MainWindow", "Plan Thérapeutique", None))
        self.label_doc.setText(_translate("MainWindow", "Documents disponibles :", None))
        self.label_docDate.setText(_translate("MainWindow", "Date :", None))
        self.dateEdit_docDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.label_docFile.setText(_translate("MainWindow", "Fichier :", None))
        self.toolButton_docFile.setToolTip(_translate("MainWindow", "Selectionner un fichier", None))
        self.toolButton_docFile.setText(_translate("MainWindow", "...", None))
        self.pushButton_docAdd.setToolTip(_translate("MainWindow", "Ajouter nouveau document au dossier", None))
        self.pushButton_docAdd.setText(_translate("MainWindow", "Ajouter", None))
        self.tabWidget_medical.setTabText(self.tabWidget_medical.indexOf(self.tab_documents), _translate("MainWindow", "Documents", None))
        self.toolButton_addClient.setToolTip(_translate("MainWindow", "Nouveau client", None))
        self.toolButton_addClient.setText(_translate("MainWindow", "...", None))
        self.toolButton_deleteClient.setToolTip(_translate("MainWindow", "Efface client", None))
        self.toolButton_deleteClient.setText(_translate("MainWindow", "...", None))
        self.toolButton_editClient.setToolTip(_translate("MainWindow", "Modifie client", None))
        self.toolButton_editClient.setText(_translate("MainWindow", "...", None))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche1), _translate("MainWindow", "Client1", None))
        self.menuDossiers_M_dicaux.setTitle(_translate("MainWindow", "Dossiers Médicaux", None))
        self.menuComptabilit.setTitle(_translate("MainWindow", "Comptabilité", None))
        self.menuD_clarations.setTitle(_translate("MainWindow", "Déclarations", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Paramètres", None))
        self.menuBase_de_donn_es.setTitle(_translate("MainWindow", "Base de données", None))
        self.menuQuitter.setTitle(_translate("MainWindow", "Quitter", None))
        self.menuStock.setTitle(_translate("MainWindow", "Stock", None))
        self.menuStatistiques.setTitle(_translate("MainWindow", "Statistiques", None))
        self.action_Recettes.setText(_translate("MainWindow", "&Recettes", None))
        self.actionD_penses.setText(_translate("MainWindow", "&Dépenses", None))
        self.action_Banque.setText(_translate("MainWindow", "&Banque", None))
        self.actionRecoupement_bancaire.setText(_translate("MainWindow", "Recoupement bancaire", None))
        self.actionTVA.setText(_translate("MainWindow", "TVA", None))
        self.action2035.setText(_translate("MainWindow", "2035", None))
        self.actionCommandes.setText(_translate("MainWindow", "&Commandes", None))
        self.actionAnalyse.setText(_translate("MainWindow", "Visualisation", None))
        self.action_Facturation.setText(_translate("MainWindow", "&Facturation", None))
        self.actionBureau.setText(_translate("MainWindow", "Bureau", None))
        self.actionBureau.setShortcut(_translate("MainWindow", "Ctrl+Alt+B", None))
        self.action_M_dicaments.setText(_translate("MainWindow", "&Médicaments", None))
        self.action_Pathologies.setText(_translate("MainWindow", "&Pathologies", None))
        self.actionBackup.setText(_translate("MainWindow", "Backup", None))
        self.actionRestore.setText(_translate("MainWindow", "Restore", None))
        self.actionImport.setText(_translate("MainWindow", "Import", None))
        self.actionR_seau_S_curit.setText(_translate("MainWindow", "Réseau/Sécurité", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.actionQuitter.setToolTip(_translate("MainWindow", "Quitter l\'application", None))
        self.actionQuitter.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

import resources_rc
